/* ═══════════════════════════════════════════════════════════════════════════
   MENTORA AI — TOPIC MODEL ANSWERS
   Actual model answers for every subject/topic pair used by the past-paper
   generator, replacing the old generic answer instructions. Each entry has:
     · definition — one crisp line, used as the MCQ explanation
     · short      — 4-5 step model answer for Section B (short questions)
     · long       — 7-9 step detailed model answer for Section C, with a
                    worked example where the topic is quantitative
   Keys follow `${subjectId}::${topic}` and must match TOPICS_BY_SUBJECT.
═══════════════════════════════════════════════════════════════════════════ */

export type ModelAnswer = {
  definition: string;
  short: string[];
  long: string[];
};

export const MODEL_ANSWERS: Record<string, ModelAnswer> = {

/* ─────────────────────────── MATHEMATICS ─────────────────────────── */
"math::Algebra Basics": {
  definition: "Algebra generalizes arithmetic by using letters for unknown numbers, so rules and equations can be written once and applied to any value.",
  short: [
    "Algebra uses letters (x, y) called variables to represent unknown numbers, letting general rules be written once and used for any value.",
    "In the term 5x², 5 is the coefficient and 2 is the power. Like terms have the same variables and powers, so 5x + 3x = 8x.",
    "An expression (3x + 2) has no equals sign; an equation (3x + 2 = 11) states that two expressions are equal.",
    "The order of operations (BODMAS) applies in all simplification: brackets, powers, division/multiplication, then addition/subtraction.",
    "Example: simplify 4x + 3 − x + 5 = 3x + 8.",
  ],
  long: [
    "Algebra is the branch of mathematics in which letters stand for unknown or general numbers; it turns arithmetic rules into reusable formulas.",
    "Key vocabulary: variable, constant, coefficient, term, expression and equation. In 2a − 3b + 7, there are two variables, one constant and coefficients 2 and −3.",
    "Like terms are combined by adding their coefficients: 7y − 2y + y = 6y. Unlike terms (x and x²) cannot be merged.",
    "Brackets are removed by multiplying every term inside: 3(x + 2) = 3x + 6.",
    "Substitution means replacing letters with values: for a = 4 and b = 1, the expression 2a − 3b = 2(4) − 3(1) = 5.",
    "Phrases translate into algebra: 'five more than a number' → x + 5, 'twice a number' → 2x, 'a number squared minus three' → x² − 3.",
    "Worked example: evaluate 3(x + 2) − 2x when x = 5. Expand: 3x + 6 − 2x = x + 6. Substitute: 5 + 6 = 11.",
    "Always finish by checking: re-substituting x = 5 in the original gives 3(7) − 10 = 11 ✓.",
    "Mastery of these basics is essential — every later topic (equations, graphs, word problems) is built on them.",
  ],
},
"math::Variables & Expressions": {
  definition: "A variable is a symbol representing an unknown or changing value; an expression combines variables, constants and operations into a single mathematical phrase.",
  short: [
    "A variable (x, n) represents an unknown or changing quantity; a constant (7) never changes within a problem.",
    "An expression combines variables and constants with operations, e.g. 3n + 5 has coefficient 3, variable n and constant 5.",
    "To evaluate an expression, substitute the given value: if x = 4, then 2x + 1 = 2(4) + 1 = 9.",
    "Common translations: 'the sum of a number and its square' → n + n², 'three less than twice a number' → 2n − 3.",
    "Formulas are expression recipes: with length 8 and width 3, area A = lw = 8 × 3 = 24.",
  ],
  long: [
    "Variables and expressions are the grammar of algebra: variables stand for quantities that can change or are unknown, and expressions record a calculation using them.",
    "An expression is evaluated by substitution. Example: for p = 6, the expression 4p − 7 gives 24 − 7 = 17.",
    "A table of values shows how an expression behaves: for 2x + 1 with x = 1, 2, 3, 4 the outputs are 3, 5, 7, 9 — each input gives exactly one output.",
    "Expressions can be simplified by collecting like terms: 5a + 2b − 3a + b = 2a + 3b.",
    "Real-life example: the cost of n notebooks at 50 each plus a 200 delivery fee is the expression C = 50n + 200; for n = 6, C = 500.",
    "Expressions differ from equations: 3(x + 1) is an expression to simplify, while 3(x + 1) = 12 is an equation to solve.",
    "Worked example: evaluate (x² − 4)/(x + 2) at x = 3: numerator 9 − 4 = 5, denominator 5, so the value is 1.",
    "Care points: follow BODMAS, substitute negative values in brackets, e.g. x = −2 in x² gives (−2)² = 4.",
    "Fluency in building and evaluating expressions is the foundation of equation solving and graph work.",
  ],
},
"math::Linear Equations": {
  definition: "A linear equation contains the variable raised only to the first power (ax + b = c); it has exactly one solution and its graph is a straight line.",
  short: [
    "A linear equation has the variable to the power 1 only, e.g. 3x − 7 = 11; it has exactly one solution.",
    "Balance method: perform the same operation on both sides — undo addition/subtraction first, then multiplication/division.",
    "Solve 3x − 7 = 11: add 7 → 3x = 18; divide by 3 → x = 6.",
    "Check the solution: 3(6) − 7 = 18 − 7 = 11 ✓.",
    "With brackets, expand first: 2(x + 3) = 14 → 2x + 6 = 14 → x = 4.",
  ],
  long: [
    "A linear equation in one variable is one where the variable appears only to the first power; solving it means finding the value that balances both sides.",
    "Rules of balancing: whatever is done to one side must be done to the other; undo operations in reverse BODMAS order.",
    "Basic example: solve 5x + 4 = 19. Subtract 4: 5x = 15. Divide by 5: x = 3. Check: 5(3) + 4 = 19 ✓.",
    "Equations with brackets: 3(x − 2) = 12 → 3x − 6 = 12 → 3x = 18 → x = 6.",
    "Equations with fractions: x/2 + 1 = 5 → subtract 1 → x/2 = 4 → multiply by 2 → x = 8.",
    "Variables on both sides: 5x − 3 = 2x + 9 → subtract 2x: 3x − 3 = 9 → add 3: 3x = 12 → x = 4.",
    "Combined example: 2(x + 1) = x + 7 → 2x + 2 = x + 7 → x = 5. Verify: 2(6) = 12 and 5 + 7 = 12 ✓.",
    "Common errors: forgetting to apply an operation to both sides, and sign slips when moving terms.",
    "Every linear equation in one variable has exactly one solution, which is why checking by substitution is always possible.",
  ],
},
"math::Equation Solving": {
  definition: "Solving an equation means finding the value of the variable that makes the left-hand side equal to the right-hand side, using inverse operations applied to both sides.",
  short: [
    "A solution is the value of the variable that makes the equation true; solving uses inverse operations while keeping both sides balanced.",
    "Undo operations in reverse BODMAS order: remove +/− first, then ×/÷, then expand brackets.",
    "Example: (2x + 1)/3 = 5 → multiply by 3: 2x + 1 = 15 → subtract 1: 2x = 14 → divide by 2: x = 7.",
    "Check by substitution: (2×7 + 1)/3 = 15/3 = 5 ✓.",
    "When variables appear on both sides (4x − 5 = x + 13), collect them on one side first: 3x = 18 → x = 6.",
  ],
  long: [
    "Equation solving is the process of isolating the variable on one side of the equals sign using lawful, balanced moves.",
    "The two lawful moves are: (1) add or subtract the same quantity on both sides, (2) multiply or divide both sides by the same non-zero quantity.",
    "Strategy: expand brackets, clear fractions by multiplying by the LCM, gather variable terms on one side and constants on the other, then divide by the coefficient.",
    "Worked example 1: 4(x − 1) = 2x + 6 → 4x − 4 = 2x + 6 → 2x = 10 → x = 5. Check: 4(4) = 16 and 2(5) + 6 = 16 ✓.",
    "Worked example 2 (fractions): (x − 3)/2 = (x + 1)/3. Multiply by 6: 3(x − 3) = 2(x + 1) → 3x − 9 = 2x + 2 → x = 11. Check: 8/2 = 4 and 12/3 = 4 ✓.",
    "Worked example 3 (brackets and negatives): 3(2x − 1) − 4 = 2(x + 3) → 6x − 3 − 4 = 2x + 6 → 6x − 7 = 2x + 6 → 4x = 13 → x = 13/4.",
    "Verification is part of the solution, not an extra step: substitute the answer back into the ORIGINAL equation.",
    "Common errors: multiplying only one term by the LCM, dropping a minus sign when moving terms, and dividing by a coefficient that is zero.",
    "Word problems become solvable equations: 'a number increased by 7 equals 15' → x + 7 = 15 → x = 8.",
  ],
},
"math::Word Problems": {
  definition: "A word problem describes a real situation in words; solving it means translating the words into an equation, solving it, and interpreting the result in context.",
  short: [
    "Steps: read carefully, choose a variable for the unknown, translate each statement into an equation, solve, then check the answer against the story.",
    "Consecutive integers: 'the sum of two consecutive integers is 47.' Let them be x and x + 1: x + (x + 1) = 47 → 2x = 46 → x = 23, so the integers are 23 and 24.",
    "Age problem: 'A father is 3 times as old as his son and together they are 48.' Son = x, father = 3x: 4x = 48 → son 12, father 36.",
    "Money problem: '5 pens cost the same as 3 notebooks at 60 each': 5p = 180 → p = 36.",
    "Always finish with a sentence that answers the question asked, with correct units.",
  ],
  long: [
    "A word problem is an equation dressed in everyday language. The solver's job is translation, solution and interpretation.",
    "Step 1 — Read and identify: what is asked? What facts are given? Draw a sketch or table if quantities are related.",
    "Step 2 — Define the variable clearly: 'let x be the smaller number' or 'let x be the cost of one pen'.",
    "Step 3 — Translate keywords: sum (+), difference (−), of (×), is (=), twice (2×), 'less than' reverses order (5 − x).",
    "Step 4 — Form and solve the equation.",
    "Worked example (numbers): 'The sum of a number and twice the number is 36.' x + 2x = 36 → 3x = 36 → x = 12; the number is 12.",
    "Worked example (speed): 'A car travels at 60 km/h. How long to cover 180 km?' d = st → 180 = 60t → t = 3 hours.",
    "Worked example (geometry): 'The perimeter of a rectangle is 30 cm and its length is twice its width.' 2(l + w) = 30 with l = 2w gives 2(3w) = 30 → w = 5, l = 10 cm.",
    "Step 5 — Check reasonableness: a negative age or a 300 km/h bus signals an error; re-read the problem.",
  ],
},
"math::Graphing Lines": {
  definition: "Every linear equation y = mx + c graphs as a straight line with gradient (slope) m and y-intercept c.",
  short: [
    "The gradient-intercept form y = mx + c describes a straight line: m is the gradient (steepness) and c is the y-intercept (crossing point on the y-axis).",
    "Gradient m = rise/run = (y₂ − y₁)/(x₂ − x₁); a positive m slopes upward, a negative m slopes downward.",
    "To plot: make a table of x values, compute y, plot the points and join them with a ruler.",
    "Example: y = 2x + 1 passes through (0, 1), (1, 3) and (2, 5).",
    "Parallel lines have equal gradients; changing c slides the line up or down.",
  ],
  long: [
    "Graphing a linear equation means drawing all points (x, y) that satisfy it; these points always lie on one straight line.",
    "From y = mx + c: m = gradient = vertical change ÷ horizontal change, and c = the y-value where the line cuts the y-axis (x = 0).",
    "Plotting y = 2x + 1: for x = 0, 1, 2 the y-values are 1, 3, 5. Plot (0, 1), (1, 3), (2, 5); the line rises 2 units for each 1 unit across.",
    "Intercepts method (fast): put x = 0 to get the y-intercept and y = 0 to get the x-intercept; join the two points.",
    "For y = 2x + 1: x = 0 gives y = 1; y = 0 gives x = −1/2. The line crosses the axes at (0, 1) and (−0.5, 0).",
    "Special cases: y = k is a horizontal line (gradient 0); x = k is a vertical line (gradient undefined).",
    "Finding the equation from two points, e.g. (1, 3) and (2, 5): m = (5 − 3)/(2 − 1) = 2, then y = 2x + c; using (1, 3): 3 = 2 + c → c = 1, so y = 2x + 1.",
    "Checking: any point on the line must satisfy the equation — (2, 5) gives 5 = 2(2) + 1 ✓.",
    "Applications: converting currencies, uniform speed (distance–time graphs) and break-even analysis all use straight-line graphs.",
  ],
},

/* ─────────────────────────── PHYSICS ─────────────────────────── */
"physics::Kinematics": {
  definition: "Kinematics is the study of motion — distance, displacement, speed, velocity and acceleration — without reference to the forces that cause the motion.",
  short: [
    "Kinematics describes motion with four quantities: distance (scalar), displacement (vector), speed and velocity.",
    "Average speed = distance / time; average velocity = displacement / time.",
    "Acceleration is the rate of change of velocity: a = (v − u)/t, with unit m/s².",
    "The three equations of motion (for uniform acceleration) are v = u + at, s = ut + ½at² and v² = u² + 2as.",
    "Example: a car starting from rest with a = 2 m/s² reaches v = u + at = 0 + 2×5 = 10 m/s after 5 s.",
  ],
  long: [
    "Kinematics studies how objects move — position, distance, displacement, speed, velocity and acceleration — without asking why they move.",
    "Distance is the total path length (scalar); displacement is the shortest straight-line change in position with direction (vector). Walking 3 m east then 4 m north gives distance 7 m but displacement 5 m.",
    "Speed is distance/time; velocity is displacement/time and carries direction. A body can have constant speed yet changing velocity (circular motion).",
    "Acceleration a = (v − u)/t: positive when speeding up, negative (deceleration) when slowing down.",
    "The three equations of motion for uniform acceleration: v = u + at, s = ut + ½at², v² = u² + 2as.",
    "Worked example: a car starts from rest (u = 0) with a = 2 m/s² for t = 5 s. Final velocity v = 0 + 2×5 = 10 m/s. Distance s = 0 + ½(2)(25) = 25 m. Check with v² = u² + 2as: 100 = 0 + 2(2)(25) ✓.",
    "Graph reading: the slope of a distance–time graph gives speed; the slope of a velocity–time graph gives acceleration; the area under a velocity–time graph gives distance.",
    "Free fall: ignoring air resistance, all bodies fall with g ≈ 9.8 m/s², so the same equations apply with a = g.",
    "Everyday uses: braking distances of vehicles, projectile paths and athletics timing all follow kinematic equations.",
  ],
},
"physics::Forces & Motion": {
  definition: "Dynamics relates force to motion through Newton's three laws: the law of inertia, F = ma, and the action–reaction principle.",
  short: [
    "Force is a push or pull that changes a body's state of rest or motion; its SI unit is the newton (N), where 1 N = 1 kg·m/s².",
    "Newton's 1st law (inertia): a body remains at rest or in uniform motion unless acted upon by a net force.",
    "Newton's 2nd law: F = ma. A 10 kg body pushed by 50 N accelerates at 5 m/s².",
    "Newton's 3rd law: every action has an equal and opposite reaction — a rocket pushes gas down, the gas pushes the rocket up.",
    "Momentum p = mv (unit Ns) is conserved in an isolated system, e.g. during collisions and recoil.",
  ],
  long: [
    "Force is the agency that tries to change a body's state of rest or of uniform motion. Forces are measured in newtons and are vectors.",
    "Newton's first law explains inertia: passengers lurch forward when a bus brakes because their bodies tend to keep moving.",
    "Newton's second law quantifies force: F = ma. Worked example: a 1000 kg car accelerates from 10 m/s to 30 m/s in 5 s, so a = 20/5 = 4 m/s² and F = 1000 × 4 = 4000 N.",
    "Newton's third law pairs act on different bodies: the gun pushes the bullet forward, the bullet pushes the gun backward (recoil).",
    "Mass (kg) measures inertia; weight is the gravitational force on a body, W = mg — a 5 kg mass weighs 50 N where g = 10 m/s².",
    "Momentum p = mv. Law of conservation of momentum: total momentum before = total momentum after a collision, provided no external force acts.",
    "Example: a 20 g bullet at 300 m/s fired from a 2 kg rifle: 0.02 × 300 = 2 × v gives recoil v = 3 m/s in the opposite direction.",
    "Friction is the force opposing relative motion; it is useful (brakes, walking) and harmful (energy loss, wear).",
    "Free-body thinking: only the NET force matters — balanced forces mean constant velocity, unbalanced forces mean acceleration.",
  ],
},
"physics::Work & Energy": {
  definition: "Work is done when a force moves its point of application through a distance (W = Fd); energy is the capacity to do work, and total energy is conserved.",
  short: [
    "Work W = F × d (unit joule), where d is the distance moved in the direction of the force; no motion means no work done.",
    "Kinetic energy KE = ½mv²; potential energy PE = mgh.",
    "Power is the rate of doing work: P = W/t, unit watt (1 W = 1 J/s).",
    "Law of conservation of energy: energy only changes form — a falling ball converts PE into KE while the total stays constant.",
    "Example: a 2 kg ball dropped from 20 m has PE = 2×10×20 = 400 J, which becomes KE = 400 J (v = 20 m/s) just before impact.",
  ],
  long: [
    "Work, energy and power link force to motion over time. Work is only done when the point of application of a force actually moves along the force's direction.",
    "Work W = Fd cosθ. Carrying a bag while walking on level ground does zero work on the bag (force vertical, motion horizontal).",
    "Energy is the ability to do work, also measured in joules. Kinetic energy KE = ½mv²; potential energy PE = mgh.",
    "Worked example (KE): a 5 kg body moving at 10 m/s has KE = ½ × 5 × 100 = 250 J.",
    "Worked example (power): a crane lifts a 500 kg load by 12 m in 10 s. Work = mgh = 500×10×12 = 60000 J, so power P = 60000/10 = 6000 W = 6 kW.",
    "Law of conservation of energy: energy can neither be created nor destroyed, only transformed. A falling body trades PE for KE: at half height, PE = KE = 200 J for the 2 kg/20 m ball.",
    "Efficiency = useful energy output ÷ total energy input × 100%; no machine is 100% efficient because friction converts some input into heat.",
    "Energy sources are renewable (solar, wind, hydro) or non-renewable (fossil fuels); both ultimately appear as usable electrical or mechanical energy.",
    "Everyday example: eating food (chemical energy) powers walking (kinetic energy) while the body warms (heat energy) — the energy account always balances.",
  ],
},
"physics::Waves & Sound": {
  definition: "A wave is a disturbance that transfers energy without transferring matter; sound is a longitudinal mechanical wave produced by vibrations.",
  short: [
    "A wave carries energy from place to place without transferring matter.",
    "Transverse waves (light, water ripples) vibrate perpendicular to the direction of travel; longitudinal waves (sound) vibrate parallel, forming compressions and rarefactions.",
    "Amplitude is the maximum displacement; frequency (Hz) is the number of waves per second; wavelength λ is the distance between consecutive crests.",
    "Wave equation: v = fλ — a 500 Hz sound at 340 m/s has λ = 340/500 = 0.68 m.",
    "Sound needs a medium, travels fastest in solids, and cannot travel through a vacuum.",
  ],
  long: [
    "A wave is a travelling disturbance that transports energy, not material — a floating cork bobs up and down as ripples pass, but does not travel with them.",
    "Two types by vibration direction: transverse (light, water waves) with crests and troughs; longitudinal (sound) with compressions and rarefactions.",
    "Wave vocabulary: amplitude (loudness/brightness), frequency f in hertz (pitch), wavelength λ in metres, period T = 1/f.",
    "The wave equation v = fλ links speed, frequency and wavelength. Worked example: v = 340 m/s, f = 500 Hz → λ = 340/500 = 0.68 m.",
    "Sound is produced by vibrating bodies (a plucked string), needs a medium and travels at about 340 m/s in air, faster in water and fastest in steel.",
    "Pitch depends on frequency; loudness depends on amplitude; quality (timbre) distinguishes instruments playing the same note.",
    "Echo problem: a person 340 m from a cliff claps. Sound covers 2 × 340 = 680 m, so the echo returns after 680/340 = 2 s.",
    "Human hearing range is 20 Hz to 20 000 Hz; ultrasound (above 20 kHz) is used in medical imaging and sonar.",
    "Reflection of sound explains echoes; refraction and diffraction explain why sound bends around corners and through open doors.",
  ],
},
"physics::Current Electricity": {
  definition: "Current electricity is the flow of electric charge through a conductor, governed by Ohm's law V = IR.",
  short: [
    "Electric current I = Q/t is the rate of flow of charge; unit ampere (A), where 1 A = 1 C/s.",
    "Ohm's law: V = IR at constant temperature — a 6 Ω resistor across a 9 V battery carries I = 9/6 = 1.5 A.",
    "Series: R = R₁ + R₂ + …; Parallel: 1/R = 1/R₁ + 1/R₂ + ….",
    "Electrical power P = VI = I²R, and energy in kWh (units) = power (kW) × time (hours).",
    "Example: 4 Ω and 12 Ω in parallel give 1/R = 1/4 + 1/12 = 4/12, so R = 3 Ω.",
  ],
  long: [
    "Current electricity deals with charges in motion. Conventional current flows from the positive to the negative terminal, while electrons flow the opposite way.",
    "Current I = Q/t: a charge of 12 C flowing in 4 s means I = 3 A.",
    "Ohm's law: at constant temperature, V = IR. Example: a 6 Ω resistor on a 9 V supply draws 1.5 A.",
    "Series combination: the same current passes through each resistor and resistances add (R = R₁ + R₂). Parallel: the same voltage appears across each and 1/R = 1/R₁ + 1/R₂.",
    "Worked example: 2 Ω, 3 Ω and 6 Ω in parallel across 12 V. 1/R = 1/2 + 1/3 + 1/6 = 1, so R = 1 Ω; total current I = 12/1 = 12 A; branch currents are 12/2 = 6 A, 12/3 = 4 A, 12/6 = 2 A (sum 12 A ✓).",
    "Electric power P = VI = I²R = V²/R. A 100 W bulb on for 10 hours uses 100 × 10 = 1000 Wh = 1 kWh, i.e. one electricity unit.",
    "Joule's law of heating: H = I²Rt — a 20 Ω heater drawing 5 A for 2 minutes (120 s) produces H = 25 × 20 × 120 = 60000 J = 60 kJ.",
    "Safety devices: a fuse melts when current exceeds a safe value; earthing provides a low-resistance path that protects users from shocks.",
    "Circuit analysis tip: reduce series and parallel groups step by step until a single equivalent resistance remains, then work backwards for currents.",
  ],
},
"physics::Heat & Thermodynamics": {
  definition: "Heat is thermal energy transferred because of a temperature difference, while temperature measures the average kinetic energy of a body's particles.",
  short: [
    "Heat is energy in transit from a hot body to a cold body; temperature (°C or K) measures how hot a body is, with 0 °C = 273 K.",
    "Heat travels by conduction (through solids, by particle vibration), convection (through fluids, by bulk movement) and radiation (electromagnetic waves, no medium needed).",
    "Specific heat capacity c is the heat needed to raise 1 kg of a substance by 1 K: Q = mcΔT; for water c = 4200 J/kg·K.",
    "Example: heating 2 kg of water by 30 °C needs Q = 2 × 4200 × 30 = 252000 J.",
    "Latent heat is the heat absorbed or released during a change of state at constant temperature.",
  ],
  long: [
    "Heat is the total kinetic energy transferred between bodies at different temperatures; temperature is the average kinetic energy of the particles — heat flows from hot to cold until both are equal.",
    "Three modes of transfer: conduction (solids, particle-to-particle vibration), convection (liquids/gases, hot fluid rises and cold sinks), radiation (infrared waves, works even through vacuum).",
    "Thermos flask design defeats all three modes: vacuum stops conduction and convection, silvered walls reflect radiation.",
    "Specific heat capacity: Q = mcΔT. Worked example: to raise 2 kg of water by 30 °C requires Q = 2 × 4200 × 30 = 252000 J; water's high c makes it a good coolant.",
    "Changes of state: melting, freezing, evaporation, condensation and sublimation (iodine, dry ice). During a state change the temperature stays constant while latent heat is absorbed or released.",
    "Evaporation (surface phenomenon, at any temperature) differs from boiling (whole bulk, at a fixed temperature); evaporation increases with temperature, surface area and wind.",
    "Applications: land and sea breezes are convection currents; metals feel cold because they conduct heat away from the skin quickly.",
    "First law of thermodynamics: heat supplied = increase in internal energy + work done by the body (energy conservation for thermal systems).",
    "Scale conversion: K = °C + 273, so 100 °C (boiling water) = 373 K.",
  ],
},

/* ─────────────────────────── CHEMISTRY ─────────────────────────── */
"chemistry::Atomic Structure": {
  definition: "An atom consists of a nucleus of protons and neutrons surrounded by electrons arranged in shells; the atomic number Z equals the number of protons.",
  short: [
    "An atom has a central nucleus containing protons (+1 charge) and neutrons (0), with electrons (−1) revolving around it in shells K, L, M…",
    "Atomic number Z = number of protons; mass number A = protons + neutrons.",
    "Maximum electrons per shell follow 2n²: K = 2, L = 8, M = 18.",
    "Electronic configuration of sodium (Z = 11): 1s² 2s² 2p⁶ 3s¹ — shells K = 2, L = 8, M = 1.",
    "Valency follows the outermost shell: sodium loses its single M-shell electron, giving valency 1 (Na⁺).",
  ],
  long: [
    "The atom is the smallest particle of an element that takes part in chemical reactions. Rutherford's experiment showed a tiny positive nucleus; Bohr arranged electrons in fixed shells.",
    "Sub-atomic particles: proton (charge +1, mass 1 u) and neutron (0 charge, 1 u) in the nucleus; electron (−1, negligible mass) in shells.",
    "Atomic number Z = protons = electrons in a neutral atom; mass number A = protons + neutrons. For carbon, Z = 6 and A = 12, so neutrons = 6.",
    "Shell capacity follows 2n². Configurations are written shell by shell: Cl (Z = 17) → K = 2, L = 8, M = 7.",
    "Valency from configuration: atoms tend to reach a full outer shell. Cl needs 1 electron (valency 1); Na sheds 1 (valency 1); Ca sheds 2 (valency 2).",
    "Isotopes are atoms of the same element with the same Z but different A: H-1 (protium), H-2 (deuterium), H-3 (tritium).",
    "Isotope uses: C-14 dating of fossils, Co-60 cancer therapy and I-131 thyroid treatment.",
    "The number of electrons equals the number of protons in a neutral atom; ions form when electrons are lost (cations) or gained (anions).",
    "Worked example: calcium-40 (₂₀Ca⁴⁰) has 20 protons, 20 neutrons and 20 electrons; the Ca²⁺ ion has lost two electrons, leaving 18.",
  ],
},
"chemistry::Chemical Bonding": {
  definition: "Chemical bonding joins atoms into stable structures with noble-gas electron arrangements, mainly by electron transfer (ionic) or electron sharing (covalent).",
  short: [
    "Atoms bond to achieve a complete outer shell like the noble gases.",
    "Ionic bond: complete transfer of electrons from a metal to a non-metal — Na gives one electron to Cl, forming Na⁺ and Cl⁻ held by electrostatic attraction.",
    "Covalent bond: sharing of electron pairs — H₂O has two O–H shared pairs and CH₄ has four C–H bonds.",
    "Ionic compounds are hard crystalline solids with high melting points and conduct electricity in solution; covalent compounds usually have low melting points and do not conduct.",
    "A coordinate covalent bond forms when one atom donates both shared electrons, as in NH₄⁺.",
  ],
  long: [
    "A chemical bond is the force of attraction that holds atoms together in a compound; bonding is driven by the tendency to reach a stable (octet) outer shell.",
    "Ionic (electrovalent) bond: transfer of electrons. Na (2,8,1) hands its outer electron to Cl (2,8,7); the resulting Na⁺ and Cl⁻ ions attract each other into a giant lattice — NaCl.",
    "Covalent bond: sharing of electrons between non-metals. In water, oxygen shares one pair with each of two hydrogens; in methane, carbon shares one pair with each of four hydrogens.",
    "Coordinate (dative) bond: both shared electrons come from the same atom, e.g. NH₃ donating its lone pair to H⁺ to make NH₄⁺.",
    "Metallic bonding: positive metal ions in a sea of delocalized electrons — this explains conductivity and malleability of metals.",
    "Property comparison: ionic compounds — crystalline, high m.p./b.p., conduct when molten or dissolved; covalent compounds — often gases/liquids or soft solids, low m.p., non-conductors (except acids in water).",
    "Polarity: unequal sharing in covalent bonds (H–Cl) creates partial charges and polar molecules; non-polar bonds share equally (H₂, Cl₂).",
    "Intermolecular forces (hydrogen bonding in water) are weaker than actual bonds but explain boiling points and solubility.",
    "Bonding decides the formula of every compound: valencies cross over, e.g. Al³⁺ with O²⁻ gives Al₂O₃.",
  ],
},
"chemistry::States of Matter": {
  definition: "The three states of matter — solid, liquid and gas — differ in particle arrangement, motion and energy; heating or cooling converts one state into another.",
  short: [
    "Solids: particles closely packed in fixed positions, only vibrating — definite shape and volume. Liquids: particles touch but slide past each other — definite volume, shape of the container. Gases: particles far apart and free-moving — fill the container.",
    "Changes of state: melting (solid→liquid), freezing, evaporation/boiling (liquid→gas), condensation (gas→liquid) and sublimation (solid→gas directly, e.g. iodine or dry ice).",
    "The kinetic molecular theory explains states: heating raises particle kinetic energy, increasing spacing and movement.",
    "Boyle's law: at constant temperature, P ∝ 1/V. Charles' law: at constant pressure, V ∝ T (in kelvin).",
    "Diffusion and Brownian motion are experimental evidence that particles move.",
  ],
  long: [
    "Matter exists in three familiar states whose differences are explained by the kinetic molecular theory: particles are in constant motion, and their spacing and energy define the state.",
    "Solid: fixed shape and volume, particles vibrate about fixed lattice points, strongest forces. Liquid: fixed volume but takes the container's shape, particles slide. Gas: neither fixed shape nor volume, particles fly freely with negligible forces.",
    "State changes with names: melting (ice→water), freezing, evaporation (surface) and boiling (throughout, at fixed temperature), condensation, and sublimation (iodine, camphor, dry ice go straight from solid to gas).",
    "During a change of state the temperature remains constant because the energy supplied is used as latent heat to break attractions rather than to raise temperature.",
    "Boyle's law (constant T): P₁V₁ = P₂V₂ — squeezing a gas into half its volume doubles the pressure.",
    "Charles' law (constant P): V₁/T₁ = V₂/T₂. Worked example: a 300 cm³ gas at 300 K warms to 600 K at the same pressure; V₂ = 300 × 600/300 = 600 cm³.",
    "Diffusion: gases mix by themselves (smell of perfume spreading); rate is faster for lighter gases (hydrogen diffuses faster than oxygen).",
    "Brownian motion — pollen grains jiggle in water — is visible evidence of invisible molecular collisions.",
    "Plasma (ionized gas, in the sun and neon signs) is called the fourth state of matter.",
  ],
},
"chemistry::Stoichiometry": {
  definition: "Stoichiometry is the quantitative study of reactants and products in chemical reactions, based on balanced equations and the mole concept.",
  short: [
    "A mole contains 6.022 × 10²³ particles (Avogadro's number); the molar mass in g/mol equals the formula mass in amu.",
    "Moles = given mass ÷ molar mass; e.g. 36 g of H₂O = 36/18 = 2 mol.",
    "A balanced equation gives the mole ratio: CH₄ + 2O₂ → CO₂ + 2H₂O means 1 mol of methane needs 2 mol of oxygen.",
    "Example: burning 12 g of carbon (1 mol) produces 1 mol of CO₂ = 44 g.",
    "Avogadro's law: equal volumes of all gases at the same temperature and pressure contain equal numbers of molecules.",
  ],
  long: [
    "Stoichiometry is the arithmetic of chemistry: it answers 'how much reactant is needed' and 'how much product forms' from balanced equations.",
    "The mole is the counting unit of chemistry: 1 mole = 6.022 × 10²³ particles, and 1 mole of any substance weighs its molar mass in grams.",
    "Core formulas: n = m/M (moles from mass), m = n × M (mass from moles), and number of particles = n × 6.022 × 10²³.",
    "Worked example 1: moles in 88 g of CO₂: M(CO₂) = 12 + 32 = 44 g/mol, so n = 88/44 = 2 mol, containing 2 × 6.022 × 10²³ molecules.",
    "Worked example 2 (mass–mass): what mass of CO₂ forms when 12 g of carbon burns completely? C + O₂ → CO₂; n(C) = 12/12 = 1 mol → n(CO₂) = 1 mol → m(CO₂) = 1 × 44 = 44 g.",
    "The limiting reactant is the one fully consumed first; it fixes the maximum product possible, like the shortest plank deciding the bucket's capacity.",
    "Percentage composition: %H in H₂O = (2/18) × 100 ≈ 11.1%, %O ≈ 88.9%.",
    "Avogadro's law underlies molar volume: at STP, 1 mole of any gas occupies 22.4 dm³.",
    "Stoichiometry is applied in industry (yield of fertilizers, fuels) and in labs (preparing solutions of exact concentration).",
  ],
},
"chemistry::Acids & Bases": {
  definition: "Acids are proton (H⁺) donors and bases are proton acceptors; the pH scale from 0 to 14 measures how acidic or basic a solution is.",
  short: [
    "Arrhenius definition: acids release H⁺ in water, bases release OH⁻. Brønsted-Lowry: acids donate protons, bases accept them.",
    "Acids taste sour (lemon), turn blue litmus red and have pH < 7; bases taste bitter (soap), turn red litmus blue and have pH > 7.",
    "Strong acids (HCl) and strong bases (NaOH) ionize completely in water; weak ones like CH₃COOH ionize partially.",
    "Neutralization: acid + base → salt + water, e.g. HCl + NaOH → NaCl + H₂O.",
    "pH examples: lemon juice ≈ 2, pure water = 7, baking soda solution ≈ 9.",
  ],
  long: [
    "Acids and bases are two opposite classes of electrolytes recognized by their reactions with indicators and each other.",
    "Definitions grew over time: Arrhenius (H⁺/OH⁻ in water), Brønsted-Lowry (proton donor/acceptor — works in any solvent), and Lewis (electron-pair acceptor/donor).",
    "Physical and chemical properties: acids conduct electricity, react with metals (Zn + 2HCl → ZnCl₂ + H₂), with carbonates (CO₂ fizzes off) and with bases; bases feel soapy, react with acids and ammonium salts.",
    "Strength vs concentration: strength is the degree of ionization (HCl strong, CH₃COOH weak); concentration is the amount of solute per volume — a dilute strong acid is still strong.",
    "pH = −log[H⁺]: each pH unit is a tenfold change in acidity. pH < 7 acidic, = 7 neutral, > 7 basic.",
    "Neutralization has everyday applications: antacids (Mg(OH)₂) cure excess stomach HCl; lime neutralizes acidic soil; toothpaste counters mouth acids.",
    "Salts from neutralization: normal salts (NaCl), acidic salts (NaHSO₄, when the acid is polybasic and partially neutralized) and basic salts.",
    "Indicators: litmus (red in acid, blue in base), methyl orange (red/yellow), phenolphthalein (colourless/pink) — used to find the end point in titrations.",
    "Acid rain (pH < 5.6) corrodes buildings and kills aquatic life, showing why controlling industrial SO₂ and NOₓ emissions matters.",
  ],
},
"chemistry::Periodic Table Trends": {
  definition: "The modern periodic table arranges elements by increasing atomic number so that elements in the same group share the same number of valence electrons and similar properties.",
  short: [
    "Modern periodic law (Moseley): the properties of elements are a periodic function of their atomic numbers.",
    "Periods are horizontal rows (7 of them) — properties change gradually from metals on the left to non-metals on the right.",
    "Groups are vertical columns (18 of them) — members share valence-electron count and similar chemistry.",
    "Atomic size decreases across a period (higher nuclear charge pulls electrons in) and increases down a group (extra shells are added).",
    "Electronegativity and ionization energy increase across a period and decrease down a group.",
  ],
  long: [
    "The periodic table is chemistry's map: 118 elements arranged by increasing atomic number so that similar properties recur at regular (periodic) intervals.",
    "Earlier attempts — Dobereiner's triads and Newlands' octaves — were replaced by Mendeleev's mass-based table and finally by Moseley's atomic-number law.",
    "Groups (vertical): group 1 alkali metals (Li…Cs, one valence electron, highly reactive), group 2 alkaline-earth, group 17 halogens (F, Cl, Br, I — seven valence electrons), group 18 noble gases (full shells, inert).",
    "Periods (horizontal): reading left to right, metallic character falls and non-metallic character rises; each period fills one more shell.",
    "Trend — atomic size: across a period it decreases (e.g. Na > Mg > Al) because nuclear charge rises while shells stay the same; down a group it increases (Li < Na < K) because new shells start.",
    "Trend — ionization energy and electronegativity: both increase across a period and decrease down a group, mirroring how tightly outer electrons are held.",
    "Metallic character therefore decreases across a period and increases down a group; the zig-zag metalloid line separates metals from non-metals.",
    "Blocks s, p, d and f describe which orbital receives the last electron and link position to electronic configuration.",
    "Applications: an element's position predicts its valency, formula of its compounds and even its oxide's acid/base nature.",
  ],
},

/* ─────────────────────────── BIOLOGY ─────────────────────────── */
"biology::Cell Structure": {
  definition: "The cell is the basic structural and functional unit of all living things, containing organelles that perform specialized jobs.",
  short: [
    "Cell theory: all living things are made of cells, the cell is the unit of structure and function, and new cells arise only from pre-existing cells.",
    "The cell membrane controls what enters and leaves; the nucleus contains chromosomes (DNA) and directs all cell activities.",
    "Mitochondria release energy by respiration (the powerhouse); ribosomes synthesize proteins; chloroplasts (plants only) carry out photosynthesis.",
    "Plant cells additionally have a cellulose cell wall, a large central vacuole and chloroplasts — animal cells lack these.",
    "Prokaryotes (bacteria) have no true nucleus; eukaryotes (plants, animals, fungi, protists) have a membrane-bound nucleus.",
  ],
  long: [
    "The cell is the smallest unit of life; Robert Hooke first saw cork 'cells', and Schleiden, Schwann and Virchow later framed the cell theory.",
    "Every cell has three essentials: a cell membrane enclosing cytoplasm, genetic material, and ribosomes for making proteins.",
    "Nucleus: the control room storing DNA on chromosomes, with the nucleolus making ribosomes. The nuclear membrane pores let messages out.",
    "Endoplasmic reticulum (rough with ribosomes — protein transport; smooth — lipid making) and Golgi bodies (packaging and secretion) work as the cell's delivery system.",
    "Mitochondria: site of aerobic respiration, releasing energy as ATP. Chloroplasts (containing chlorophyll) capture light for photosynthesis — both contain their own DNA.",
    "Lysosomes are the recycling centres full of digestive enzymes; vacuoles store water, salts and waste (the large plant vacuole gives support).",
    "Plant-only structures: cellulose cell wall for strength and shape, plus chloroplasts — which is why animal cells neither photosynthesize nor stand rigid.",
    "Levels of organization: cells → tissues → organs → organ systems → organism; e.g. muscle cells → muscle tissue → heart → circulatory system.",
    "Specialization example: a root hair cell has an extended membrane for absorbing water; a red blood cell loses its nucleus to carry more haemoglobin.",
  ],
},
"biology::Biological Molecules": {
  definition: "Biological molecules are the organic compounds of life — carbohydrates, proteins, lipids and nucleic acids — each built from smaller repeating units.",
  short: [
    "Carbohydrates (C, H, O only) are the main energy source: sugars like glucose give quick energy, and starch stores it in plants.",
    "Proteins are chains of amino acids used for growth and repair; enzymes, antibodies and many hormones are proteins.",
    "Lipids (fats and oils) provide roughly twice the energy of carbohydrates and form cell membranes.",
    "Nucleic acids DNA and RNA store and transfer hereditary information; their monomer is the nucleotide.",
    "Water makes up 70–90% of cells and acts as the universal solvent in which life's reactions occur.",
  ],
  long: [
    "Life is chemically organized into four great classes of biological molecules, all built around carbon skeletons with C, H and O (plus N in proteins and nucleic acids).",
    "Carbohydrates: monosaccharides (glucose, fructose), disaccharides (sucrose = glucose + fructose) and polysaccharides (starch — plant storage; glycogen — animal storage; cellulose — plant walls).",
    "Proteins: 20 kinds of amino acids join by peptide bonds into polypeptides, which fold into working shapes; functions include structure (keratin), transport (haemoglobin), defence (antibodies) and catalysis (enzymes).",
    "Lipids: triglycerides (fats and oils = glycerol + 3 fatty acids) store energy and insulate; phospholipids build membranes; steroids include cholesterol.",
    "Nucleic acids: DNA (double helix) stores genetic information; RNA copies it for protein synthesis; a nucleotide = sugar + phosphate + nitrogen base.",
    "Condensation joins monomers by removing water; hydrolysis splits them by adding water back — these two reactions run all metabolism.",
    "Food tests: iodine turns blue-black with starch, Benedict's reagent turns brick-red with reducing sugar, the biuret test turns violet with protein, and the emulsion test detects fats.",
    "Water's roles: solvent, reactant in photosynthesis and hydrolysis, and temperature regulator because of its high specific heat.",
    "Deficiency links the molecules to health: too little protein causes stunted growth; excess carbohydrates are stored as fat.",
  ],
},
"biology::Enzymes": {
  definition: "Enzymes are biological catalysts, mostly proteins, that speed up the chemical reactions of life without being consumed.",
  short: [
    "Enzymes are globular protein catalysts: they accelerate biochemical reactions but remain unchanged at the end.",
    "Each enzyme is substrate-specific — the lock-and-key model describes a substrate fitting exactly into the enzyme's active site.",
    "Activity depends on temperature (human enzymes work best near 37 °C) and pH (pepsin ≈ pH 2; most others near 7).",
    "Denaturation: strong heat or extreme pH permanently changes the enzyme's shape and destroys activity.",
    "Example: salivary amylase digests starch into maltose in the mouth.",
  ],
  long: [
    "Enzymes are the cell's catalysts — they lower the activation energy of reactions so life's chemistry runs at body temperature.",
    "Lock-and-key mechanism: the substrate (key) fits the active site (lock), forms an enzyme–substrate complex, products leave, and the enzyme is reused.",
    "Thousands of turnovers per minute make tiny enzyme amounts hugely effective — one catalase molecule can break down millions of H₂O₂ molecules.",
    "Factors — temperature: rate roughly doubles per 10 °C rise until the optimum (≈ 37 °C in humans); beyond it the protein denatures and the rate collapses.",
    "Factors — pH: each enzyme has an optimum (pepsin in the stomach ≈ 2; salivary amylase ≈ 6.8). Wrong pH distorts ionic bonds and denatures the enzyme.",
    "Factors — substrate/enzyme concentration: at fixed enzyme level, rate rises with substrate until all active sites are saturated.",
    "Examples in digestion: amylase (starch→maltose, mouth), pepsin (protein→peptides, stomach), trypsin and lipase (small intestine).",
    "Inhibition: competitive inhibitors block the active site; the poison cyanide disables cytochrome oxidase in respiration.",
    "Commercial uses: biological detergents (proteases and lipases), cheese-making (rennin), and medicine — all rely on enzyme specificity.",
  ],
},
"biology::Human Digestion": {
  definition: "Human digestion is the physical and chemical breakdown of food into soluble molecules by enzymes along the alimentary canal, followed by absorption into the blood.",
  short: [
    "Digestion breaks food physically (churning, grinding) and chemically (enzymes) into small soluble molecules the blood can absorb.",
    "Route of food: mouth → oesophagus → stomach → small intestine (duodenum + ileum) → large intestine → rectum.",
    "Mouth: salivary amylase digests starch. Stomach: HCl and pepsin digest protein. Small intestine: bile emulsifies fat; pancreatic enzymes complete digestion.",
    "Absorption of digested food happens through villi in the ileum; the large intestine mainly absorbs water.",
    "End products: starch → glucose, protein → amino acids, fats → fatty acids and glycerol.",
  ],
  long: [
    "Digestion converts insoluble food into soluble molecules small enough to pass into the blood — a paired process of mechanical breakdown and enzymatic hydrolysis.",
    "Mouth: teeth grind food while salivary amylase turns starch into maltose; the tongue rolls the bolus for swallowing.",
    "Peristalsis — waves of muscle contraction — pushes food down the oesophagus into the stomach.",
    "Stomach: muscular churning mixes food with gastric juice (HCl + pepsin). Acid kills germs and gives pepsin its pH 2 optimum; pepsin turns protein into peptides.",
    "Duodenum: bile from the liver (stored in the gall bladder) emulsifies fats into droplets; pancreatic juice supplies amylase, trypsin and lipase.",
    "Ileum: intestinal juice completes digestion. Villi — finger-like projections with a lacteal and dense blood capillaries — absorb glucose, amino acids and fatty acids; the lacteals take fats.",
    "Villi adaptations: enormous surface area, thin walls, rich blood supply and constant movement — all speed absorption.",
    "Large intestine absorbs remaining water and salts; undigested residue is compacted and egested through the rectum (defaecation) — egestion is NOT excretion.",
    "Health link: a balanced diet with fibre keeps peristalsis efficient, preventing constipation, while the villi surface damaged by infection causes malabsorption and diarrhoea.",
  ],
},
"biology::Reproduction": {
  definition: "Reproduction is the biological process by which new individuals of a species are produced — asexually from one parent or sexually by the fusion of two gametes.",
  short: [
    "Asexual reproduction involves one parent and yields genetically identical offspring — binary fission (amoeba), budding (yeast, hydra), spore formation (rhizopus) and vegetative propagation (potato tubers).",
    "Sexual reproduction fuses two gametes; the zygote grows into a genetically varied new individual.",
    "In flowers: the stamen (anther + filament) produces pollen (male gametes); the carpel (stigma + style + ovary) holds ovules (female gametes).",
    "In humans: sperm form in the testes, eggs in the ovaries, and fertilization occurs in the fallopian tube.",
    "Pollination is the transfer of pollen to a stigma; fertilization is the actual fusion of gametes — the two must not be confused.",
  ],
  long: [
    "Reproduction ensures species survival. The two modes trade speed for variety: asexual reproduction is fast and needs no mate; sexual reproduction introduces variation that helps species adapt.",
    "Asexual types: binary fission (amoeba, bacteria), budding (yeast, hydra), spore formation (bread mould Rhizopus) and vegetative propagation (potato tubers, strawberry runners, onion bulbs).",
    "Flower structure: male stamen = anther (pollen) + filament; female carpel = stigma (catches pollen) + style + ovary (contains ovules).",
    "Pollination (self or cross, often by insects or wind) is followed by germination of the pollen tube; the male nucleus fuses with the ovule nucleus — fertilization.",
    "After fertilization: the ovule becomes the seed, the ovary becomes the fruit; seeds disperse by wind, water or animals and germinate when conditions are right.",
    "Human reproduction: testes make sperm and testosterone; ovaries release one egg per cycle; fertilization in the fallopian tube forms a zygote that implants in the uterus and develops into an embryo nourished by the placenta.",
    "The placenta exchanges nutrients, oxygen and wastes between mother and fetus; the amniotic fluid protects the embryo.",
    "Comparison: asexual offspring are clones (stable environments) while sexual offspring vary (changing environments and disease resistance).",
    "Applications: vegetative propagation is used by gardeners and tissue-culture labs to mass-produce identical quality plants.",
  ],
},
"biology::Ecosystem & Environment": {
  definition: "An ecosystem is a community of organisms interacting with one another and with their physical environment, with energy flowing from producers to consumers.",
  short: [
    "An ecosystem = the biotic community (producers, consumers, decomposers) plus the abiotic factors (light, water, temperature, soil).",
    "Producers (green plants) trap sunlight by photosynthesis; consumers eat them (herbivores → carnivores); decomposers (bacteria, fungi) recycle nutrients.",
    "A food chain shows who eats whom: grass → grasshopper → frog → snake → hawk; interlinked chains form a food web.",
    "Only about 10% of energy passes to the next trophic level, so pyramids of numbers and biomass narrow upward.",
    "Carbon cycle: photosynthesis removes CO₂; respiration and combustion return it — excess CO₂ from human activity drives global warming.",
  ],
  long: [
    "Ecology studies relationships between organisms and their environment at levels: population → community → ecosystem → biosphere.",
    "Biotic components: producers (autotrophs), consumers (primary/herbivores, secondary and tertiary carnivores, omnivores) and decomposers (saprophytes).",
    "Abiotic components: light, temperature, water, soil and air — these decide which organisms can live in a habitat.",
    "Food chain example: grass → grasshopper → frog → snake → hawk. Because most organisms eat several foods, chains interconnect into food webs; removing one species ripples through the web.",
    "Energy flow: the sun is the ultimate source; producers convert about 1% into food, each consumer passes on roughly one-tenth, so top carnivores are few — this explains pyramid shapes.",
    "Carbon cycle: photosynthesis fixes CO₂ into organic matter; respiration, decay and fuel burning release it; oceans and forests are major reservoirs.",
    "Nitrogen cycle: nitrogen fixation (bacteria/lightning) → nitrification → uptake by plants → animals → death → ammonification → denitrification returns N₂ to the air.",
    "Human impacts: deforestation, over-hunting, pollution and climate change cause habitat loss and extinction; conservation (protected areas, replanting, recycling, pollution control) limits damage.",
    "Symbiosis close to the ecosystem idea: mutualism (bee and flower), commensalism (remora and shark) and parasitism (tapeworm) describe species living together.",
  ],
},

/* ─────────────────────────── ENGLISH ─────────────────────────── */
"english::Grammar Foundations": {
  definition: "Grammar is the structural rule system of a language — parts of speech, tenses and agreement rules — that makes sentences correct and clear.",
  short: [
    "Grammar is the rule system of English: parts of speech, tenses, and the rules by which words combine into correct sentences.",
    "The eight parts of speech are noun, pronoun, verb, adverb, adjective, preposition, conjunction and interjection.",
    "Subject–verb agreement: a singular subject takes a singular verb — 'He writes', not 'He write'.",
    "Tenses show time — past, present and future, each with simple, continuous and perfect forms.",
    "Example correction: 'She go to school' becomes 'She goes to school' (agreement), and 'He done it' becomes 'He did it' (past simple).",
  ],
  long: [
    "Grammar is the machinery that turns vocabulary into meaning: knowing the classes of words and the rules for arranging them.",
    "Parts of speech with examples: noun (Lahore), pronoun (she), verb (runs), adjective (bright), adverb (quickly), preposition (under), conjunction (although), interjection (wow!).",
    "Sentence structure: every complete sentence needs a subject and a predicate; English normally follows Subject–Verb–Object order — 'The cat (S) chased (V) the mouse (O)'.",
    "Tense system: past, present, future × simple, continuous, perfect, perfect continuous — e.g. 'I wrote', 'I write', 'I will have written'.",
    "Agreement and consistency: 'The list of items is long' (subject is 'list'); keep tense consistent within a passage unless time genuinely shifts.",
    "Punctuation supports grammar: the comma separates clauses, the apostrophe shows possession (the boy's book) or contraction (it's = it is — distinct from its).",
    "Common confusions: their/there/they're, its/it's, then/than, affect (verb)/effect (usually noun).",
    "Worked correction: 'Me and him goes to market yesterday' → 'He and I went to the market yesterday' (case, agreement, tense, article).",
    "Improvement method: read good prose daily, rewrite your own sentences, and verify doubtful rules in a grammar reference.",
  ],
},
"english::Comprehension": {
  definition: "Comprehension is reading a passage carefully and answering questions that test literal, inferential and vocabulary understanding of exactly what the passage says.",
  short: [
    "Comprehension means reading a given passage closely and answering questions based only on what the passage states or implies.",
    "Method: skim once for the general idea, read again slowly, underline key points, then answer in your own words.",
    "Literal questions ask for stated facts; inferential questions ask you to read between the lines; vocabulary questions ask for meanings in context.",
    "For vocabulary items, use context clues from the surrounding sentences before guessing.",
    "Answer in complete sentences, keep to the point, and always look back at the passage — marks are lost for irrelevant detail.",
  ],
  long: [
    "Comprehension tests whether a reader can extract both surface information and hidden meaning from a passage — the skill behind every exam reading question.",
    "Step 1 — Skim (1 minute): note the title, opening and closing lines to grasp the theme.",
    "Step 2 — Read actively: underline topic sentences, names, dates and contrast words (however, although) that questions usually target.",
    "Step 3 — Read the questions first if allowed; knowing what is asked makes the second reading purposeful.",
    "Question types: factual (locate the line), inferential (combine two clues — 'the writer's attitude is…'), vocabulary (meaning in context) and title-selection (the choice that covers the whole passage, not one paragraph).",
    "Answering technique: respond in complete sentences using your own words, quote sparingly, and match the tense of the question.",
    "Vocabulary clue example: in 'The arid desert had seen no rain for years', the context defines arid as extremely dry.",
    "Inference example: if a character 'slammed the door and said nothing', you may infer anger even though the word angry never appears.",
    "Time discipline: allot a fixed time per question, attempt the direct ones first, and never leave a comprehension blank — partial credit is real.",
  ],
},
"english::Essay Writing": {
  definition: "An essay is an organized composition on a single topic, built from an introduction, developing body paragraphs and a conclusion.",
  short: [
    "An essay develops one topic through three parts: introduction, body and conclusion.",
    "The introduction states the thesis; each body paragraph covers one point with an example; the conclusion summarizes and gives a final thought.",
    "Before writing, spend five minutes listing 4–6 points — this outline is the essay's skeleton.",
    "Use linkers (however, moreover, in conclusion) so ideas flow smoothly between paragraphs.",
    "A good essay is simple, accurate and relevant; match the length to the word limit printed on the paper.",
  ],
  long: [
    "An essay is a structured piece of prose that argues, describes or narrates a single theme — organization matters as much as ideas.",
    "Types: narrative (tells a story), descriptive (paints a picture), expository (explains) and argumentative (takes a side with evidence).",
    "Planning: jot the thesis and 4–6 supporting points in the margin; number them in the best order before writing the first sentence.",
    "Introduction (3–4 sentences): hook (quotation, fact or question), background, and a clear thesis — for 'Discipline in Student Life': 'Discipline is the invisible timetable behind every success.'",
    "Body paragraphs: one point each, following PEEL — Point, Evidence/Example, Explanation, Link to the next idea.",
    "Conclusion: restate the thesis freshly, summarize the main stance and end with a memorable line — never introduce brand-new arguments here.",
    "Language: prefer active voice, concrete nouns and short sentences; vary sentence openings to avoid monotony.",
    "Revision checklist (5 minutes): tense consistency, spelling, paragraphing, word count and neat crossing-out of errors.",
    "Common faults: drifting off-topic, one giant paragraph, memorized chunks that do not fit the question, and ignoring the word limit.",
  ],
},
"english::Précis Writing": {
  definition: "A précis is a faithful condensation of a passage to about one-third of its length, written in the candidate's own words.",
  short: [
    "A précis condenses a passage to roughly one-third of its length while keeping every essential idea.",
    "Write it in your own words, in the third person and in indirect speech — no examples, quotations or personal opinion.",
    "Method: read twice, note the central theme and supporting points, draft, then trim to the word limit.",
    "Give the précis a short title that captures the theme.",
    "Model compression: 'Honesty is the best policy because truthfulness earns lasting trust' → 'Truthfulness builds trust.'",
  ],
  long: [
    "Précis (French: 'cut short') is the art of shrinking a passage without losing its meaning — completeness in one-third of the space.",
    "Step 1 — Read the passage twice: first for the general sense, then with a pencil marking the topic sentence of each paragraph.",
    "Step 2 — Identify what to drop: illustrations, repetitions, quotations, rhetorical questions and decorative adjectives.",
    "Step 3 — Draft in indirect speech and third person: convert 'I have always found...' to 'The writer has always found...'.",
    "Step 4 — Count and trim: the final version should be about one-third of the original; keep the logical order of the original.",
    "Step 5 — Title: a short phrase naming the core idea (a passage on the value of trees → 'Trees: Our Silent Friends').",
    "Qualities of a good précis: clarity, coherence, completeness and single consistent tense; it must be able to stand alone.",
    "Worked example: original of 96 words describing three reasons cities are growing becomes 30 words naming the three reasons in one sentence each.",
    "Common errors: copying whole sentences (defeats the purpose), adding opinions, exceeding the limit and missing one of the main ideas.",
  ],
},
"english::Letter & Application Writing": {
  definition: "Formal letters and applications follow a fixed format — sender's address and date, recipient's designation, salutation, subject line, body and courteous closing.",
  short: [
    "A formal letter's parts: sender's address and date (top right), recipient's designation and address (left), salutation (Sir/Madam), subject line, body and closing ('Yours faithfully').",
    "The body states the purpose in the first paragraph, gives details in the middle, and closes politely in the last.",
    "An application (for leave, fee concession, a job) uses the same format but is addressed 'To, The Headmaster/Principal' and often opens with 'Respected Sir'.",
    "Keep the tone courteous and the language simple; avoid slang, contractions and emotion.",
    "Example subject line: 'Subject: Application for four days' leave on medical grounds.'",
  ],
  long: [
    "Letters and applications are formal communications judged as much on format as on content — examiners award marks for each correctly placed part.",
    "Layout of a formal letter: (1) sender's address and date, top right; (2) recipient's designation and address, left; (3) salutation 'Dear Sir/Madam'; (4) subject line in brief; (5) body paragraphs; (6) complimentary close 'Yours faithfully' with signature and name.",
    "Body structure: paragraph 1 — who you are and why you are writing; paragraph 2 — details/facts supporting the request; paragraph 3 — the specific action you seek and thanks.",
    "Sample leave application: 'To, The Principal, City School, Lahore. Subject: Request for leave on medical grounds. Respected Sir, I am a student of Class 10-B. I have been suffering from fever since Monday and the doctor has advised three days' rest. I therefore request leave from 5 to 7 March. I shall be grateful for your kind permission. Yours obediently, Ali Ahmad, Class 10-B, Roll No. 12.'",
    "Differences: a letter may go to a newspaper editor, a company or a friend (informal, different format); an application specifically requests something from an authority.",
    "Style rules: one topic per letter, facts before feelings, present facts with dates and numbers, and request — never demand.",
    "Common faults: missing date or address, mixing formal and friendly tone, two subjects in one letter, and forgetting the subject line.",
    "Practice plan: write one formal letter and one application weekly on rotating topics (fee concession, character certificate, complaint about water supply).",
  ],
},
"english::Vocabulary Building": {
  definition: "Vocabulary building is the deliberate expansion of word knowledge — meaning, spelling and usage — through roots, affixes, context and regular reading.",
  short: [
    "A strong vocabulary grows from three habits: wide reading, word analysis and active use.",
    "Word analysis uses roots and affixes: 'bio' (life) + 'graphy' (writing) = biography, the story of a life; 'pre' + 'view' = a viewing before.",
    "Context clues: in 'The arid desert had no rain for years', the context shows arid means very dry.",
    "Learn words in families (act, action, active, actively) and in collocations — 'heavy rain', not 'strong rain'.",
    "Keep a personal word notebook; revise it weekly and use every new word in a sentence.",
  ],
  long: [
    "Vocabulary is the toolbox of expression: the more words a learner commands, the more precisely they can read, write and speak.",
    "Roots unlock families of words: 'port' (carry) gives transport, import, export, portable; 'spect' (look) gives inspect, spectator, respect.",
    "Prefixes and suffixes bend meaning: un-/dis-/in- negate (unfair, disorder); -ful/-less show presence or absence (careful, careless); -tion/-ment make nouns (action, movement).",
    "Context strategy — instead of halting at an unknown word, read the whole sentence and predict: 'The knife was blunt and would not cut' → blunt = not sharp.",
    "Synonyms refine shade: big, large, huge, enormous grow in intensity; antonyms sharpen meaning by contrast.",
    "Collocations and register: 'do homework' but 'make mistakes'; formal 'purchase' vs everyday 'buy'.",
    "Active use beats passive lists: write a paragraph using five new words, and say them aloud — words used are words kept.",
    "Exam technique: for synonym/antonym items, think of the word in a sentence first, then match options; eliminate obviously wrong pairs.",
    "Sustained method: 15 minutes of daily reading (editorials, stories) plus a weekly self-quiz yields roughly 20 durable new words a month.",
  ],
},

/* ─────────────────────────── COMPUTER SCIENCE ─────────────────────────── */
"computer::Computer Fundamentals": {
  definition: "A computer is an electronic device that accepts input, processes data, stores results and produces output, following the input–process–output cycle.",
  short: [
    "A computer is an electronic machine that takes input, processes data, stores results and gives output — the IPOS cycle.",
    "Hardware is the physical equipment (CPU, RAM, keyboard); software is the set of instructions (system software like Windows, application software like MS Word).",
    "The CPU is the brain: the ALU does arithmetic and logic, the Control Unit directs operations, and registers hold data temporarily.",
    "Input devices: keyboard, mouse, scanner. Output devices: monitor, printer, speakers.",
    "By size, computers are micro (PC), mini, mainframe and supercomputer.",
  ],
  long: [
    "A computer is a programmable electronic device that accepts data, processes it according to stored instructions, and produces information — speed, accuracy and storage are its hallmarks.",
    "The IPO(S) cycle describes every task: Input (pressing a key) → Processing (CPU decodes and executes) → Output (the character appears) → Storage (the document is saved).",
    "Hardware units: input, output, CPU (ALU + Control Unit + registers), and memory (RAM — volatile working memory; ROM — permanent start-up instructions; hard disks and SSDs — mass storage).",
    "Software families: system software (operating systems, drivers, utilities) manages the machine; application software (Word, browsers, games) serves the user.",
    "Units of data: 8 bits = 1 byte; 1024 bytes = 1 KB, then MB, GB, TB.",
    "Computer generations: vacuum tubes → transistors → integrated circuits → microprocessors → today's AI and portable devices.",
    "Classification: by size (micro, mini, mainframe, super), by purpose (general vs special-purpose like ATMs), and by signal (digital vs analog).",
    "Characteristics: speed (billions of operations/second), diligence (never tires), accuracy (errors come from wrong input — GIGO: garbage in, garbage out) and versatility.",
    "Everyday example: an ATM reads the card (input), verifies the PIN (processing), dispenses cash (output) and updates the account (storage).",
  ],
},
"computer::Programming Basics": {
  definition: "Programming is writing step-by-step instructions in a language the computer can execute; programs manipulate data through variables, decisions and loops.",
  short: [
    "A program is a sequence of instructions that tells the computer exactly what to do; programming languages such as C and Python make these instructions writable and readable.",
    "Variables are named memory locations that store data; every value has a data type — integer, float, character, Boolean or string.",
    "Selection (if/else) lets a program choose between paths; loops (for, while) repeat steps.",
    "Example pseudocode: IF marks >= 50 THEN grade = 'Pass' ELSE grade = 'Fail'.",
    "Good programs are correct, clear and tested against sample inputs.",
  ],
  long: [
    "Programming turns an algorithm into instructions a machine executes; the quality of the thinking shows up directly in the quality of the code.",
    "Language levels: machine language (raw binary), assembly (mnemonics like ADD), high-level (C, Python — human-readable, translated by compilers or interpreters).",
    "Variables and types: a variable is a named box in memory; declaring x = 5 (integer) vs price = 99.5 (float) vs grade = 'A' (character) fixes what operations are legal.",
    "Operators: arithmetic (+ − × ÷ %), relational (=, ≠, <, >) and logical (AND, OR, NOT) — combined in conditions like (marks >= 40) AND (marks < 50).",
    "Control structures: sequence (default), selection (if / if-else / switch) and iteration (for a counted number of times, while a condition holds).",
    "Worked example — average of three marks: 1) Start; 2) Input a, b, c; 3) total = a + b + c; 4) avg = total / 3; 5) Print avg; 6) Stop.",
    "Worked example — grade decision: IF avg >= 80 THEN print 'A+' ELSE IF avg >= 70 THEN print 'A' ELSE print 'B'.",
    "Errors: syntax errors break the grammar rules (caught by the compiler), logic errors run but produce wrong answers (found by testing), and runtime errors like division by zero crash the run.",
    "Development habit: code a little, test a little — trace every program by hand with sample values before running it.",
  ],
},
"computer::Flowcharts & Algorithms": {
  definition: "An algorithm is a finite, ordered set of unambiguous steps for solving a problem; a flowchart is its diagram drawn with standard symbols.",
  short: [
    "An algorithm is a finite, ordered list of clear, unambiguous steps that solves a problem — like a recipe.",
    "A flowchart draws the algorithm using standard symbols: oval = start/stop, parallelogram = input/output, rectangle = process, diamond = decision, arrows = flow.",
    "An algorithm must have defined inputs, precise steps, finiteness (it must end) and effectiveness.",
    "Example algorithm — average of two numbers: 1) Start 2) Input A, B 3) Avg = (A + B)/2 4) Print Avg 5) Stop.",
    "Flowcharts help spot logic errors before coding begins.",
  ],
  long: [
    "Algorithms and flowcharts are the planning tools of programming: first think in steps, then draw the plan, and only then write code.",
    "Algorithm properties: input (zero or more), output (at least one), definiteness (each step exact), finiteness (ends after finitely many steps) and effectiveness (each step basic enough to perform).",
    "Flowchart symbols: oval for START/STOP, parallelogram for INPUT/PRINT, rectangle for calculations (process), diamond for decisions (yes/no), and small circle for connectors; arrows fix the direction of flow.",
    "Worked example — average of two numbers: Start → Input A, B → Avg = (A + B)/2 → Print Avg → Stop. Each step maps to one symbol.",
    "Worked example — largest of three numbers: Start → Input A, B, C → decision 'A > B?' — if yes go to 'A > C?' else 'B > C?'; the true branches print A or B, the false branch prints C → Stop. Two chained diamonds test all cases.",
    "Worked example — pass/fail: Start → Input marks → diamond 'marks >= 33?' → yes: print 'Pass' / no: print 'Fail' → Stop.",
    "Flowchart rules: flow top to bottom and left to right, only one symbol per step, label every decision branch (Yes/No) and never leave an open path.",
    "Algorithm vs flowchart: an algorithm is the textual plan, a flowchart is the same plan visualized — both precede the program.",
    "Benefit: tracing the flowchart with sample data (dry run) catches errors while they are still cheap to fix.",
  ],
},
"computer::Data Representation": {
  definition: "Data representation is how a computer encodes every kind of information — numbers, text, pictures and sound — as binary patterns of 0s and 1s.",
  short: [
    "Computers represent all data — numbers, text, images, sound — in binary (0s and 1s) because electronic circuits have two stable states.",
    "Units: 4 bits = 1 nibble, 8 bits = 1 byte; sizes scale KB (1024 B) → MB → GB → TB.",
    "Decimal to binary: divide by 2 and read the remainders upward — 13₁₀ = 1101₂.",
    "Binary to decimal: add the place values of the 1-bits — 1101₂ = 8 + 4 + 0 + 1 = 13.",
    "Text is stored with character codes such as ASCII: 'A' = 65 = 01000001₂.",
  ],
  long: [
    "Digital computers use the binary system because transistors switch reliably between two states — OFF = 0 and ON = 1; every kind of data must therefore be encoded in bits.",
    "Number systems: decimal (base 10, digits 0–9), binary (base 2), octal (base 8) and hexadecimal (base 16, digits 0–9 and A–F).",
    "Decimal → binary by repeated division: 25 ÷ 2 = 12 r1; 12 ÷ 2 = 6 r0; 6 ÷ 2 = 3 r0; 3 ÷ 2 = 1 r1; 1 ÷ 2 = 0 r1; reading remainders upward gives 11001₂.",
    "Binary → decimal by place value: 11001₂ = 16 + 8 + 0 + 0 + 1 = 25. (Each position right-to-left is worth 1, 2, 4, 8, 16…)",
    "Text: ASCII assigns each character a 7/8-bit code ('A' = 65, 'a' = 97, '0' = 48); Unicode extends this to cover Urdu, Arabic and Chinese characters.",
    "Images: a picture is a grid of pixels, each pixel a binary number for its colour; a 24-bit colour pixel stores three bytes (R, G, B).",
    "Sound: audio is sampled thousands of times per second, and each sample's amplitude is stored as a binary number.",
    "Storage units: 1 byte = 8 bits, 1 KB = 1024 bytes, 1 MB = 1024 KB, 1 GB = 1024 MB, 1 TB = 1024 GB.",
    "Why binary wins: two-state storage is noise-tolerant — a value is either clearly 0 or clearly 1, making digital data easy to copy without loss.",
  ],
},
"computer::Databases Intro": {
  definition: "A database is an organized collection of related data stored in tables so it can be searched and updated efficiently; a DBMS is the software that manages it.",
  short: [
    "A database is an organized collection of related data — e.g. a school's student records — stored in tables.",
    "A table consists of records (rows) and fields (columns); each field has a defined data type.",
    "A primary key is a field that uniquely identifies each record, such as RollNo.",
    "A DBMS (MySQL, Oracle, MS Access) lets users store, query, update and protect data; SQL is the standard query language.",
    "Example query: SELECT Name, Marks FROM Students WHERE Class = '10';",
  ],
  long: [
    "A database stores related data once, centrally and consistently, instead of scattering it across separate files.",
    "Structure: a table holds records (rows) and fields (columns). In a Students table, one row = one student; fields like RollNo (number), Name (text) and Marks (number) have fixed data types.",
    "Primary key: the field whose value is unique for every record — RollNo or CNIC. It prevents duplicate identities and links tables via foreign keys.",
    "A DBMS (Database Management System — MySQL, Oracle, SQL Server, Access) provides data definition, manipulation, querying, security and backup facilities.",
    "SQL essentials: SELECT (read), INSERT (add), UPDATE (change), DELETE (remove). Example: INSERT INTO Students VALUES (23, 'Ayesha', 87);",
    "Worked query: SELECT Name FROM Students WHERE Marks > 80 ORDER BY Marks DESC; — lists top students in descending order.",
    "Advantages over flat files: controlled redundancy, consistency, sharing by many users, security levels, backup/recovery and faster search through indexing.",
    "Relationships: one-to-many (one class, many students) built by storing the primary key of one table as a foreign key in another.",
    "Everyday examples: ATM transactions, school result cards, library catalogues and online shopping carts are all database applications.",
  ],
},
"computer::Networking Basics": {
  definition: "A computer network is a set of computers and devices connected to share data and resources; the internet is the largest network of networks.",
  short: [
    "A network connects computers so they can share files, printers and internet access.",
    "By coverage: LAN spans a building, MAN a city, and WAN spans countries — the internet is the largest WAN.",
    "By architecture: peer-to-peer (all computers equal) and client–server (a server provides services to clients).",
    "Every device on a network has an IP address (e.g. 192.168.1.5); DNS translates names like google.com into IP addresses.",
    "Protocols are communication rules: TCP/IP moves data, and HTTP/HTTPS delivers web pages.",
  ],
  long: [
    "A computer network is two or more computers linked so they can exchange data and share hardware (printers), software and internet connections.",
    "By geographical span: LAN (one office/building — fast, privately owned), MAN (a city) and WAN (countries and continents — the internet is the biggest WAN).",
    "By architecture: peer-to-peer networks treat every machine equally (small offices), while client–server networks centre on powerful servers (web server, mail server, file server) that serve many clients.",
    "Transmission media: wired — twisted pair, coaxial and fibre optic (fast, secure, expensive); wireless — radio (Wi-Fi), microwave and satellite.",
    "Network devices: NIC (connects a computer), switch (connects devices in a LAN), router (connects networks and chooses best paths) and modem (modulates signals for telephone/cable lines).",
    "Addressing: each device has an IP address (IPv4 like 192.168.1.5 or IPv6 like 2001:db8::1); DNS converts human-friendly names to IPs, exactly like a phone book.",
    "Protocols: TCP/IP (packet delivery), HTTP/HTTPS (web), SMTP/POP3 (email), FTP (file transfer) — agreed rules make different machines interoperable.",
    "Internet vs World Wide Web: the internet is the hardware network of networks; the web is a service of pages (HTML over HTTP) running on it — email is a different service on the same internet.",
    "Security basics: strong passwords, firewalls, antivirus updates and HTTPS (encrypted) protect data travelling across networks.",
  ],
},

/* ─────────────────────────── URDU ─────────────────────────── */
"urdu::نثر (Prose)": {
  definition: "نثر (prose) is ordinary written language arranged in sentences and paragraphs — essays, stories and novels — without the metre or rhyme of verse.",
  short: [
    "نثر وہ تحریر ہے جو جملوں اور پیراگرافوں میں، عام بول چال کے انداز میں لکھی جاتی ہے؛ اس میں وزن اور قافیے کی پابندی نہیں ہوتی۔",
    "نثری اصناف میں افسانہ، مضمون، ناول، ڈرامہ اور سوانح عمری شامل ہیں۔",
    "افسانہ مختصر مگر مکمل واقعہ پیش کرتا ہے جبکہ ناول زندگی کے وسیع پہلوؤں پر محیط طویل کہانی ہے۔",
    "اچھی نثر کی خوبیاں سادگی، وضاحت، تسلسل اور زورِ بیان ہیں — سر سید احمد خان، پطرس بخاری اور فرحت اللہ بیگ اردو نثر کے نمایاں لکھاری ہیں۔",
  ],
  long: [
    "نثر وہ تحریر ہے جو فطری بول چال کی طرح جملوں میں لکھی جاتی ہے اور اس میں شاعری کے وزن و قافیے کی پابندی نہیں ہوتی۔",
    "نثر کی نمایاں اصناف: افسانہ (مختصر کہانی)، مضمون (موضوع پر تحریر)، ناول (طویل کہانی)، ڈرامہ (منظر کے لیے لکھی گئی تحریر) اور سوانح عمری۔",
    "افسانہ ایک ہی کردار یا واقعے کے گرد گھومتا ہے اور مختصر ہوتا ہے؛ ناول میں کئی کردار اور کئی واقعے ہوتے ہیں۔",
    "مضمون دو قسم کا ہوتا ہے: ذاتی مضمون (ادبی و مزاحیہ انداز) اور موضوعاتی مضمون (معلومات اور استدلال پر مبنی)۔",
    "اچھی نثر کے اوصاف: سادہ و رواں زبان، وضاحت، تسلسل اور مؤثر جملے۔",
    "اردو نثر کے نمایاں لکھاریوں میں سر سید احمد خان، مولانا محمد حسین آزاد، پطرس بخاری اور فرحت اللہ بیگ شامل ہیں۔",
    "امتحان میں نثری اقتباس کا جائزہ لیتے وقت صنف، مرکزی خیال اور اسلوب کا ذکر ضروری ہے۔",
    "خلاصہ: علم و تحقیق، تاریخ، صحافت اور افسانوی ادب — ہر شعبے کا عام ذریعہ نثر ہی ہے۔",
  ],
},
"urdu::نظم (Poetry)": {
  definition: "نظم (poem) is verse written in lines with metre (وزن) and often rhyme, unified by a single subject and mood, unlike the multi-theme ghazal.",
  short: [
    "نظم شاعری کی وہ صنف ہے جس میں کلام مصرعوں میں، وزن اور قافیے کی رعایت کے ساتھ کہا جاتا ہے۔",
    "نظم کا موضوع اور جذبہ شروع سے آخر تک ایک ہی رہتا ہے؛ یہی اسے غزل سے ممیز کرتا ہے جس کے ہر شعر کا مزاج الگ ہو سکتا ہے۔",
    "شاعری کی معروف اصناف میں نظم، غزل، مرثیہ، قصیدہ، سلام اور مثنوی شامل ہیں۔",
    "نظم کے عناصر — وزن، قافیہ، ردیف اور بند — کلام کو موسیقیت اور معنوی وحدت عطا کرتے ہیں۔",
  ],
  long: [
    "نظم شاعری کی وہ صنف ہے جس میں ایک ہی موضوع اور جذبے کو مصرعوں کی ترتیب سے بیان کیا جاتا ہے اور اس میں وزن و قافیے کی پابندی ہوتی ہے۔",
    "نظم اور غزل کا بنیادی فرق: نظم ایک ہی موضوع پر ہوتی ہے جبکہ غزل کے ہر شعر کا موضوع الگ الگ ہو سکتا ہے۔",
    "شاعری کی معروف اصناف: نظم، غزل، مرثیہ (شہدائے کربلا کے ماتم کی نظم)، قصیدہ (تعریف یا قصہ گوئی)، سلام اور مثنوی۔",
    "نظم کے فنی عناصر: وزن (ارکانِ عروض کے اصول پر)، قافیہ، ردیف اور بندوں (اشعار کے گروہوں) کی ترتیب۔",
    "حسبِ موضوع نظم کی اقسام: حمدیہ، مدحیہ، طنزیہ، تعلیمی اور قومی نظم۔",
    "نمائندہ کلام: علامہ اقبال کی 'شکوہ' اور 'جوابِ شکوہ'، فیض احمد فیض اور احمد فراز کی نظمیں اردو کا قیمتی سرمایہ ہیں۔",
    "امتحان میں نظم کی تشریح کرتے وقت عنوان، مرکزی خیال، جذبہ اور فنی خصوصیات بیان کرنا ضروری ہے۔",
    "خلاصہ: نظم ایک ہی جذبے کو موسیقیت کے سانچے میں ڈھال کر مکمل اکائی کے طور پر پیش کرتی ہے۔",
  ],
},
"urdu::قواعد (Grammar)": {
  definition: "Urdu grammar (قواعد) is the rule system of the language: parts of speech (اسم، فعل، صفت، حرف), sentence structure, spelling and punctuation.",
  short: [
    "قواعد زبان کے وہ اصول ہیں جن کے ذریعے الفاظ، جملے، املا اور رموزِ اوقاف کی درستی قائم رہتی ہے۔",
    "الفاظ کی بنیادی اقسام: اسم (نام)، فعل (کام)، صفت (وصف)، ضمیر اور حرف۔",
    "جملے کے بنیادی اجزا فاعل، فعل اور مفعول ہیں: 'احمد نے خط لکھا' میں احمد فاعل، لکھا فعل اور خط مفعول ہے۔",
    "املا کی درستی اور رموزِ اوقاف (۔ ، ؟ !) جملے کا مطلب واضح کرتے ہیں۔",
  ],
  long: [
    "قواعد زبان کے وہ قاعدے ہیں جن سے کلام کی ساخت، املا اور رموزِ اوقاف کی درستی معلوم ہوتی ہے؛ یہی صحیح اور بامعنی جملہ سازی کی بنیاد ہے۔",
    "الفاظ کی اقسام: اسم (ذات یا جگہ کا نام)، فعل (کام کا وقوع)، صفت (اسم کی خصوصیت)، ضمیر (اسم کی جگہ) اور حرف (الفاظ کو ملانے والا)۔",
    "اسم کی دو بڑی قسمیں ہیں: اسمِ معرفہ (احمد، لاہور) اور اسمِ نکرہ (لڑکا، شہر)۔",
    "فعل کی تین صورتیں: ماضی (گزری ہوئی)، مضارع (جاری) اور امر (حکم)۔",
    "جملے کے اجزا: فاعل (کرنے والا)، فعل اور مفعول (جس پر عمل ہو) — مثلاً 'بچے نے سبق پڑھا' میں بچے فاعل، پڑھا فعل اور سبق مفعول ہے۔",
    "اردو جملے کی خوبی: فعل آخر میں آتا ہے، اسی تسلسل سے کلام رواں ہوتا ہے۔",
    "املا کی عام غلطیاں: ہمزہ کی جگہ (آنا، آیت) اور ایک جیسی آوازوں کے حروف (ض/ظ، ہ/ھ) کا التباس۔",
    "رموزِ اوقاف (وقفے کے نشانات) جملے کا مطلب اور جذبہ واضح کرتے ہیں؛ غلط وقفہ معنی بدل دیتا ہے۔",
    "مشق کا طریقہ: روزانہ تحریر لکھیں، اپنی غلطیاں نشان زد کریں اور قاعدے کی ایک مثال ساتھ یاد کریں۔",
  ],
},
"urdu::خط و درخواست (Letters)": {
  definition: "خط (letter) اور درخواست (application) رسمی تحریریں ہیں جن کا مقصد معلومات دینا یا کوئی اختیار سے کام کروانا ہے۔",
  short: [
    "خط اور درخواست باقاعدہ تحریریں ہیں جن میں ایک متعین ترتیب عمل میں لائی جاتی ہے۔",
    "خط کے حصے: دائیں طرف پتہ اور تاریخ، پھر خطاب ('محترم جناب')، مضمون کا خلاصہ، جسمِ خط اور آخر میں 'آپ کا تابعدار'۔",
    "درخواست عموماً پرنسپل یا صدرِ ادارے کے نام لکھی جاتی ہے اور اس کا اسلوب مکمل رسمی ہوتا ہے۔",
    "زبان مختصر، مؤدبانہ اور واضح ہو؛ ایک تحریر میں صرف ایک ہی معاملہ لکھیں۔",
  ],
  long: [
    "خط و درخواست رسمی تحریریں ہیں جن کا مقصد کسی ادارے یا فرد تک معلومات پہنچانا یا کوئی کام کروانا ہے۔",
    "خط کی ترتیب: 1) دائیں جانب اپنا پتہ اور تاریخ 2) مخاطب کا نام و پتہ 3) 'محترم جناب' 4) مضمون کا خلاصہ 5) جسمِ خط (ایک یا دو پیراگراف) 6) خاتمہ اور دستخط۔",
    "درخواست کی ترتیب: 'بہ خدمت پرنسپل صاحب'، ادارے کا نام، 'معروض ہے کہ…' سے آغاز، وجہ، درخواست کا خلاصہ اور تشکر۔",
    "چھٹی کی درخواست کی مثال: معروض ہے کہ میں آپ کے ادارے کا طالبِ علم ہوں؛ بیماری کی وجہ سے مجھے دو دن کی رخصت کی ضرورت ہے۔ مہربانی فرما کر رخصت عطا فرمائیں۔",
    "خط اور درخواست کا فرق: خط عام پیغام یا شکایت کے لیے لکھا جاتا ہے جبکہ درخواست اختیار سے کچھ مانگنے (رخصت، فیس کی معافی) کے لیے دی جاتی ہے۔",
    "زبان: مکمل رسمی اور مؤدبانہ؛ فاعل 'میں' کی تکرار سے گریز کریں۔",
    "املا اور رموزِ اوقاف کی پابندی کریں؛ ہر نئی بات نئی سطر سے شروع کریں۔",
    "عام غلطیاں: تاریخ یا پتہ بھول جانا، دوستانہ لہجہ اختیار کرنا اور غیر ضروری طوالت۔",
    "مشق: فارمیٹ یاد رکھیں اور مختلف موضوعات (فیس کی معافی، سندِ تعلیم، چھٹی) پر نمونے لکھ کر دیکھیں۔",
  ],
},
"urdu::مضمون نویسی (Essay Writing)": {
  definition: "مضمون نویسی کا مطلب ہے کسی ایک موضوع پر منظم تحریر ترتیب دینا جس کے حصے تعارف، تفصیلی بیان اور خاتمہ ہوتے ہیں۔",
  short: [
    "مضمون کسی ایک موضوع پر باقاعدہ تحریر ہے جس کے تین حصے ہوتے ہیں: تعارف، تفصیلی بیان اور خاتمہ۔",
    "تعارف میں موضوع کی اہمیت، جسم میں سرخیوں کے تحت نکات اور خاتمہ میں نتیجہ لکھا جاتا ہے۔",
    "ہر پیراگراف صرف ایک نکتہ پیش کرے؛ نکتوں کے درمیان منطقی تسلسل ہو۔",
    "سادہ زبان، درست املا اور مناسب اشعار یا حکایات مضمون کو مؤثر بناتے ہیں۔",
  ],
  long: [
    "مضمون نویسی کا مطلب ہے کسی موضوع پر منظم، مدلل اور رواں تحریر ترتیب دینا؛ یہ اردو کی اہم نثری صنف ہے۔",
    "مضمون کے تین حصے: تعارف (موضوع کی تعریف اور اہمیت)، جسمِ مضمون (سرخیوں کے تحت تفصیلی نکات) اور خاتمہ (خلاصہ اور نتیجہ)۔",
    "لکھنے سے پہلے خاکہ بنائیں: چار سے چھ سرخیاں منتخب کریں تاکہ مضمون متوازن رہے۔",
    "سرخیاں مختصر اور واضح ہوں؛ ہر سرخی کے تحت دو تین جملے لکھیں۔",
    "تعارف دلچسپ جملے، سوال یا شعر سے شروع کریں تاکہ قاری کی توجہ قائم ہو۔",
    "جسمِ مضمون میں مثالیں، حکایات اور شواہد دیں؛ استدلال کی ترتیب کمزور نکتے سے مضبوط نکتے کی طرف ہو۔",
    "خاتمہ میں کوئی نئی بات نہ لائیں؛ صرف خلاصہ اور اچھا لفظِ آخر۔",
    "عام غلطیاں: باتوں کا دہراؤ، دور دراز بیانات، املا کی خرابی اور سرخیوں کی عدم پابندی۔",
    "مشق کا طریقہ: ہفتے میں دو مضمون لکھیں اور استاد سے ان کی نشاندہی کروائیں۔",
  ],
},
"urdu::تلخیص (Summary)": {
  definition: "تلخیص کا مطلب ہے طویل عبارت کا تقریباً ایک تہائی حجم کا خلاصہ، اپنے الفاظ میں، صرف مرکزی خیالات کے ساتھ لکھنا۔",
  short: [
    "تلخیص کا مطلب ہے کسی طویل عبارت کو مختصر کر کے اس کے مرکزی خیالات برقرار رکھنا۔",
    "قاعدہ: تلخیص اپنے الفاظ میں، تیسری شخص میں اور براہِ راست کلام کے بغیر لکھی جاتی ہے۔",
    "مثالیں، تشبیہات اور غیر ضروری تفصیلات حذف کی جاتی ہیں۔",
    "عموماً تلخیص اصل عبارت کے تقریباً ایک تہائی حصے کے برابر ہوتی ہے؛ آخر میں مناسب عنوان دیا جاتا ہے۔",
  ],
  long: [
    "تلخیص عربی لفظ 'خُلاصہ' سے نکلی ہے؛ اس کا مطلب ہے طویل عبارت کے مرکزی خیالات کو مختصر الفاظ میں پیش کرنا۔",
    "پہلا قدم: عبارت دو تین بار پڑھیں اور ہر پیراگراف کا موضوعی جملہ (مرکزی خیال) نوٹ کریں۔",
    "دوسرا قدم: نکات کی فہرست بنائیں اور انہیں جوڑ کر ایک مسودہ لکھیں۔",
    "تیسرا قدم: اپنی رائے، نئی معلومات اور مثالیں شامل کیے بغیر مسودہ کو مطلوبہ حد تک چھوٹا کریں۔",
    "قاعدے: 1) اپنے الفاظ استعمال کریں 2) تیسری شخص میں لکھیں 3) براہِ راست گفتگو کو غیر مباش انداز میں بدلیں۔",
    "لمبے جملے چھوٹے کریں اور زائد صفتیں حذف کریں؛ اصل عبارت کی منطقی ترتیب قائم رکھیں۔",
    "لفظوں کی تعداد عموماً اصل کے ایک تہائی تک محدود رکھی جاتی ہے۔",
    "آخری شکل مرتب کر کے مختصر اور جامع عنوان لگائیں۔",
    "اچھی تلخیص کے اوصاف: جامعیت، وضاحت، اسلوب کی یکسانیت اور خیال کی مکملیت۔",
  ],
},
};
