/* ═══════════════════════════════════════════════════════════════════════════
   MENTORA AI — REAL STUDY NOTES BANK
   Structured study notes per subject and class level (Pakistani boards).
   Notes here take priority over the template generator in data.ts.
   Board content follows the shared national curriculum, so the same note set
   serves every board; the selected board tags the notes (see data.ts getNotes).
═══════════════════════════════════════════════════════════════════════════ */

export type SubjectId = "math" | "physics" | "chemistry" | "biology" | "english" | "computer" | "urdu";

export interface RealNote {
  topic: string;
  readMins: number;
  updated: string;
  points: string[];
}

/* ════════════════ MATHEMATICS ════════════════ */
const MATH_9: RealNote[] = [
  { topic: "Matrices & Determinants", readMins: 7, updated: "3 days ago", points: ["A matrix is a rectangular array of elements arranged in rows and columns; its order is rows × columns.", "Add or subtract matrices of the same order by combining corresponding entries.", "For A = [a b; c d], det(A) = ad − bc; det = 0 means A is singular and has no inverse.", "Multiply matrices only when the columns of A equal the rows of B; the product then has order (rows of A) × (columns of B).", "The identity matrix leaves any matrix unchanged: A·I = I·A = A.", "Exam tip: verify a matrix multiplication by recomputing one entry of the product by hand."] },
  { topic: "Real Numbers & Logarithms", readMins: 6, updated: "1 week ago", points: ["Rational numbers can be written as p/q; irrational ones such as √2 and π cannot.", "log_b(x) asks: b raised to what power gives x? For example log₁₀(100) = 2.", "Product law: log(mn) = log m + log n; quotient law: log(m/n) = log m − log n.", "Power law: log(mᵏ) = k·log m — it brings exponents to the front.", "Every common log splits into a characteristic (integer part) and a mantissa (decimal part).", "Logs turn multiplication into addition — the idea behind log tables and slide rules."] },
  { topic: "Algebraic Formulas & Factorization", readMins: 8, updated: "2 weeks ago", points: ["Workhorse identities: (a ± b)² = a² ± 2ab + b² and (a + b)(a − b) = a² − b².", "Cubes: a³ ± b³ = (a ± b)(a² ∓ ab + b²); memorize the (a ± b)³ expansions too.", "Factorize in order: common factor first, then grouping, then pattern recognition.", "A trinomial x² + bx + c factors as (x + p)(x + q) where p·q = c and p + q = b.", "HCF and LCM of algebraic expressions follow the same logic as for numbers.", "Always check a factorization by multiplying back out."] },
  { topic: "Linear Equations & Inequalities", readMins: 6, updated: "1 week ago", points: ["Collect variables on one side and constants on the other, then divide out the coefficient.", "Multiplying or dividing an inequality by a negative number reverses its direction.", "Elimination method: scale the equations so adding or subtracting removes one variable.", "Substitution method: express one variable in terms of the other, then substitute.", "For fractional equations, multiply through by the LCM of the denominators first.", "Substitute your solution back into the original equation — especially with fractions."] },
  { topic: "Coordinate Geometry Basics", readMins: 7, updated: "2 days ago", points: ["Points are located as ordered pairs (x, y) relative to the origin and the two axes.", "Distance between two points: d = √((x₂−x₁)² + (y₂−y₁)²).", "Midpoint formula: ((x₁+x₂)/2, (y₁+y₂)/2).", "Gradient (slope) between two points: m = (y₂−y₁)/(x₂−x₁); equal gradients mean collinear points.", "The signs of x and y decide which of the four quadrants a point lies in.", "Sketch the points first — a rough graph prevents sign mistakes."] },
  { topic: "Geometry: Congruence, Ratios & Pythagoras", readMins: 9, updated: "3 weeks ago", points: ["Congruent triangles satisfy SAS, ASA, SSS or RHS — know each condition with a diagram.", "Pythagoras: in a right triangle, hypotenuse² = (side 1)² + (side 2)².", "Similar figures have equal corresponding angles and proportional corresponding sides.", "The Basic Proportionality (Thales) theorem links a parallel line with side ratios in a triangle.", "In any triangle, the largest angle faces the longest side.", "Perpendicular bisectors of the sides meet at the circumcentre, equidistant from all vertices."] },
];

const MATH_10: RealNote[] = [
  { topic: "Quadratic Equations & Discriminant", readMins: 8, updated: "2 days ago", points: ["Standard form ax² + bx + c = 0 (a ≠ 0); solve by factorization or the quadratic formula.", "Quadratic formula: x = (−b ± √(b² − 4ac)) / 2a.", "Discriminant b² − 4ac decides the nature of roots: >0 real and distinct, =0 real and equal, <0 complex.", "Sum of roots = −b/a; product of roots = c/a.", "Completing the square is the method used to derive the formula itself.", "Word problems: let the unknown be x, translate the sentence into an equation, then solve."] },
  { topic: "Matrices: Solving Systems of Equations", readMins: 7, updated: "1 week ago", points: ["Write simultaneous equations as the matrix equation AX = B.", "Solve with the inverse: X = A⁻¹B, valid when det(A) ≠ 0.", "Cramer's rule: x = det(Aₓ)/det(A) and y = det(A_y)/det(A).", "A singular system (det = 0) has either no solution or infinitely many.", "Row operations — swap, scale, add rows — reduce a matrix step by step.", "Verify any solution by substituting it into both original equations."] },
  { topic: "Partial Fractions", readMins: 6, updated: "2 weeks ago", points: ["Partial fractions split one fraction into a sum of simpler fractions.", "Distinct linear factors: write A/(x−p) + B/(x−q) and solve for A and B.", "A repeated factor (x−p)² needs A/(x−p) + B/(x−p)².", "An irreducible quadratic factor needs (Ax + B)/(x² + px + q).", "Shortcut: substitute the roots of the factors to read off constants instantly.", "Improper fractions must be divided out before resolving."] },
  { topic: "Sets & Functions", readMins: 7, updated: "1 week ago", points: ["A set is a well-defined collection written with braces, e.g. {1, 2, 3}.", "Union A∪B (either), intersection A∩B (both), difference A−B (in A only).", "Venn diagrams make unions, intersections and complements visual.", "A function maps every input to exactly one output.", "Types of functions: one-one (injective), onto (surjective), both (bijective).", "Domain = allowed inputs; range = outputs actually produced."] },
  { topic: "Introduction to Trigonometry", readMins: 8, updated: "3 days ago", points: ["Define sin, cos and tan for a right triangle as ratios of its sides.", "Exact values to recall: sin 30° = 1/2, cos 60° = 1/2, tan 45° = 1.", "Fundamental identity: sin²θ + cos²θ = 1 for every angle θ.", "Angle of elevation (up from horizontal) and depression (down) model real problems.", "Heights and distances: draw the triangle, mark the knowns, then pick the right ratio.", "Reciprocal ratios: cosec, sec and cot are 1/sin, 1/cos and 1/tan."] },
  { topic: "Circles: Chords, Tangents & Angles", readMins: 8, updated: "2 weeks ago", points: ["Exactly one circle passes through three non-collinear points — its centre is the circumcentre.", "The perpendicular from the centre to a chord bisects the chord.", "A tangent touches the circle at one point and is perpendicular to the radius there.", "The two tangents drawn from an external point are equal in length.", "The central angle on an arc is twice the angle it subtends at the circumference.", "The angle in a semicircle is always 90° (Thales' result)."] },
];

const MATH_11: RealNote[] = [
  { topic: "Number Systems & Complex Numbers", readMins: 8, updated: "1 week ago", points: ["Hierarchy: naturals ⊂ integers ⊂ rationals ⊂ reals ⊂ complex numbers.", "A complex number z = a + bi with i² = −1; its conjugate is a − bi.", "z·z̄ = |z|², and dividing by a complex number means multiplying with its conjugate.", "Add real-with-real and imaginary-with-imaginary; multiply using i² = −1.", "Modulus |z| = √(a² + b²); the argument gives the direction angle.", "Rationalize denominators like 1/(a + bi) by multiplying with the conjugate."] },
  { topic: "Matrices & Determinants (3×3)", readMins: 9, updated: "3 days ago", points: ["Evaluate 3×3 determinants by cofactor expansion along any row or column.", "Cramer's rule extends to three unknowns using D, Dₓ, D_y and D_z.", "Row reduction (Gauss elimination) solves systems without needing inverses.", "Swapping two rows changes the sign of the determinant.", "Rank equals the number of non-zero rows in echelon form.", "Homogeneous systems always admit the trivial solution x = y = z = 0."] },
  { topic: "Sequences & Series", readMins: 8, updated: "2 weeks ago", points: ["Arithmetic progression: aₙ = a + (n−1)d; sum Sₙ = n/2·(2a + (n−1)d).", "Geometric progression: aₙ = arⁿ⁻¹; sum Sₙ = a(1 − rⁿ)/(1 − r).", "An infinite GP converges to a/(1 − r) only when |r| < 1.", "Arithmetic-geometric mean inequality: A ≥ G for positive numbers.", "Harmonic progression: the reciprocals form an AP — used in speed and price averages.", "Practise reading sigma (Σ) notation with its limits."] },
  { topic: "Permutations, Combinations & Probability", readMins: 8, updated: "1 week ago", points: ["Permutation = arrangement (order matters): ⁿPᵣ = n!/(n−r)!", "Combination = selection (order free): ⁿCᵣ = n!/(r!(n−r)!)", "n! arranges all n objects; remember 0! = 1 by definition.", "P(A) = favourable/total; add for OR, multiply for AND with independent events.", "Complement rule: P(not A) = 1 − P(A) — often the fastest route.", "Phrases like at least one usually signal a complement-rule problem."] },
  { topic: "Trigonometric Identities & Equations", readMins: 9, updated: "2 days ago", points: ["From sin²θ + cos²θ = 1, divide to get 1 + tan²θ = sec²θ.", "Compound angles: sin(A ± B) = sin A cos B ± cos A sin B.", "Double angle: sin 2θ = 2 sin θ cos θ and cos 2θ = cos²θ − sin²θ.", "Solve trig equations over a stated interval, then write the general solution.", "Periodicity: sin and cos repeat every 360°, tan every 180°.", "The law of sines and the law of cosines solve any triangle, not just right-angled ones."] },
  { topic: "Mathematical Induction & Binomial Theorem", readMins: 8, updated: "3 weeks ago", points: ["Induction steps: verify n = 1, assume true for n = k, then prove for n = k + 1.", "State the base case, hypothesis and inductive step explicitly in every proof.", "Binomial theorem: (a + b)ⁿ = Σ ⁿCᵣ aⁿ⁻ʳ bʳ.", "The (r + 1)-th term is T₍ᵣ₊₁₎ = ⁿCᵣ aⁿ⁻ʳ bʳ — find terms without expanding.", "The expansion of (a + b)ⁿ contains n + 1 terms.", "Setting a = b = 1 gives the sum of all coefficients: 2ⁿ."] },
];

const MATH_12: RealNote[] = [
  { topic: "Functions, Limits & Continuity", readMins: 8, updated: "2 days ago", points: ["A function f: X → Y assigns every input exactly one output.", "A limit exists at a only when the left-hand and right-hand limits agree.", "Standard limits: sin x/x → 1 and (1 − cos x)/x → 0 as x → 0.", "Resolve 0/0 forms by factoring, rationalizing or standard limits.", "A continuous function has no break, jump or hole at the point.", "Composite functions: (g∘f)(x) = g(f(x)) — apply f first, then g."] },
  { topic: "Differentiation & Applications", readMins: 9, updated: "1 week ago", points: ["Definition: f'(x) = lim(h→0) [f(x+h) − f(x)]/h — the gradient of the tangent.", "Power rule d/dx xⁿ = n·xⁿ⁻¹; use the chain rule for composite functions.", "Product rule (uv)' = u'v + uv'; learn the quotient rule for fractions.", "Stationary points: solve f'(x) = 0; f'' > 0 gives a minimum, f'' < 0 a maximum.", "Memorize derivatives of sin x, cos x, tan x, eˣ and ln x.", "Applications: tangents and normals, rates of change, maxima and minima problems."] },
  { topic: "Integration & Definite Integrals", readMins: 9, updated: "3 days ago", points: ["Integration reverses differentiation: ∫xⁿ dx = xⁿ⁺¹/(n+1) + C for n ≠ −1.", "Indefinite integrals carry the constant C — a whole family of curves.", "Definite integral ∫ₐᵇ f(x) dx = F(b) − F(a) gives the signed area.", "Substitution (reverse chain rule) handles composite integrands.", "Standard integrals: sin, cos, sec²x and 1/x (→ ln|x|).", "Area between curves: integrate (top curve − bottom curve) across the intersections."] },
  { topic: "Introduction to Analytic Geometry", readMins: 7, updated: "2 weeks ago", points: ["Distance, midpoint and gradient formulas connect algebra with geometry.", "Straight lines: y = mx + c, or point-slope form y − y₁ = m(x − x₁).", "Parallel lines have m₁ = m₂; perpendicular lines have m₁·m₂ = −1.", "Angle between lines: tan θ = |(m₂ − m₁)/(1 + m₁m₂)|.", "Distance from a point to a line: |ax₁ + by₁ + c|/√(a² + b²).", "The sign of ax₁ + by₁ + c places a point relative to the line."] },
  { topic: "Conic Sections", readMins: 8, updated: "1 week ago", points: ["Circle: (x − h)² + (y − k)² = r² with centre (h, k) and radius r.", "Parabola y² = 4ax opens right, with focus (a, 0) and directrix x = −a.", "Ellipse x²/a² + y²/b² = 1; eccentricity e = √(1 − b²/a²) stays below 1.", "Hyperbola x²/a² − y²/b² = 1 with asymptotes y = ±(b/a)x.", "All four conics come from slicing a double cone at different angles.", "Identify the conic from its equation before computing focus or directrix data."] },
  { topic: "Vectors", readMins: 7, updated: "3 weeks ago", points: ["A vector has magnitude and direction, written ai + bj or with an arrow.", "Magnitude |v| = √(a² + b²); a unit vector has length 1 (divide by |v|).", "Dot product v·w = |v||w|cos θ; a zero dot product means perpendicular.", "Cross product v×w is perpendicular to both; its magnitude is the parallelogram area.", "Position vectors locate points relative to the origin.", "Use dot products to compute the angle between two vectors."] },
];

/* ════════════════ PHYSICS ════════════════ */
const PHYSICS_9: RealNote[] = [
  { topic: "Physical Quantities & Measurement", readMins: 6, updated: "1 week ago", points: ["Base SI units: metre, kilogram, second, ampere, kelvin, mole and candela.", "Derived units such as newton, joule and watt are built from base units.", "Significant figures show a measurement's precision — carry them through calculations.", "Prefixes: kilo (10³), mega (10⁶), milli (10⁻³), micro (10⁻⁶).", "Vernier callipers read to 0.01 cm; a micrometer screw gauge to 0.001 cm.", "Least count = the smallest division readable on the instrument."] },
  { topic: "Kinematics: Equations of Motion", readMins: 8, updated: "2 days ago", points: ["Scalars (speed, distance) have magnitude only; vectors (velocity, displacement) add direction.", "Uniform acceleration: v = u + at, s = ut + ½at², v² = u² + 2as.", "Derive all three equations from a velocity-time graph (slope and area).", "Free fall: replace a with g ≈ 9.8 m/s² and take u = 0 for a dropped object.", "Average velocity = total displacement / total time.", "Sketch the v-t graph first — it usually reveals the solution path."] },
  { topic: "Dynamics: Newton's Laws & Momentum", readMins: 8, updated: "1 week ago", points: ["First law (inertia): no net force means no change in motion.", "Second law: F = ma — the workhorse of mechanics problems.", "Third law: action and reaction are equal, opposite, and act on different bodies.", "Momentum p = mv; impulse Ft = Δp explains seatbelts and airbags.", "Conservation of momentum governs collisions and explosions.", "Weight = mg changes with local g; mass stays the same everywhere."] },
  { topic: "Work, Energy & Power", readMins: 7, updated: "2 weeks ago", points: ["Work W = Fd cosθ is zero when the force is perpendicular to the displacement.", "Kinetic energy KE = ½mv²; potential energy PE = mgh near the Earth's surface.", "Conservation of energy: the total stays constant in an ideal system.", "Power P = W/t; the SI unit watt equals one joule per second.", "Efficiency = useful output / total input × 100%.", "Compare renewable (solar, hydro, wind) with non-renewable (fossil) energy sources."] },
  { topic: "Density, Pressure & Archimedes' Principle", readMins: 7, updated: "3 days ago", points: ["Density = mass/volume in kg/m³; water is 1000 kg/m³.", "Pressure = force/area — a small area gives a big pressure (why needles are sharp).", "In liquids P = ρgh grows with depth, whatever the container's shape.", "Pascal's principle: pressure applied to an enclosed fluid transmits equally (hydraulics).", "Archimedes' principle: upthrust equals the weight of displaced fluid.", "A floating body displaces exactly its own weight of fluid."] },
  { topic: "Thermal Properties & Heat Transfer", readMins: 7, updated: "1 week ago", points: ["Temperature measures the average kinetic energy of particles; heat is energy in transit.", "Specific heat capacity: water's 4200 J/kg·K is unusually high.", "Heating: Q = mcΔθ; phase change: Q = mL (latent heat).", "Linear expansion ΔL = αL₀ΔT explains gaps in bridges and bimetal strips.", "Conduction (solids), convection (fluids) and radiation (no medium needed).", "A thermos flask fights all three transfers: vacuum, stopper and silvered walls."] },
];

const PHYSICS_10: RealNote[] = [
  { topic: "Simple Harmonic Motion", readMins: 8, updated: "2 days ago", points: ["SHM: acceleration is proportional to displacement and points back to the mean position.", "Restoring force F = −kx; mass-spring period T = 2π√(m/k).", "Simple pendulum: T = 2π√(L/g) — a classic way to measure g.", "Amplitude, frequency f = 1/T and phase fully describe the motion.", "Energy trades between kinetic (at the mean) and potential (at the extremes).", "Applications: clocks, watches, car suspensions and musical instruments."] },
  { topic: "Waves & Sound", readMins: 8, updated: "1 week ago", points: ["Mechanical waves need a medium; electromagnetic waves do not.", "Transverse waves vibrate perpendicular to travel; longitudinal waves (sound) vibrate parallel.", "The wave equation v = fλ links speed, frequency and wavelength.", "Loudness follows amplitude; pitch follows frequency; quality follows waveform.", "Echoes are reflected sound — sonar and ultrasound imaging rely on them.", "Sound travels about 343 m/s in air at 20 °C, faster in liquids, fastest in solids."] },
  { topic: "Geometrical Optics: Reflection & Refraction", readMins: 8, updated: "3 days ago", points: ["Law of reflection: the angle of incidence equals the angle of reflection.", "A plane-mirror image is virtual, erect, the same size and laterally inverted.", "Refraction bends light between media; Snell's law: n₁ sinθ₁ = n₂ sinθ₂.", "Total internal reflection begins beyond the critical angle — the basis of fibre optics.", "Refractive index n = c/v measures the optical density of a medium.", "Lenses use refraction: converging (convex) versus diverging (concave)."] },
  { topic: "Electricity: Current, Ohm's Law & Power", readMins: 8, updated: "1 week ago", points: ["Current I = Q/t; conventional current flows opposite to the electrons.", "Ohm's law V = IR at constant temperature; resistance depends on length, area and material.", "Series: R = R₁ + R₂ + …; parallel: 1/R = 1/R₁ + 1/R₂ + …", "Electric power P = VI = I²R = V²/R.", "Joule's law of heating H = I²Rt explains fuses and heaters.", "One kilowatt-hour (unit) is the energy a 1 kW appliance uses in an hour."] },
  { topic: "Electromagnetism", readMins: 7, updated: "2 weeks ago", points: ["A current-carrying conductor produces a magnetic field (right-hand grip rule).", "Force on a current-carrying wire F = BIL sinθ; on a moving charge F = qvB sinθ.", "A D.C. motor turns electrical energy into rotation; a generator reverses the process.", "Electromagnetic induction: moving a magnet in a coil induces current.", "Transformers step voltage up or down for efficient transmission.", "An A.C. generator converts mechanical energy into alternating current."] },
  { topic: "Electronics & Radioactivity", readMins: 7, updated: "3 weeks ago", points: ["Doping silicon with donors makes n-type; with acceptors, p-type.", "A p-n junction diode conducts forward and blocks reverse — a one-way valve.", "Rectification converts A.C. to D.C. using diodes.", "Transistors amplify signals or act as electronic switches.", "Radioactive emissions: alpha (helium nucleus), beta (electron) and gamma (EM radiation).", "Half-life is the time for half the nuclei to decay; radiation ionizes living tissue."] },
];

const PHYSICS_11: RealNote[] = [
  { topic: "Measurements & Significant Figures", readMins: 6, updated: "1 week ago", points: ["Precision is repeatability; accuracy is closeness to the true value.", "Uncertainties add for sums; relative errors add for products.", "Dimensional analysis checks equations, e.g. [F] = [M][L][T]⁻².", "Handle least count and zero error in every lab measurement.", "Report results with the correct number of significant figures.", "Random errors scatter readings; systematic errors shift them all the same way."] },
  { topic: "Vectors & Equilibrium", readMins: 8, updated: "2 days ago", points: ["Add vectors head-to-tail; components: Aₓ = A cosθ, A_y = A sinθ.", "Resultant magnitude R = √(Aₓ² + A_y²) with direction tan⁻¹(A_y/Aₓ).", "Dot product A·B = AB cosθ (a scalar); cross product A×B = AB sinθ (a vector).", "Torque τ = rF sinθ is the turning effect about a pivot.", "First condition ΣF = 0; second condition Στ = 0 for full equilibrium.", "Resolve every force before applying the equilibrium conditions."] },
  { topic: "Projectile & Circular Motion", readMins: 8, updated: "1 week ago", points: ["Projectile motion combines uniform horizontal velocity with vertical acceleration.", "Range and time of flight follow from the launch speed v₀ and angle θ.", "On level ground (ignoring air) the maximum range occurs at 45°.", "Uniform circular motion needs centripetal acceleration a = v²/r.", "Centripetal force F = mv²/r points to the centre — never outward.", "Banked roads and satellites are centripetal-force problems in disguise."] },
  { topic: "Fluid Dynamics", readMins: 7, updated: "2 weeks ago", points: ["Streamline (laminar) versus turbulent flow, separated by the Reynolds number.", "Equation of continuity A₁v₁ = A₂v₂ — flow speeds up in narrow pipes.", "Bernoulli's principle: faster flow means lower pressure (aerofoils, spray guns).", "Terminal velocity: weight balances drag plus upthrust in a viscous fluid.", "Stokes' law F = 6πηrv for small spheres falling in viscous liquids.", "Applications: aircraft wings, carburettors and blood-flow measurement."] },
  { topic: "Physical Optics: Interference & Diffraction", readMins: 8, updated: "3 days ago", points: ["Huygens' principle constructs wavefronts to explain reflection and refraction.", "Young's double slit: bright and dark fringes from path differences d sinθ = mλ.", "Constructive interference: path difference = mλ; destructive: (m + ½)λ.", "Diffraction spreads waves around obstacles and through narrow slits.", "A diffraction grating separates wavelengths better than a double slit.", "Interference proves light behaves as a wave; polarization shows it is transverse."] },
  { topic: "Thermodynamics & Kinetic Theory", readMins: 8, updated: "1 week ago", points: ["Kinetic theory: gas pressure comes from molecular collisions with the walls.", "First law: ΔQ = ΔU + W — energy conservation with heat included.", "Know isothermal, adiabatic, isobaric and isochoric processes.", "The Carnot cycle sets the ceiling on efficiency between two temperatures.", "Second law: heat flows spontaneously from hot to cold; entropy tends to increase.", "An ideal gas's internal energy depends only on its temperature."] },
];

const PHYSICS_12: RealNote[] = [
  { topic: "Electrostatics: Coulomb's Law & Electric Fields", readMins: 8, updated: "2 days ago", points: ["Coulomb's law F = kq₁q₂/r² with k ≈ 9×10⁹ N·m²/C².", "Electric field E = F/q in N/C; field lines leave positive and enter negative charges.", "Point-charge field E = kq/r² points radially.", "Electric potential V = kq/r; potential energy U = kq₁q₂/r.", "Equipotential surfaces are perpendicular to field lines — no work moves a charge along one.", "Capacitance C = Q/V: a capacitor stores energy in its electric field."] },
  { topic: "Current Electricity & Kirchhoff's Laws", readMins: 8, updated: "1 week ago", points: ["Ohm's law plus resistivity ρ = RA/L characterizes conductors.", "Junction rule ΣI = 0 and loop rule ΣV = 0 solve any network.", "A Wheatstone bridge balances when R₁/R₂ = R₃/R₄.", "A potentiometer measures EMF without drawing current.", "Terminal voltage V = E − Ir exposes internal resistance.", "Ammeters go in series (low resistance); voltmeters in parallel (high resistance)."] },
  { topic: "Electromagnetism & Electromagnetic Induction", readMins: 8, updated: "3 days ago", points: ["The right-hand rule gives the field direction around a current.", "Force on a charge: F = qvB sinθ; on a wire: F = BIL sinθ.", "Faraday's law: induced EMF = −N ΔΦ/Δt; Lenz's law gives its direction.", "Motors convert electrical energy to rotation; generators do the reverse.", "A.C.: V = V₀ sin ωt; RMS values govern power (Vrms = V₀/√2).", "Transformers move power efficiently between voltage levels."] },
  { topic: "Dawn of Modern Physics", readMins: 8, updated: "2 weeks ago", points: ["Photoelectric effect: light ejects electrons only above a threshold frequency.", "Einstein: light arrives in quanta (photons) of energy hf.", "Compton scattering and pair production reinforce the photon model.", "Special relativity: the speed of light is constant; E = mc².", "de Broglie: particles have wavelength λ = h/p — wave-particle duality.", "The uncertainty principle limits simultaneous position and momentum."] },
  { topic: "Atomic Spectra & Atomic Models", readMins: 7, updated: "1 week ago", points: ["Line spectra are element fingerprints — evidence of quantized energy levels.", "Bohr model: photons are emitted when electrons drop between allowed orbits.", "Photon energy: E = hf = E₂ − E₁.", "Excitation and ionization energies read straight off the level diagram.", "X-rays emerge when fast electrons strike a metal target.", "Laser light is coherent, monochromatic and highly directional."] },
  { topic: "Nuclear Physics & Radioactivity", readMins: 8, updated: "3 weeks ago", points: ["A nucleus contains Z protons and N neutrons; binding energy holds it together.", "Mass defect times c² gives the binding energy (E = Δmc²).", "Decay law N = N₀e^(−λt); half-life t½ = ln2/λ.", "Fission splits heavy nuclei (reactors); fusion joins light ones (stars).", "Radiation hazards: minimize time, maximize distance, use shielding.", "Geiger counters and cloud chambers detect nuclear radiation."] },
];

/* ════════════════ CHEMISTRY ════════════════ */
const CHEM_9: RealNote[] = [
  { topic: "Fundamentals of Chemistry", readMins: 6, updated: "1 week ago", points: ["Branches: physical, organic, inorganic, analytical, biochemistry and industrial chemistry.", "One atomic mass unit (amu) is 1/12 the mass of a carbon-12 atom.", "Empirical formula = simplest whole-number ratio; molecular formula = actual count.", "One mole = 6.022×10²³ particles; molar mass is measured in grams per mole.", "Percentage composition feeds empirical-formula problems.", "Every chemical equation must be balanced — atoms are conserved."] },
  { topic: "Atomic Structure & Isotopes", readMins: 7, updated: "3 days ago", points: ["Protons and neutrons sit in the nucleus; electrons occupy shells around it.", "Atomic number Z = protons; mass number A = protons + neutrons.", "Isotopes differ only in neutrons (H-1, H-2, H-3) yet share chemistry.", "Shells K, L, M… hold at most 2n² electrons each.", "Valence electrons (outermost shell) drive chemical behaviour.", "Ions form when atoms gain or lose electrons to complete a shell."] },
  { topic: "Periodic Table & Periodicity", readMins: 7, updated: "2 weeks ago", points: ["Modern periodic law: properties repeat as a function of atomic number.", "Groups (18 columns) share valence configuration; periods (7 rows) fill shells.", "Metals sit left, non-metals right, metalloids along the staircase.", "Atomic radius shrinks across a period and grows down a group.", "Ionization energy and electronegativity rise across a period.", "Noble gases are inert because their valence shells are full."] },
  { topic: "Chemical Bonding & Molecular Structure", readMins: 8, updated: "1 week ago", points: ["Ionic bond: a metal donates electrons to a non-metal (NaCl).", "Covalent bond: non-metals share electron pairs (H₂O, CH₄).", "Coordinate covalent bond: one atom donates both shared electrons (NH₄⁺).", "Metallic bonding: positive ions in a sea of delocalized electrons.", "Bond type predicts melting point, conductivity and solubility.", "Valency is the number of bonds an atom forms; check with Lewis structures."] },
  { topic: "Physical States of Matter & Solutions", readMins: 7, updated: "2 days ago", points: ["Solid, liquid and gas differ in particle spacing, energy and arrangement.", "Diffusion and Brownian motion are evidence of moving particles.", "Solute + solvent = solution; suspensions settle, colloids do not.", "Solid solubility usually rises with temperature; gas solubility falls.", "Express concentration with percentages or molarity (mol/L).", "Evaporation happens at the surface at any temperature; boiling happens throughout at one temperature."] },
  { topic: "Electrochemistry Basics & Reactivity", readMins: 7, updated: "3 weeks ago", points: ["Oxidation is loss of electrons; reduction is gain (OIL RIG).", "Redox reactions pair the two — one species oxidizes while another reduces.", "Metals above hydrogen in the reactivity series displace it from dilute acids.", "The series ranks metals from potassium (most reactive) to gold (least).", "Iron corrosion needs both water and oxygen; galvanizing protects it.", "Electroplating uses electrolysis to coat objects with metal."] },
];

const CHEM_10: RealNote[] = [
  { topic: "Chemical Equilibrium & Le Chatelier's Principle", readMins: 8, updated: "2 days ago", points: ["Reversible reactions reach dynamic equilibrium: forward rate equals reverse rate.", "Kc = [products]ˣ/[reactants]ʸ, fixed at a given temperature.", "Le Chatelier: a disturbed equilibrium shifts to oppose the change.", "Pressure shifts move gaseous equilibria toward fewer gas moles.", "Temperature is the only factor that changes Kc itself.", "The Haber process for ammonia applies all of these principles."] },
  { topic: "Acids, Bases, Salts & pH", readMins: 7, updated: "1 week ago", points: ["Arrhenius: acids give H⁺ and bases give OH⁻ in water.", "Brønsted-Lowry: acids donate protons and bases accept them.", "pH = −log[H⁺]: 7 is neutral, lower is acidic, higher is basic.", "Strong acids (HCl) fully ionize; weak acids (CH₃COOH) only partially.", "Neutralization: acid + base → salt + water.", "NH₄Cl (strong acid + weak base) is an acidic salt; Na₂CO₃ is basic."] },
  { topic: "Organic Chemistry Fundamentals", readMins: 7, updated: "3 days ago", points: ["Organic chemistry studies carbon chains and rings (catenation).", "Hydrocarbons contain only C and H: saturated versus unsaturated.", "Functional groups like −OH, −COOH and −CHO define families.", "Represent molecules with molecular, structural and condensed formulas.", "Isomers share a molecular formula but differ in structure.", "A homologous series advances by −CH₂− each member."] },
  { topic: "Hydrocarbons: Alkanes, Alkenes & Alkynes", readMins: 8, updated: "2 weeks ago", points: ["Alkanes CₙH₂ₙ₊₂: saturated, undergo substitution (halogenation).", "Alkenes CₙH₂ₙ: one double bond, undergo addition (H₂, Br₂, H₂O).", "Alkynes CₙH₂ₙ₋₂: a triple bond, also addition reactions.", "Bromine water decolourizes instantly with unsaturated hydrocarbons — a key test.", "Cracking splits long alkanes into smaller alkanes and alkenes.", "Complete combustion of alkanes gives CO₂ and H₂O."] },
  { topic: "Biochemistry: Carbohydrates, Proteins & Lipids", readMins: 7, updated: "1 week ago", points: ["Carbohydrates: mono- (glucose), di- (sucrose) and polysaccharides (starch).", "Proteins are amino acids joined by peptide bonds; enzymes are proteins.", "Lipids (fats and oils) are esters of glycerol with fatty acids.", "Vitamins: water-soluble (B, C) versus fat-soluble (A, D, E, K).", "DNA and RNA are nucleic acids made of nucleotides.", "Deficiency diseases link missing nutrients to illness (scurvy, rickets)."] },
  { topic: "Environmental Chemistry & Industries", readMins: 6, updated: "3 weeks ago", points: ["Air pollutants: CO, SO₂, NOₓ and particulates; SO₂ and NOₓ cause acid rain.", "Greenhouse gases (CO₂, CH₄) drive global warming.", "CFCs release chlorine radicals that deplete the ozone layer.", "Water pollution: sewage, industrial waste and fertilizers (eutrophication).", "Key processes: the Solvay process (Na₂CO₃), urea and petroleum refining.", "Reduce, reuse and recycle to limit waste and resource loss."] },
];

const CHEM_11: RealNote[] = [
  { topic: "Stoichiometry & Limiting Reactants", readMins: 8, updated: "1 week ago", points: ["Balance the equation first — all stoichiometry rests on mole ratios.", "Convert mass ↔ moles with the molar mass at every step.", "The limiting reactant runs out first and caps the yield.", "Theoretical versus actual yield gives the percentage yield.", "Gravimetric and volumetric analysis apply these calculations.", "One mole of any ideal gas occupies 22.414 dm³ at STP."] },
  { topic: "Atomic Structure & Orbitals", readMins: 8, updated: "2 days ago", points: ["Quantum numbers n, l, m and s uniquely describe each electron.", "s, p, d and f orbitals hold 2, 6, 10 and 14 electrons respectively.", "Aufbau, Pauli and Hund rules govern how orbitals fill.", "The electromagnetic spectrum: E = hν links energy and frequency.", "Line spectra arise from quantized electron transitions.", "Electronic configuration explains an element's chemistry."] },
  { topic: "Theories of Bonding & Molecular Geometry", readMins: 8, updated: "1 week ago", points: ["VSEPR: electron pairs repel; geometry minimizes that repulsion.", "Hybridization: sp (linear), sp² (trigonal, 120°), sp³ (tetrahedral, 109.5°).", "Sigma bonds overlap head-on; pi bonds overlap sideways.", "Electronegativity differences create bond polarity and dipole moments.", "Hydrogen bonding explains water's unusually high boiling point.", "Dipole-induced and London dispersion forces set intermolecular strength."] },
  { topic: "Thermochemistry & Energetics", readMins: 8, updated: "2 weeks ago", points: ["Exothermic releases heat (ΔH < 0); endothermic absorbs it (ΔH > 0).", "Hess's law: ΔH depends only on the initial and final states.", "Born-Haber cycles break lattice energy into measurable steps.", "Calorimetry measures heat with q = mcΔθ.", "Breaking bonds costs energy; making bonds releases it.", "First law of thermodynamics: energy is conserved (ΔE = q + w)."] },
  { topic: "Chemical Equilibrium (Advanced)", readMins: 8, updated: "3 days ago", points: ["Kc (concentrations) and Kp (pressures) both describe equilibrium.", "The reaction quotient Q predicts the direction of the shift.", "Le Chatelier's principle, quantified: shifts restore K after a disturbance.", "The common-ion effect suppresses ionization — the basis of buffers.", "The solubility product Ksp governs precipitation.", "Industrial examples: the contact process (H₂SO₄) and the Haber process (NH₃)."] },
  { topic: "Reaction Kinetics & Solutions", readMins: 7, updated: "1 week ago", points: ["Rate depends on concentration, temperature, surface area and catalysts.", "Rate law: rate = k[A]ˣ[B]ʸ with overall order x + y.", "Catalysts lower the activation energy without being consumed.", "Express concentration with molarity, molality or mole fraction.", "Colligative properties: boiling-point rise and freezing-point depression.", "Collision theory: only energetic, well-oriented collisions react."] },
];

const CHEM_12: RealNote[] = [
  { topic: "s- and p-Block Elements", readMins: 8, updated: "1 week ago", points: ["Alkali metals are soft, highly reactive metals with a +1 oxidation state.", "Alkaline-earth metals (Group IIA) are harder and less reactive.", "Group IIIA shows the inert-pair effect in its heavier members.", "Group IVA runs from carbon's catenation to lead's metallic character.", "Halogens become less reactive down the group.", "Noble gases form few compounds (XeF₂, XeF₄) only under forcing conditions."] },
  { topic: "Transition Elements (d-Block)", readMins: 8, updated: "2 days ago", points: ["Partially filled d-subshells allow variable oxidation states.", "Coloured ions come from d-electron transitions absorbing visible light.", "Unpaired d-electrons make many compounds paramagnetic.", "Ligands form complexes such as [Cu(NH₃)₄]²⁺.", "Catalytic roles: iron in the Haber process, nickel in hydrogenation.", "Alloying exploits their hardness and corrosion resistance."] },
  { topic: "Alkyl Halides", readMins: 8, updated: "1 week ago", points: ["SN1 (two steps via carbocation) versus SN2 (one step, inversion of configuration).", "Tertiary halides favour SN1; primary halides favour SN2.", "Prepare them from alcohols (HX or PX₃) or from alkanes (halogenation).", "Elimination competes with substitution at higher temperature.", "Grignard reagents (RMgX) build longer carbon chains.", "Reactivity order: RI > RBr > RCl."] },
  { topic: "Alcohols, Phenols & Ethers", readMins: 7, updated: "2 weeks ago", points: ["Primary, secondary and tertiary alcohols differ at the carbon bearing the −OH group.", "Oxidation: primary → aldehyde → acid; secondary → ketone; tertiary resists.", "The Lucas test distinguishes alcohol classes by turbidity speed.", "Phenol is acidic thanks to a resonance-stabilized phenoxide ion; alcohols are not.", "Ethers are relatively inert — useful solvents.", "Fermentation makes ethanol; dehydrating alcohols makes alkenes."] },
  { topic: "Aldehydes & Ketones", readMins: 8, updated: "3 days ago", points: ["The carbonyl C=O is polarized (Cδ⁺); aldehydes end a chain, ketones sit inside it.", "Nucleophiles (HCN, NaHSO₃) add across the C=O bond.", "Aldehydes reduce Tollens' reagent to a silver mirror; ketones do not.", "Fehling's solution flags aliphatic aldehydes.", "The iodoform test detects methyl ketones (CH₃CO−).", "Aldol condensation and Cannizzaro reactions extend carbonyl chemistry."] },
  { topic: "Carboxylic Acids & Derivatives", readMins: 7, updated: "1 week ago", points: ["The −COOH acidity comes from the resonance-stabilized carboxylate ion.", "Electron-withdrawing substituents increase acid strength.", "Derivatives: acyl chlorides, anhydrides, esters and amides.", "Fischer esterification: acid + alcohol ⇌ ester + water.", "Soap is made by alkaline hydrolysis of fats (saponification).", "Amides hydrolyze back to acids under acid or base catalysis."] },
];

/* ════════════════ BIOLOGY ════════════════ */
const BIO_9: RealNote[] = [
  { topic: "Introduction to Biology & Branches", readMins: 5, updated: "1 week ago", points: ["Biology studies life at every level, from molecules to ecosystems.", "Major branches: botany, zoology, microbiology, genetics and ecology.", "Levels of organization: cell → tissue → organ → organ system → organism.", "Careers: medicine, agriculture, biotechnology, pharmacy and forestry.", "The scientific method: observation, hypothesis, experiment, conclusion.", "Bioinformatics and computational biology are fast-growing fields."] },
  { topic: "Cell Structure & Organelles", readMins: 7, updated: "2 days ago", points: ["Cell theory: all living things are made of cells, and cells come from cells.", "Prokaryotes lack a true nucleus; eukaryotes have one.", "Mitochondria are the powerhouses — cellular respiration and ATP.", "Chloroplasts (plants only) carry out photosynthesis with chlorophyll.", "Ribosomes build proteins, the ER transports them, and Golgi bodies package them.", "The cell wall (plants) gives support; the membrane controls transport."] },
  { topic: "Enzymes: Nature & Action", readMins: 7, updated: "1 week ago", points: ["Enzymes are biological catalysts, nearly all proteins.", "Lock-and-key and induced-fit models describe substrate binding at the active site.", "Enzymes are substrate-specific and speed reactions enormously.", "Activity peaks at an optimum temperature and pH (about 37 °C in humans).", "Heat or extreme pH denatures the enzyme and ruins the active site.", "Examples: amylase (starch), pepsin (protein) and catalase (H₂O₂)."] },
  { topic: "Bioenergetics: Photosynthesis", readMins: 8, updated: "3 days ago", points: ["Summary: 6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂.", "Light reactions in the thylakoids split water and make ATP and NADPH.", "The Calvin cycle fixes CO₂ into sugar in the stroma.", "Chlorophyll absorbs red and blue light and reflects green.", "Limiting factors: light intensity, CO₂ concentration and temperature.", "Respiration runs the reaction backwards to release the stored energy."] },
  { topic: "Cellular Respiration", readMins: 8, updated: "2 weeks ago", points: ["Glycolysis in the cytoplasm splits glucose into two pyruvate (net 2 ATP).", "The Krebs cycle in the mitochondrial matrix harvests electron carriers.", "The electron transport chain produces the bulk of the ATP.", "Aerobic respiration yields about 36–38 ATP per glucose.", "Anaerobic pathways: lactic acid (muscle) or alcohol fermentation (yeast).", "Aerobic-versus-anaerobic comparison tables are favourite exam items."] },
  { topic: "Biodiversity & Classification", readMins: 7, updated: "1 week ago", points: ["Five-kingdom system: Monera, Protista, Fungi, Plantae and Animalia.", "Binomial nomenclature: Genus + species, as in Homo sapiens.", "Biodiversity spans genes, species and ecosystems.", "Bacteria can help (yogurt, nitrogen fixation) or harm (disease).", "Viruses are borderline: genetic material in a protein coat, needing a host.", "Conservation protects biodiversity via reserves and breeding programmes."] },
];

const BIO_10: RealNote[] = [
  { topic: "Homeostasis & Kidney Function", readMins: 8, updated: "2 days ago", points: ["Homeostasis keeps the internal environment constant.", "Osmoregulation balances water and salts; thermoregulation balances heat.", "The nephron: filtration (Bowman's capsule) → reabsorption → secretion.", "ADH from the pituitary tunes water reabsorption in the tubules.", "Dialysis machines substitute for failed kidneys.", "Imbalance leads to kidney stones and renal failure."] },
  { topic: "Nervous Coordination", readMins: 8, updated: "1 week ago", points: ["A neuron: dendrites receive, the axon conducts, terminals transmit.", "Reflex arc: receptor → sensory neuron → CNS → motor neuron → effector.", "The CNS is the brain plus spinal cord; peripheral nerves connect the body.", "Cerebrum (thinking), cerebellum (balance) and medulla (involuntary control).", "Neurotransmitters carry the signal across synapses chemically.", "Reflexes skip the brain for speed — that is their protective value."] },
  { topic: "Chemical Coordination (Hormones)", readMins: 7, updated: "3 days ago", points: ["Endocrine glands release hormones directly into the blood.", "The pituitary is the master gland directing other glands.", "Insulin lowers blood glucose; glucagon raises it.", "Thyroxine sets the metabolic rate; iodine deficiency causes goitre.", "Adrenaline drives the fight-or-flight response.", "Negative feedback loops keep hormone levels steady."] },
  { topic: "Reproduction", readMins: 8, updated: "1 week ago", points: ["Asexual methods: binary fission, budding, spores and vegetative propagation.", "Sexual reproduction mixes genetic material — the variation advantage.", "Flower parts: stamen produces pollen; the carpel holds the ovule.", "Pollination is followed by fertilization, then seed and fruit formation.", "Human male: testes make sperm; female: ovaries make eggs, uterus nurtures.", "The menstrual cycle prepares the uterus for implantation."] },
  { topic: "Biotechnology", readMins: 7, updated: "2 weeks ago", points: ["Fermentation by yeast and bacteria makes bread, yogurt and cheese.", "Genetic engineering inserts genes — human insulin from bacteria.", "Single-cell protein and enzymes serve the food industry.", "Tissue culture clones whole plants from a few cells.", "Antibiotics such as penicillin come from fungi and bacteria.", "Ethics and biosafety govern all GMO releases."] },
  { topic: "Man & Environment", readMins: 7, updated: "3 weeks ago", points: ["An ecosystem is a biotic community plus its abiotic factors.", "Food chains and webs trace energy flow; pyramids shrink at each level.", "Carbon, nitrogen and water cycles recycle matter.", "Pollution of air, water and land — know sources and effects.", "Overpopulation and deforestation destroy habitats.", "Conservation tools: afforestation, recycling and protected areas."] },
];

const BIO_11: RealNote[] = [
  { topic: "Biological Molecules", readMins: 8, updated: "1 week ago", points: ["Carbon skeletons build the diversity of biomolecules.", "Carbohydrates: monosaccharides → disaccharides → polysaccharides.", "Proteins are amino-acid polymers with four levels of structure.", "Lipids: triglycerides for storage, phospholipids for membranes, steroids for signalling.", "Nucleic acids DNA and RNA store and express heredity.", "Water's polarity and hydrogen bonding make it life's solvent."] },
  { topic: "The Cell & Membrane Transport", readMins: 8, updated: "2 days ago", points: ["Fluid-mosaic model: a phospholipid bilayer studded with proteins.", "Diffusion moves particles down a gradient; osmosis moves water across a membrane.", "Facilitated diffusion uses channels; active transport spends ATP.", "Endocytosis and exocytosis move material in bulk.", "Plasmolysis in plant cells shows osmotic effects directly.", "Turgor pressure keeps plant cells firm."] },
  { topic: "Enzymes: Mode of Action & Factors", readMins: 7, updated: "1 week ago", points: ["Enzymes lower activation energy, speeding specific reactions.", "Active-site specificity is described by the induced-fit model.", "Temperature and pH optima flank denaturation limits.", "Competitive inhibitors block the active site; non-competitive bind elsewhere.", "Feedback inhibition regulates whole metabolic pathways.", "Coenzymes and cofactors assist many enzymes."] },
  { topic: "Acellular Life & Viruses", readMins: 7, updated: "2 weeks ago", points: ["Viruses: a nucleic acid core in a protein capsid — obligate parasites.", "Lytic versus lysogenic cycles in bacteriophages.", "Some viruses cause disease (influenza, HIV); vaccines protect against them.", "Viroids and prions are even simpler infectious agents.", "Bacteria lack a nucleus; classify by shape — coccus, bacillus, spirillum.", "Gram staining sorts bacteria into two broad groups."] },
  { topic: "Kingdom Plantae & Fungi", readMins: 8, updated: "3 days ago", points: ["Bryophytes (mosses) lack vascular tissue; tracheophytes have xylem and phloem.", "Ferns are vascular and reproduce by spores; seed plants dominate today.", "Gymnosperms bear naked seeds; angiosperms use flowers and fruits.", "Fungi have chitin walls and absorb food, living as saprophytes or parasites.", "Lichens pair a fungus with an alga in symbiosis.", "Alternation of generations runs through plant life cycles."] },
  { topic: "Bioenergetics: Photosynthesis & Respiration", readMins: 8, updated: "1 week ago", points: ["Photosynthesis pairs light reactions with the Calvin cycle.", "C₃, C₄ and CAM plants adapt to hot, dry climates.", "Respiration: glycolysis, link reaction, Krebs cycle, electron transport chain.", "Mitochondrion structure matches its energy role.", "Anaerobic branches: lactic acid or alcoholic fermentation.", "Chemosynthesis powers life without light at deep-sea vents."] },
];

const BIO_12: RealNote[] = [
  { topic: "DNA, Chromosomes & Genes", readMins: 8, updated: "2 days ago", points: ["DNA is a double helix: a sugar-phosphate backbone with paired bases inside.", "Base pairing A=T and G≡C follows Chargaff's rules.", "A gene is a DNA segment coding for a protein.", "The genome is the full set of genetic information.", "Semi-conservative replication copies DNA before every division.", "Central dogma: DNA → RNA → protein."] },
  { topic: "Cell Division: Mitosis & Meiosis", readMins: 8, updated: "1 week ago", points: ["Mitosis: one division → two identical diploid cells (growth and repair).", "Meiosis: two divisions → four haploid gametes (variation).", "Crossing over in prophase I recombines genes.", "Independent assortment randomizes chromosome distribution.", "Cancer is uncontrolled mitosis.", "Know the IPMAT stages and the events of each."] },
  { topic: "Mendelian Genetics", readMins: 8, updated: "3 days ago", points: ["Mendel's laws: segregation and independent assortment.", "Monohybrid ratio 3:1; dihybrid ratio 9:3:3:1.", "Genotype is the allele pair; phenotype is the visible outcome.", "A dominant allele masks its recessive partner in heterozygotes.", "A test-cross reveals an unknown genotype.", "Human cases: ABO blood groups show codominance and multiple alleles."] },
  { topic: "Human Reproduction & Development", readMins: 8, updated: "1 week ago", points: ["Gametogenesis: spermatogenesis in testes, oogenesis in ovaries.", "Fertilization restores the diploid number at conception.", "Early stages: cleavage → morula → blastocyst → gastrula.", "The placenta exchanges nutrients, gases and wastes.", "Identical twins come from one zygote; fraternal twins from two eggs.", "Development runs zygote → embryo → fetus → birth."] },
  { topic: "Nervous & Hormonal Coordination", readMins: 8, updated: "2 weeks ago", points: ["A nerve impulse is a wave of depolarization and repolarization.", "Saltatory conduction jumps between the nodes of myelinated axons.", "Synaptic transmission uses neurotransmitter vesicles.", "Autonomic system: sympathetic (fight-or-flight) versus parasympathetic (rest).", "The hypothalamus links nervous and endocrine control.", "Diabetes mellitus: insulin deficiency leaves blood glucose high."] },
  { topic: "Biotechnology & Genetic Engineering", readMins: 7, updated: "3 weeks ago", points: ["Recombinant DNA: restriction enzymes cut, ligase joins, plasmids carry.", "PCR amplifies DNA millions of times over.", "Gel electrophoresis sorts DNA fragments by size.", "Human insulin and growth hormone now come from modified bacteria.", "Gene therapy aims to correct defective genes.", "Cloning produced Dolly the sheep from a single udder cell."] },
];

/* ════════════════ COMPUTER SCIENCE ════════════════ */
const COMP_9: RealNote[] = [
  { topic: "Computer Hardware & Components", readMins: 6, updated: "1 week ago", points: ["The CPU = ALU + control unit + registers: the machine's brain.", "Input: keyboard, mouse, scanner; output: monitor, printer, speakers.", "Primary memory (RAM volatile, ROM permanent) versus secondary storage.", "The motherboard's buses connect all components.", "Storage units climb KB → MB → GB → TB, each ×1024.", "Hardware is physical; software is instructions."] },
  { topic: "Number Systems & Binary", readMins: 7, updated: "3 days ago", points: ["Binary (base 2) uses the digits 0 and 1 — computers are binary machines.", "Binary → decimal: add up the place values (1, 2, 4, 8…).", "Decimal → binary: divide by 2 repeatedly and read the remainders upward.", "Octal (base 8) and hexadecimal (base 16) compress binary neatly.", "1 nibble = 4 bits; 1 byte = 8 bits.", "Binary addition rule to remember: 1 + 1 = 10 (carry)."] },
  { topic: "Logic Gates & Boolean Algebra", readMins: 7, updated: "1 week ago", points: ["AND outputs 1 only when all inputs are 1; OR when any input is 1.", "NOT inverts; NAND and NOR are universal gates.", "Truth tables list every possible input combination.", "Boolean identities simplify logic expressions.", "De Morgan's laws: NOT(A AND B) = NOT A OR NOT B.", "Gates combine into adders, memory and whole processors."] },
  { topic: "Software & Operating Systems", readMins: 6, updated: "2 weeks ago", points: ["System software (OS, drivers) versus application software.", "OS roles: process, memory, file and device management plus the user interface.", "GUI (windows, icons) versus command-line interfaces.", "Common systems: Windows, Linux, macOS, Android.", "Install software only from trusted sources.", "Utilities: antivirus, backup and disk cleanup."] },
  { topic: "Computer Networks & Internet", readMins: 6, updated: "1 week ago", points: ["LAN covers a building; WAN spans cities or countries.", "Topologies: bus, star, ring and mesh.", "The Internet is a worldwide network of networks.", "The WWW, email and FTP are all internet services.", "Your ISP connects you; bandwidth measures speed in Mbps.", "Cyber ethics: respect privacy and intellectual property."] },
  { topic: "Programming Concepts", readMins: 7, updated: "3 days ago", points: ["An algorithm is a step-by-step solution plan.", "Flowcharts picture algorithms with standard symbols.", "Variables store data; constants never change.", "The three constructs: sequence, selection, repetition.", "Syntax errors stop a program; logic errors let it run wrongly.", "Testing with sample inputs validates any program."] },
];

const COMP_10: RealNote[] = [
  { topic: "Programming Fundamentals", readMins: 7, updated: "2 days ago", points: ["A program is an algorithm expressed in a programming language.", "Data types: integer, float, char, string and boolean.", "Variables are named memory boxes — declare them before use.", "Operators: arithmetic, relational and logical.", "Expressions follow precedence rules (parentheses first).", "Comments document code for human readers."] },
  { topic: "Conditional Statements", readMins: 7, updated: "1 week ago", points: ["if runs a block only when its condition is true.", "if/else chooses between two paths.", "Nested ifs handle multi-level decisions.", "switch/case dispatches on a single value.", "Relational operators compare; logical AND, OR, NOT combine.", "Trace code by hand with test values."] },
  { topic: "Loops & Iteration", readMins: 7, updated: "3 days ago", points: ["for loops suit known counts; while suits open-ended conditions.", "do-while runs its body at least once.", "Loop parts: initialization, condition, update.", "An infinite loop's condition never turns false — a classic bug.", "break exits a loop; continue skips to the next pass.", "Nested loops print tables and patterns."] },
  { topic: "Arrays, Strings & Functions", readMins: 8, updated: "1 week ago", points: ["Arrays store many values under one name, indexed from 0.", "Array length = number of elements; watch off-by-one errors.", "Strings are character arrays; common ops: length, concatenate, compare.", "Functions package reusable logic: inputs → output.", "Parameters carry data in; return sends a result back.", "Scope: local variables live only inside their function."] },
  { topic: "Databases Introduction", readMins: 6, updated: "2 weeks ago", points: ["A database is an organized data store; a DBMS manages it.", "Tables hold records (rows) and fields (columns).", "A primary key uniquely identifies each record.", "Queries retrieve filtered and sorted data (SQL SELECT).", "Forms enter data; reports present it.", "Backups protect against data loss."] },
  { topic: "Internet Services & Web", readMins: 6, updated: "1 week ago", points: ["Web pages (HTML) live on servers and reach you via browsers.", "A URL = protocol + domain + path.", "Search engines index the web by keywords.", "Email uses addresses and mail servers.", "Cloud computing delivers storage and apps online.", "Cyber safety: strong passwords and phishing awareness."] },
];

const COMP_INTER: RealNote[] = [
  { topic: "Programming Constructs & Data Types", readMins: 8, updated: "1 week ago", points: ["Strong versus weak typing; declare and initialize variables properly.", "Operators and expressions: precedence and associativity matter.", "Input/output with basic formatting.", "Core syntax essentials: statements, blocks and indentation.", "Follow identifier naming conventions.", "Debug systematically: print tracing, then breakpoints."] },
  { topic: "Control Structures & Modular Design", readMins: 8, updated: "2 days ago", points: ["Selection and iteration can express any algorithm.", "Modularity: decompose problems into functions and procedures.", "Parameter passing: by value versus by reference.", "Recursion: a function calling itself with a base case.", "Scope and lifetime of variables.", "Structured programming improves readability and reuse."] },
  { topic: "Arrays, Strings & Data Structures Basics", readMins: 8, updated: "1 week ago", points: ["1-D and 2-D arrays: traversal and searching.", "Linear search versus binary search (needs sorted data).", "Sorting: bubble, selection and insertion basics.", "String manipulation and standard library functions.", "Stacks (LIFO) and queues (FIFO) concepts.", "Big-O intuition for common operations."] },
  { topic: "Database Concepts & SQL", readMins: 8, updated: "3 days ago", points: ["The relational model: tables, keys and relationships.", "SQL core: SELECT, INSERT, UPDATE, DELETE.", "WHERE filters; ORDER BY sorts; JOIN combines tables.", "Normalization reduces redundancy.", "Primary and foreign keys enforce integrity.", "Indexes speed up lookups."] },
  { topic: "Operating Systems & System Software", readMins: 7, updated: "2 weeks ago", points: ["Process states: ready, running, blocked.", "Scheduling algorithms: FCFS, SJF, round robin.", "Memory management: paging and virtual memory.", "File systems organize persistent storage.", "Deadlock: its conditions and avoidance.", "Linux command-line basics."] },
  { topic: "Networking & Data Communication", readMins: 7, updated: "1 week ago", points: ["OSI and TCP/IP layered models.", "IP addressing and subnet masks.", "Switching versus routing; packets travel hop by hop.", "Transmission media: copper, fibre and wireless.", "Protocols: HTTP(S), FTP, SMTP and DNS.", "Security: firewalls, encryption and VPNs."] },
];

/* ════════════════ ENGLISH (shared across classes) ════════════════ */
const ENGLISH_ALL: RealNote[] = [
  { topic: "Grammar Foundations", readMins: 7, updated: "2 days ago", points: ["Parts of speech: noun, pronoun, verb, adjective, adverb, preposition, conjunction, interjection.", "Twelve tense forms: 3 times × 4 aspects — learn the formula for each.", "Subject-verb agreement: a singular subject takes a singular verb.", "Active-to-passive transformations must keep the tense intact.", "Punctuation: master the comma, semicolon and apostrophe with examples.", "Common confusions: its/it's, their/there, affect/effect."] },
  { topic: "Comprehension", readMins: 6, updated: "1 week ago", points: ["Skim first for the gist, then scan for details.", "Read the questions before re-reading the passage — targeted reading.", "Locate the question's key words inside the passage.", "Inference answers go beyond the literal text but stay defensible.", "Vocabulary in context: use the surrounding clues.", "Answer in complete sentences, staying within the passage facts."] },
  { topic: "Essay Writing", readMins: 8, updated: "3 days ago", points: ["Structure: introduction (hook + thesis), body paragraphs, conclusion.", "One idea per paragraph, led by a topic sentence.", "Essay types: narrative, descriptive, expository and argumentative.", "Brainstorm and outline before writing.", "Link ideas with transitions: furthermore, however, consequently.", "Reserve time to proofread grammar, spelling and coherence."] },
  { topic: "Précis Writing", readMins: 6, updated: "2 weeks ago", points: ["A précis compresses a passage to about one-third of its length.", "Three readings: theme, main points, then draft.", "Drop examples, repetitions and decorative language.", "Use reported speech and the third person.", "Write in your own words — never lift phrases.", "Finish with a title that captures the central idea."] },
  { topic: "Letter & Application Writing", readMins: 7, updated: "1 week ago", points: ["Letter parts: sender address, date, salutation, body, closing.", "Formal letters: to the point, respectful, one purpose only.", "Applications to the principal: state the request and reason clearly.", "Job applications mention or attach a CV.", "Informal letters warm up with personal touches.", "Match the tone and format to the audience."] },
  { topic: "Vocabulary Building", readMins: 5, updated: "3 days ago", points: ["Learn roots (port = carry), prefixes (pre-, un-) and suffixes (-able).", "Keep a personal word diary with your own sentences.", "Learn words in context and collocations, not in isolation.", "Synonyms and antonyms expand expressive range.", "One new word daily beats ten words weekly.", "Read widely — vocabulary grows by exposure."] },
];

/* ════════════════ URDU (shared across classes) ════════════════ */
const URDU_ALL: RealNote[] = [
  { topic: "نثر (Prose)", readMins: 6, updated: "1 week ago", points: ["نثر وہ تحریر ہے جو عام بول چال کے انداز میں لکھی جاتی ہے۔", "نثری اصناف: مضمون، افسانہ، سوانح عمری، خطوط اور خاکہ۔", "افسانہ مختصر کہانی ہے جس میں ایک مرکزی تاثر ہوتا ہے۔", "مضمون میں موضوع کو دلائل اور مثالوں سے واضح کیا جاتا ہے۔", "نثر پڑھتے وقت مرکزی خیال اور مصنف کے اسلوب کا جائزہ لیں۔", "مشہور نثر نگاروں کے نام اور ان کی تصانیف یاد رکھیں۔"] },
  { topic: "نظم (Poetry)", readMins: 6, updated: "3 days ago", points: ["نظم وہ شاعری ہے جس میں وزن، قافیہ اور ردیف کی پابندی ہوتی ہے۔", "اصنافِ سخن: غزل، نظم، مرثیہ، قصیدہ اور رباعی۔", "غزل کا ہر شعر اپنا الگ پیغام رکھ سکتا ہے۔", "مصرع، بیت، ردیف اور قافیے کی پہچان سیکھیں۔", "اقبال، فیض اور احمد فراز کے مشہور اشعار یاد کریں۔", "تشبیہ، استعارہ اور تلمیح کے استعمال کو پہچانیں۔"] },
  { topic: "قواعد (Grammar)", readMins: 7, updated: "1 week ago", points: ["اردو جملے کی تین بنیادی قسمیں: اسم، فعل اور حرف۔", "اسم کی اقسام: ذات، صفت، اشارہ اور ضمیر۔", "فعل کی اقسام: ماضی، حال اور مستقبل کی پہچان سیکھیں۔", "جملے میں فاعل، مفعول، مبتدا اور خبر کی تفریق کریں۔", "واحد جمع اور مذکر مونث کے قواعد مشق کریں۔", "املا اور رموزِ اوقاف (۔ ، ؟ !) کی درستی یاد رکھیں۔"] },
  { topic: "خط و درخواست (Letters)", readMins: 6, updated: "2 weeks ago", points: ["خط کے حصے: تاریخ، مخاطب، جسمِ مضمون اور اختتام۔", "سرکاری درخواست مختصر، واضح اور مؤدبانہ ہوتی ہے۔", "ذاتی خط میں مخاطب کے مزاج کے مطابق لہجہ اختیار کریں۔", "درخواست میں وجہ واضح بیان کریں۔", "چھٹی، فیس اور معافی کی درخواست کے نمونے مشق کریں۔", "خط لکھنے کے آداب اور سادہ زبان استعمال کریں۔"] },
  { topic: "مضمون نویسی (Essay Writing)", readMins: 7, updated: "3 days ago", points: ["مضمون کے حصے: تمہید، جسمِ مضمون اور نتیجہ۔", "تمہید میں موضوع کا دلچسپ تعارف دیں۔", "ہر پیراگراف میں ایک مرکزی نکتہ بیان کریں۔", "دلائل، حوالے اور مثالیں مضمون کو مضبوط بناتی ہیں۔", "نتیجے میں پوری گفتگو کا خلاصہ پیش کریں۔", "مشہور مضامین مشق کریں: میرا وطن، سائنس کے کرشمے، صبح کی سیر۔"] },
  { topic: "تلخیص (Summary)", readMins: 6, updated: "1 week ago", points: ["تلخیص اصل عبارت کا مختصر خلاصہ ہوتی ہے۔", "پہلی بار پڑھ کر مرکزی خیال معلوم کریں۔", "غیر ضروری جملے، مثالیں اور تکرار حذف کریں۔", "تلخیص اپنے الفاظ میں لکھیں، نقل نہ کریں۔", "عام طور پر ایک تہائی لمبائی مناسب رہتی ہے۔", "آخر میں مرکزی خیال کے مطابق عنوان دیں۔"] },
];

/* ── Lookup: class-specific first, then subject-level ─────────────────────── */
export const REAL_NOTES: Record<string, RealNote[]> = {
  "math-9": MATH_9, "math-10": MATH_10, "math-11": MATH_11, "math-12": MATH_12,
  "physics-9": PHYSICS_9, "physics-10": PHYSICS_10, "physics-11": PHYSICS_11, "physics-12": PHYSICS_12,
  "chemistry-9": CHEM_9, "chemistry-10": CHEM_10, "chemistry-11": CHEM_11, "chemistry-12": CHEM_12,
  "biology-9": BIO_9, "biology-10": BIO_10, "biology-11": BIO_11, "biology-12": BIO_12,
  "computer-9": COMP_9, "computer-10": COMP_10, "computer-11": COMP_INTER, "computer-12": COMP_INTER,
  "english": ENGLISH_ALL,
  "urdu": URDU_ALL,
};

/** Best available notes for a subject + class: class-specific set first,
    falling back to the shared subject set (English/Urdu). */
export function getRealNotes(subject: SubjectId, classId: string): RealNote[] {
  return REAL_NOTES[`${subject}-${classId}`] ?? REAL_NOTES[subject] ?? [];
}
