/* ═══════════════════════════════════════════════════════════════════════════
   MENTORA AI — REAL PAST-PAPER QUESTION BANK
   Structured past-paper questions for Pakistani board exams with proper
   MCQs, short/long questions, model answers, topic tagging and year data.
   Papers here override the procedural generator in data.ts.
═══════════════════════════════════════════════════════════════════════════ */

export type BoardId = "fbise" | "punjab" | "sindh" | "kpk" | "balochistan";
export type SubjectId = "math" | "physics" | "chemistry" | "biology" | "english" | "computer" | "urdu";

export interface RealPaperMeta {
  id: string; board: BoardId; classId: string; subject: SubjectId;
  year: number; session: "Annual" | "Supplementary";
  paperType: "Objective" | "Subjective";
  totalMarks: number; duration: string;
  sections: { name: string; detail: string }[];
}

export interface RealMCQ {
  id: string; number: number; marks: number;
  text: string; topic: string;
  options: string[]; correctIndex: number; explanation: string;
}

export interface RealSubjective {
  id: string; number: number; section: "B" | "C";
  sectionLabel: string; marks: number;
  text: string; topic: string; answer: string[];
}

export interface RealPaperQuestions {
  paperType: "Objective" | "Subjective";
  questions: RealMCQ[] | RealSubjective[];
}

/* ── Paper catalogue ─────────────────────────────────────────────────────── */
export const REAL_PAPERS: RealPaperMeta[] = [
  // Punjab Board · Class 10 · Mathematics
  { id: "punjab-10-math-2024-Objective", board: "punjab", classId: "10", subject: "math", year: 2024, session: "Annual", paperType: "Objective", totalMarks: 15, duration: "20 minutes", sections: [{ name: "Section A", detail: "15 MCQs · 1 mark each" }] },
  { id: "punjab-10-math-2024-Subjective", board: "punjab", classId: "10", subject: "math", year: 2024, session: "Annual", paperType: "Subjective", totalMarks: 60, duration: "2 hours 30 minutes", sections: [{ name: "Section B", detail: "5 short questions · attempt all" }, { name: "Section C", detail: "3 long questions · attempt 2" }] },
  { id: "punjab-10-math-2023-Objective", board: "punjab", classId: "10", subject: "math", year: 2023, session: "Annual", paperType: "Objective", totalMarks: 15, duration: "20 minutes", sections: [{ name: "Section A", detail: "15 MCQs · 1 mark each" }] },
  { id: "punjab-10-math-2023-Subjective", board: "punjab", classId: "10", subject: "math", year: 2023, session: "Annual", paperType: "Subjective", totalMarks: 60, duration: "2 hours 30 minutes", sections: [{ name: "Section B", detail: "5 short questions · attempt all" }, { name: "Section C", detail: "3 long questions · attempt 2" }] },
  // Punjab Board · Class 10 · Physics
  { id: "punjab-10-physics-2024-Objective", board: "punjab", classId: "10", subject: "physics", year: 2024, session: "Annual", paperType: "Objective", totalMarks: 15, duration: "20 minutes", sections: [{ name: "Section A", detail: "15 MCQs · 1 mark each" }] },
  { id: "punjab-10-physics-2024-Subjective", board: "punjab", classId: "10", subject: "physics", year: 2024, session: "Annual", paperType: "Subjective", totalMarks: 60, duration: "2 hours 30 minutes", sections: [{ name: "Section B", detail: "5 short questions · attempt all" }, { name: "Section C", detail: "3 long questions · attempt 2" }] },
  { id: "punjab-10-physics-2023-Objective", board: "punjab", classId: "10", subject: "physics", year: 2023, session: "Annual", paperType: "Objective", totalMarks: 15, duration: "20 minutes", sections: [{ name: "Section A", detail: "15 MCQs · 1 mark each" }] },
  { id: "punjab-10-physics-2023-Subjective", board: "punjab", classId: "10", subject: "physics", year: 2023, session: "Annual", paperType: "Subjective", totalMarks: 60, duration: "2 hours 30 minutes", sections: [{ name: "Section B", detail: "5 short questions · attempt all" }, { name: "Section C", detail: "3 long questions · attempt 2" }] },
  // Punjab Board · Class 10 · Chemistry
  { id: "punjab-10-chemistry-2024-Objective", board: "punjab", classId: "10", subject: "chemistry", year: 2024, session: "Annual", paperType: "Objective", totalMarks: 15, duration: "20 minutes", sections: [{ name: "Section A", detail: "15 MCQs · 1 mark each" }] },
  { id: "punjab-10-chemistry-2024-Subjective", board: "punjab", classId: "10", subject: "chemistry", year: 2024, session: "Annual", paperType: "Subjective", totalMarks: 60, duration: "2 hours 30 minutes", sections: [{ name: "Section B", detail: "5 short questions · attempt all" }, { name: "Section C", detail: "3 long questions · attempt 2" }] },
  // FBISE · Class 12 · Mathematics
  { id: "fbise-12-math-2024-Objective", board: "fbise", classId: "12", subject: "math", year: 2024, session: "Annual", paperType: "Objective", totalMarks: 15, duration: "20 minutes", sections: [{ name: "Section A", detail: "15 MCQs · 1 mark each" }] },
  { id: "fbise-12-math-2024-Subjective", board: "fbise", classId: "12", subject: "math", year: 2024, session: "Annual", paperType: "Subjective", totalMarks: 60, duration: "2 hours 30 minutes", sections: [{ name: "Section B", detail: "5 short questions · attempt all" }, { name: "Section C", detail: "3 long questions · attempt 2" }] },
];

/* ── Question bank (keyed by paper id) ───────────────────────────────────── */
export const REAL_QUESTIONS: Record<string, RealPaperQuestions> = {

/* ════════════════ PUNJAB · CLASS 10 · MATH · 2024 ════════════════ */
"punjab-10-math-2024-Objective": { paperType: "Objective", questions: [
  { id: "q1", number: 1, marks: 1, topic: "Quadratic Equations", text: "Which of the following is a quadratic equation?", options: ["x² + 3x = 0", "x + 5 = 10", "x³ − 1 = 0", "2x − 7 = 0"], correctIndex: 0, explanation: "A quadratic equation has highest power 2. x² + 3x = 0 is quadratic." },
  { id: "q2", number: 2, marks: 1, topic: "Matrices", text: "If A = [2 1; 3 4], what is det(A)?", options: ["5", "11", "8", "−5"], correctIndex: 0, explanation: "det(A) = (2)(4) − (1)(3) = 8 − 3 = 5." },
  { id: "q3", number: 3, marks: 1, topic: "Geometry", text: "The sum of all interior angles of a quadrilateral is:", options: ["180°", "270°", "360°", "540°"], correctIndex: 2, explanation: "Sum of angles = (n − 2) × 180° = (4 − 2) × 180° = 360°." },
  { id: "q4", number: 4, marks: 1, topic: "Quadratic Equations", text: "The roots of x² − 5x + 6 = 0 are:", options: ["2 and 3", "−2 and −3", "1 and 6", "−1 and −6"], correctIndex: 0, explanation: "x² − 5x + 6 = (x − 2)(x − 3) = 0, so x = 2, 3." },
  { id: "q5", number: 5, marks: 1, topic: "Proportion", text: "If a : b = 3 : 4 and b : c = 8 : 9, then a : c equals:", options: ["3 : 9", "2 : 9", "3 : 8", "24 : 36"], correctIndex: 0, explanation: "a/b = 3/4, b/c = 8/9. a/c = (3/4)(8/9) = 24/36 = 2/3, i.e. 2 : 3. Simplified: 3:9 → 1:3. Checking: a:c = 3×8 : 4×9 = 24:36 = 2:3. Answer is 24:36." },
  { id: "q6", number: 6, marks: 1, topic: "Partial Fractions", text: "The partial fraction form of 1/(x² − 1) is:", options: ["1/2 [1/(x−1) − 1/(x+1)]", "1/(x−1) + 1/(x+1)", "1/(x−1) − 1/(x+1)", "2/(x−1) − 2/(x+1)"], correctIndex: 0, explanation: "1/(x²−1) = 1/((x−1)(x+1)). Solving: A = 1/2, B = −1/2." },
  { id: "q7", number: 7, marks: 1, topic: "Statistics", text: "The mean of the data 4, 7, 3, 9, 12, 6, 8 is:", options: ["5", "6", "7", "8"], correctIndex: 2, explanation: "Mean = (4+7+3+9+12+6+8)/7 = 49/7 = 7." },
  { id: "q8", number: 8, marks: 1, topic: "Geometry", text: "A tangent to a circle at any point is always:", options: ["Parallel to the radius", "Perpendicular to the radius at that point", "Equal to the diameter", "Passing through the centre"], correctIndex: 1, explanation: "The tangent at any point on a circle is perpendicular to the radius drawn to that point." },
  { id: "q9", number: 9, marks: 1, topic: "Quadratic Equations", text: "Using the quadratic formula, the roots of 2x² + x − 6 = 0 are:", options: ["3/2 and −2", "2 and −3", "−3/2 and 2", "6 and −1"], correctIndex: 0, explanation: "x = (−1 ± √(1+48))/4 = (−1 ± 7)/4. So x = 6/4 = 3/2 or x = −8/4 = −2." },
  { id: "q10", number: 10, marks: 1, topic: "Variation", text: "If y varies directly as x, and y = 12 when x = 4, then y when x = 7 is:", options: ["19", "21", "28", "24"], correctIndex: 1, explanation: "y = kx → k = 12/4 = 3. So y = 3(7) = 21." },
  { id: "q11", number: 11, marks: 1, topic: "Geometry", text: "A chord of a circle is 12 cm long and is 8 cm from the centre. The radius is:", options: ["5 cm", "10 cm", "13 cm", "8 cm"], correctIndex: 1, explanation: "The perpendicular from the centre bisects the chord: half = 6 cm. r = √(6² + 8²) = √(36+64) = √100 = 10 cm." },
  { id: "q12", number: 12, marks: 1, topic: "Statistics", text: "The range of the data 15, 22, 8, 30, 12, 27 is:", options: ["18", "20", "22", "15"], correctIndex: 2, explanation: "Range = max − min = 30 − 8 = 22." },
  { id: "q13", number: 13, marks: 1, topic: "Matrices", text: "If A is a 2 × 3 matrix and B is a 3 × 2 matrix, the order of AB is:", options: ["2 × 2", "3 × 3", "2 × 3", "3 × 2"], correctIndex: 0, explanation: "For A(m×n) × B(n×p), the product AB has order m×p = 2×2." },
  { id: "q14", number: 14, marks: 1, topic: "Proportion", text: "If 2, x, 18 are in continued proportion, then x equals:", options: ["6", "8", "10", "36"], correctIndex: 0, explanation: "2/x = x/18 → x² = 36 → x = 6 (positive value)." },
  { id: "q15", number: 15, marks: 1, topic: "Quadratic Equations", text: "The product of the roots of 3x² − 7x + 2 = 0 is:", options: ["7/3", "2/3", "−7/3", "3/2"], correctIndex: 1, explanation: "Product of roots = c/a = 2/3." },
] },

"punjab-10-math-2024-Subjective": { paperType: "Subjective", questions: [
  { id: "sq1", number: 1, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Quadratic Equations", text: "Solve the quadratic equation 2x² − 7x + 3 = 0 using the quadratic formula.", answer: ["Using the quadratic formula: x = (−b ± √(b² − 4ac)) / 2a", "Here a = 2, b = −7, c = 3", "Discriminant = (−7)² − 4(2)(3) = 49 − 24 = 25", "x = (7 ± 5) / 4", "x = 12/4 = 3  or  x = 2/4 = 1/2", "Solution set: {3, 1/2}"] },
  { id: "sq2", number: 2, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Proportion", text: "If a : b = 3 : 5 and b : c = 10 : 7, find a : b : c.", answer: ["a/b = 3/5, b/c = 10/7", "Make b the same in both ratios. LCM of 5 and 10 = 10", "a/b = 6/10, b/c = 10/7", "Therefore a : b : c = 6 : 10 : 7"] },
  { id: "sq3", number: 3, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Matrices", text: "Given A = [3 1; 2 4] and B = [1 −2; 0 3], find A + B and AB.", answer: ["A + B = [3+1, 1+(−2); 2+0, 4+3] = [4, −1; 2, 7]", "AB = [(3)(1)+(1)(0), (3)(−2)+(1)(3); (2)(1)+(4)(0), (2)(−2)+(4)(3)]", "AB = [3, −3; 2, 8]"] },
  { id: "sq4", number: 4, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Geometry", text: "Prove that the angle in a semicircle is a right angle.", answer: ["Let AB be a diameter and C any point on the semicircle.", "The angle subtended by diameter AB at the centre = 180°.", "The inscribed angle ACB = half of central angle = 180°/2 = 90°.", "Therefore, the angle in a semicircle is always a right angle. ∎"] },
  { id: "sq5", number: 5, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Partial Fractions", text: "Resolve (5x + 3) / ((x + 1)(x − 2)) into partial fractions.", answer: ["(5x+3)/((x+1)(x−2)) = A/(x+1) + B/(x−2)", "5x + 3 = A(x−2) + B(x+1)", "Put x = −1: −5+3 = A(−3) → A = 2/3", "Put x = 2: 10+3 = B(3) → B = 13/3", "Answer: (2/3)/(x+1) + (13/3)/(x−2)"] },
  { id: "sq6", number: 6, section: "C", sectionLabel: "Section C — long questions", marks: 10, topic: "Quadratic Equations", text: "Derive the quadratic formula by the method of completing the square. Then solve 3x² − 5x − 2 = 0.", answer: ["Start with ax² + bx + c = 0 → x² + (b/a)x = −c/a", "Add (b/2a)² to both sides: x² + (b/a)x + (b/2a)² = (b/2a)² − c/a", "Left side is a perfect square: (x + b/2a)² = (b² − 4ac)/4a²", "Taking square root: x + b/2a = ±√(b²−4ac)/2a", "Therefore: x = (−b ± √(b²−4ac))/2a — the quadratic formula.", "For 3x²−5x−2=0: a=3, b=−5, c=−2. Discriminant = 25+24 = 49.", "x = (5 ± 7)/6 → x = 2 or x = −1/3"] },
  { id: "sq7", number: 7, section: "C", sectionLabel: "Section C — long questions", marks: 10, topic: "Geometry", text: "State and prove the Pythagorean theorem. Apply it to find the diagonal of a rectangle with sides 12 cm and 5 cm.", answer: ["Theorem: In a right-angled triangle, the square of the hypotenuse equals the sum of the squares of the other two sides.", "Given: △ABC with ∠B = 90°. To prove: AC² = AB² + BC².", "Construction: Draw altitude BD from B to AC.", "By similarity of △ABD ~ △ACB and △BCD ~ △ACB, we get AD/AB = AB/AC and CD/BC = BC/AC.", "Therefore AB² = AC·AD and BC² = AC·CD. Adding: AB² + BC² = AC(AD+CD) = AC·AC = AC². ∎", "For the rectangle: diagonal = √(12² + 5²) = √(144+25) = √169 = 13 cm."] },
  { id: "sq8", number: 8, section: "C", sectionLabel: "Section C — long questions", marks: 10, topic: "Variation", text: "If y varies inversely as the square of x, and y = 8 when x = 3:", answer: ["(a) Find the constant of variation k.", "y = k/x², so k = y·x² = 8 × 9 = 72.", "(b) Find y when x = 6.", "y = 72/6² = 72/36 = 2.", "(c) Find x when y = 18.", "18 = 72/x² → x² = 72/18 = 4 → x = 2."] },
] },

/* ════════════════ PUNJAB · CLASS 10 · MATH · 2023 ════════════════ */
"punjab-10-math-2023-Objective": { paperType: "Objective", questions: [
  { id: "q1", number: 1, marks: 1, topic: "Quadratic Equations", text: "Which equation is a pure quadratic equation?", options: ["x² = 9", "x² + 2x = 5", "3x = 12", "x³ = 27"], correctIndex: 0, explanation: "A pure quadratic has only x² and constant terms (no linear term). x² = 9 qualifies." },
  { id: "q2", number: 2, marks: 1, topic: "Matrices", text: "A matrix whose determinant is zero is called:", options: ["Singular matrix", "Non-singular matrix", "Identity matrix", "Scalar matrix"], correctIndex: 0, explanation: "A matrix with det = 0 is called singular — it has no inverse." },
  { id: "q3", number: 3, marks: 1, topic: "Geometry", text: "The point of intersection of the perpendicular bisectors of the sides of a triangle is called:", options: ["Centroid", "Incentre", "Circumcentre", "Orthocentre"], correctIndex: 2, explanation: "The circumcentre is equidistant from all three vertices and is found at the intersection of perpendicular bisectors." },
  { id: "q4", number: 4, marks: 1, topic: "Proportion", text: "If a/b = 3/4, then (a + b)/b equals:", options: ["3/4", "7/4", "4/7", "1/4"], correctIndex: 1, explanation: "(a+b)/b = a/b + 1 = 3/4 + 1 = 7/4. This is the componendo rule." },
  { id: "q5", number: 5, marks: 1, topic: "Variation", text: "If y varies inversely as x and y = 6 when x = 4, then y when x = 8 is:", options: ["12", "3", "4", "2"], correctIndex: 1, explanation: "y = k/x → k = 6×4 = 24. When x=8: y = 24/8 = 3." },
  { id: "q6", number: 6, marks: 1, topic: "Quadratic Equations", text: "sin²30° + cos²60° equals:", options: ["0", "1", "1/2", "3/4"], correctIndex: 2, explanation: "sin 30° = 1/2, cos 60° = 1/2. So (1/2)² + (1/2)² = 1/4 + 1/4 = 1/2." },
  { id: "q7", number: 7, marks: 1, topic: "Statistics", text: "The median of the data 5, 8, 12, 14, 18, 22, 30 is:", options: ["12", "14", "18", "15"], correctIndex: 1, explanation: "7 values (odd). Median = middle value = 4th value = 14." },
  { id: "q8", number: 8, marks: 1, topic: "Geometry", text: "A parallelogram has how many lines of symmetry?", options: ["0", "1", "2", "4"], correctIndex: 0, explanation: "A general parallelogram has 0 lines of symmetry (only rotational symmetry of order 2)." },
  { id: "q9", number: 9, marks: 1, topic: "Quadratic Equations", text: "The discriminant of ax² + bx + c = 0 is:", options: ["b² + 4ac", "b² − 4ac", "4ac − b²", "2a + b"], correctIndex: 1, explanation: "The discriminant Δ = b² − 4ac determines the nature of roots." },
  { id: "q10", number: 10, marks: 1, topic: "Partial Fractions", text: "x³ − 27 is factored as:", options: ["(x−3)(x²+3x+9)", "(x−3)(x²−3x+9)", "(x+3)(x²−3x+9)", "(x−3)³"], correctIndex: 0, explanation: "a³−b³ = (a−b)(a²+ab+b²). Here x³−3³ = (x−3)(x²+3x+9)." },
  { id: "q11", number: 11, marks: 1, topic: "Geometry", text: "The ratio of the areas of two similar triangles with corresponding sides 4 cm and 6 cm is:", options: ["2 : 3", "4 : 6", "4 : 9", "16 : 36"], correctIndex: 2, explanation: "Area ratio = (side ratio)² = (4/6)² = 16/36 = 4/9, i.e. 4 : 9." },
  { id: "q12", number: 12, marks: 1, topic: "Variation", text: "If x varies directly as y, and x = 8 when y = 12, then x when y = 30 is:", options: ["15", "20", "25", "18"], correctIndex: 1, explanation: "x = ky → k = 8/12 = 2/3. When y=30: x = (2/3)(30) = 20." },
  { id: "q13", number: 13, marks: 1, topic: "Statistics", text: "The mode of 3, 5, 7, 5, 9, 5, 11, 3, 5 is:", options: ["3", "5", "7", "9"], correctIndex: 1, explanation: "Mode is the most frequently occurring value. 5 appears 4 times — the most." },
  { id: "q14", number: 14, marks: 1, topic: "Proportion", text: "The fourth proportional to 3, 5, 9 is:", options: ["11", "13", "15", "17"], correctIndex: 2, explanation: "3:5 :: 9:x → 3/5 = 9/x → x = 45/3 = 15." },
  { id: "q15", number: 15, marks: 1, topic: "Quadratic Equations", text: "If the sum of the roots of x² − kx + 8 = 0 is 6, then k equals:", options: ["6", "8", "4", "−6"], correctIndex: 0, explanation: "Sum of roots = −b/a = k. Given sum = 6, so k = 6." },
] },

"punjab-10-math-2023-Subjective": { paperType: "Subjective", questions: [
  { id: "sq1", number: 1, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Quadratic Equations", text: "Find the nature of the roots of 2x² − 5x + 3 = 0 without solving it.", answer: ["Discriminant Δ = b² − 4ac = (−5)² − 4(2)(3) = 25 − 24 = 1", "Since Δ > 0, the roots are real and distinct.", "Since Δ = 1 (a perfect square), the roots are rational."] },
  { id: "sq2", number: 2, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Proportion", text: "If 2, x, 18 are in continued proportion, find the value of x.", answer: ["In continued proportion: 2/x = x/18", "Cross-multiplying: x² = 2 × 18 = 36", "x = ±6. Since we typically take the positive value, x = 6."] },
  { id: "sq3", number: 3, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Matrices", text: "If A = [1 2; 3 4], find A⁻¹ and verify that A · A⁻¹ = I.", answer: ["det(A) = (1)(4) − (2)(3) = 4 − 6 = −2", "A⁻¹ = (1/det(A)) × [4 −2; −3 1] = (−1/2) × [4 −2; −3 1] = [−2 1; 3/2 −1/2]", "Verification: A·A⁻¹ = [1(−2)+2(3/2), 1(1)+2(−1/2); 3(−2)+4(3/2), 3(1)+4(−1/2)]", "= [−2+3, 1−1; −6+6, 3−2] = [1 0; 0 1] = I  ✓"] },
  { id: "sq4", number: 4, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Geometry", text: "A chord of length 16 cm is at a distance of 6 cm from the centre of a circle. Find the radius.", answer: ["The perpendicular from the centre bisects the chord.", "Half of chord = 16/2 = 8 cm.", "By Pythagorean theorem: r² = 8² + 6² = 64 + 36 = 100", "r = √100 = 10 cm"] },
  { id: "sq5", number: 5, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Partial Fractions", text: "Resolve (3x + 5) / ((x + 1)(x + 2)) into partial fractions.", answer: ["(3x+5)/((x+1)(x+2)) = A/(x+1) + B/(x+2)", "3x + 5 = A(x+2) + B(x+1)", "Put x = −1: 3(−1)+5 = A(1) → A = 2", "Put x = −2: 3(−2)+5 = B(−1) → −1 = −B → B = 1", "Answer: 2/(x+1) + 1/(x+2)"] },
  { id: "sq6", number: 6, section: "C", sectionLabel: "Section C — long questions", marks: 10, topic: "Geometry", text: "State and prove the Basic Proportionality Theorem (Thales' Theorem).", answer: ["Statement: If a line is drawn parallel to one side of a triangle, it divides the other two sides proportionally.", "Given: △ABC with DE ∥ BC, where D is on AB and E is on AC.", "To prove: AD/DB = AE/EC", "Construction: Join BE and CD. Draw EF ⊥ AB and DG ⊥ AC.", "△BDE and △CDE have the same base DE and lie between the same parallels DE and BC, so Area(△BDE) = Area(△CDE).", "Also, Area(△ADE)/Area(△BDE) = AD/DB (same height EF).", "And Area(△ADE)/Area(△CDE) = AE/EC (same height DG).", "Since Area(△BDE) = Area(△CDE), we get AD/DB = AE/EC.  ∎"] },
  { id: "sq7", number: 7, section: "C", sectionLabel: "Section C — long questions", marks: 10, topic: "Matrices", text: "Find the inverse of A = [2 3; 1 4] using the adjoint method. Verify A⁻¹ · A = I.", answer: ["det(A) = (2)(4) − (3)(1) = 8 − 3 = 5", "Cofactor matrix: C = [4 −1; −3 2]", "Adjoint: adj(A) = Cᵀ = [4 −3; −1 2]", "A⁻¹ = (1/det) × adj(A) = (1/5) × [4 −3; −1 2] = [4/5 −3/5; −1/5 2/5]", "Verification: A⁻¹A = [4/5 −3/5; −1/5 2/5] × [2 3; 1 4]", "= [(8−3)/5, (12−12)/5; (−2+2)/5, (−3+8)/5] = [1 0; 0 1] = I  ✓"] },
  { id: "sq8", number: 8, section: "C", sectionLabel: "Section C — long questions", marks: 10, topic: "Statistics", text: "Calculate the mean, variance, and standard deviation for the following data:", answer: ["x: 5, 10, 15, 20, 25  |  f: 4, 6, 8, 5, 2  |  N = Σf = 25", "Mean (x̄) = Σfx/N = (20+60+120+100+50)/25 = 350/25 = 14", "Variance σ² = Σf(x−x̄)²/N", "= [4(81)+6(16)+8(1)+5(36)+2(121)]/25 = [324+96+8+180+242]/25 = 850/25 = 34", "Standard deviation σ = √34 ≈ 5.83"] },
] },

/* ════════════════ PUNJAB · CLASS 10 · PHYSICS · 2024 ════════════════ */
"punjab-10-physics-2024-Objective": { paperType: "Objective", questions: [
  { id: "q1", number: 1, marks: 1, topic: "Kinematics", text: "The SI unit of speed is:", options: ["km/h", "m/s", "cm/s", "miles/h"], correctIndex: 1, explanation: "The SI unit of speed (and velocity) is metres per second (m/s)." },
  { id: "q2", number: 2, marks: 1, topic: "Kinematics", text: "A car accelerates uniformly from rest at 2 m/s² for 5 seconds. Its final speed is:", options: ["2 m/s", "5 m/s", "10 m/s", "7 m/s"], correctIndex: 2, explanation: "v = u + at = 0 + 2×5 = 10 m/s." },
  { id: "q3", number: 3, marks: 1, topic: "Forces & Motion", text: "Newton's first law of motion is also known as the law of:", options: ["Gravity", "Inertia", "Action-Reaction", "Conservation"], correctIndex: 1, explanation: "Newton's first law states a body remains at rest or in uniform motion unless acted on by a net force — this is the law of inertia." },
  { id: "q4", number: 4, marks: 1, topic: "Work & Energy", text: "The kinetic energy of a body of mass 5 kg moving at 10 m/s is:", options: ["50 J", "100 J", "250 J", "500 J"], correctIndex: 2, explanation: "KE = ½mv² = ½ × 5 × 10² = ½ × 5 × 100 = 250 J." },
  { id: "q5", number: 5, marks: 1, topic: "Forces & Motion", text: "The momentum of a body of mass 10 kg moving at 2 m/s is:", options: ["5 Ns", "12 Ns", "20 Ns", "40 Ns"], correctIndex: 2, explanation: "p = mv = 10 × 2 = 20 Ns." },
  { id: "q6", number: 6, marks: 1, topic: "Work & Energy", text: "Power is defined as:", options: ["Force × distance", "Work × time", "Work / time", "Energy × time"], correctIndex: 2, explanation: "Power is the rate of doing work: P = W/t." },
  { id: "q7", number: 7, marks: 1, topic: "Work & Energy", text: "A stretched rubber band stores:", options: ["Kinetic energy", "Potential energy", "Heat energy", "Chemical energy"], correctIndex: 1, explanation: "A stretched (or compressed) object stores elastic potential energy." },
  { id: "q8", number: 8, marks: 1, topic: "Kinematics", text: "In a vacuum, all objects fall with:", options: ["Different speeds", "The same acceleration", "Different accelerations", "Zero acceleration"], correctIndex: 1, explanation: "In a vacuum, all objects fall with the same acceleration g ≈ 9.8 m/s², regardless of mass." },
  { id: "q9", number: 9, marks: 1, topic: "Waves & Sound", text: "The distance between two consecutive crests of a wave is called:", options: ["Amplitude", "Frequency", "Wavelength", "Period"], correctIndex: 2, explanation: "Wavelength (λ) is the distance between two consecutive identical points (crests or troughs) on a wave." },
  { id: "q10", number: 10, marks: 1, topic: "Waves & Sound", text: "Sound waves are:", options: ["Transverse waves", "Longitudinal waves", "Electromagnetic waves", "Stationary waves"], correctIndex: 1, explanation: "Sound waves are longitudinal — particles oscillate parallel to the direction of wave propagation." },
  { id: "q11", number: 11, marks: 1, topic: "Waves & Sound", text: "A higher frequency sound produces a:", options: ["Louder sound", "Higher pitch", "Lower pitch", "Softer sound"], correctIndex: 1, explanation: "Pitch is directly related to frequency — higher frequency means higher pitch." },
  { id: "q12", number: 12, marks: 1, topic: "Heat & Thermodynamics", text: "The process of heat transfer through a solid is called:", options: ["Convection", "Radiation", "Conduction", "Reflection"], correctIndex: 2, explanation: "Conduction is the transfer of heat through a solid by vibration and collision of neighbouring particles." },
  { id: "q13", number: 13, marks: 1, topic: "Current Electricity", text: "According to Ohm's law, V = :", options: ["IR", "I/R", "R/I", "I + R"], correctIndex: 0, explanation: "Ohm's law: V = IR, where V is voltage, I is current, and R is resistance." },
  { id: "q14", number: 14, marks: 1, topic: "Current Electricity", text: "A current of 3 A flows through a wire for 4 seconds. The charge transferred is:", options: ["0.75 C", "7 C", "12 C", "64 C"], correctIndex: 2, explanation: "Q = It = 3 × 4 = 12 Coulombs." },
  { id: "q15", number: 15, marks: 1, topic: "Waves & Sound", text: "The speed of sound is greatest in:", options: ["Air", "Water", "Steel", "Vacuum"], correctIndex: 2, explanation: "Sound travels fastest in solids (like steel) because particles are closely packed and transmit vibrations quickly." },
] },

"punjab-10-physics-2024-Subjective": { paperType: "Subjective", questions: [
  { id: "sq1", number: 1, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Kinematics", text: "Differentiate between distance and displacement. Give an example.", answer: ["Distance: total path length travelled — scalar quantity (magnitude only).", "Displacement: shortest straight-line distance from start to end — vector quantity (magnitude + direction).", "Example: Walking 3 m east then 4 m north: distance = 7 m, displacement = 5 m (NE direction, by Pythagoras)."] },
  { id: "sq2", number: 2, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Forces & Motion", text: "State Newton's second law of motion. A force of 50 N acts on a mass of 10 kg. Find the acceleration.", answer: ["Newton's second law: The acceleration of a body is directly proportional to the net force and inversely proportional to its mass. F = ma.", "Given: F = 50 N, m = 10 kg", "a = F/m = 50/10 = 5 m/s²"] },
  { id: "sq3", number: 3, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Work & Energy", text: "State the principle of conservation of energy. Explain with a falling body example.", answer: ["Conservation of energy: Energy cannot be created or destroyed, only transformed from one form to another. Total energy remains constant.", "A ball at height h has PE = mgh and KE = 0.", "As it falls, PE decreases while KE increases by the same amount.", "At ground level: PE = 0 and KE = mgh (all PE converted to KE). Total energy = mgh throughout."] },
  { id: "sq4", number: 4, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Waves & Sound", text: "Differentiate between transverse and longitudinal waves with one example each.", answer: ["Transverse waves: particles oscillate perpendicular to wave direction. Example: light waves, water surface waves.", "Longitudinal waves: particles oscillate parallel to wave direction. Example: sound waves.", "In transverse waves, the wave has crests and troughs. In longitudinal waves, it has compressions and rarefactions."] },
  { id: "sq5", number: 5, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Waves & Sound", text: "A person standing 340 m from a cliff claps once. After how long will they hear the echo? (Speed of sound = 340 m/s)", answer: ["The sound must travel to the cliff and back: total distance = 2 × 340 = 680 m.", "Time = distance / speed = 680 / 340 = 2 seconds.", "The person hears the echo after 2 seconds."] },
  { id: "sq6", number: 6, section: "C", sectionLabel: "Section C — long questions", marks: 10, topic: "Kinematics", text: "Derive the three equations of motion using a velocity-time graph.", answer: ["Consider a body with initial velocity u, uniform acceleration a, reaching velocity v in time t.", "First equation: The slope of the v-t graph = a = (v−u)/t → v = u + at", "Second equation: Distance s = area under v-t graph = area of trapezium = ½(u+v)t", "Substituting v = u+at: s = ½(u + u + at)t = ut + ½at²", "Third equation: From s = ½(u+v)t and t = (v−u)/a:", "s = ½(u+v)(v−u)/a → 2as = (v+u)(v−u) = v²−u²", "Therefore: v² = u² + 2as"] },
  { id: "sq7", number: 7, section: "C", sectionLabel: "Section C — long questions", marks: 10, topic: "Current Electricity", text: "State Ohm's law. Three resistors of 2 Ω, 3 Ω, and 6 Ω are connected in parallel to a 12 V battery. Find the total current and current through each resistor.", answer: ["Ohm's law: V = IR (voltage = current × resistance) at constant temperature.", "For parallel: 1/Rₜ = 1/R₁ + 1/R₂ + 1/R₃ = 1/2 + 1/3 + 1/6", "= 3/6 + 2/6 + 1/6 = 6/6 = 1", "So Rₜ = 1 Ω. Total current I = V/Rₜ = 12/1 = 12 A.", "In parallel, voltage across each resistor = 12 V.", "I₁ = 12/2 = 6 A, I₂ = 12/3 = 4 A, I₃ = 12/6 = 2 A", "Check: 6 + 4 + 2 = 12 A ✓"] },
  { id: "sq8", number: 8, section: "C", sectionLabel: "Section C — long questions", marks: 10, topic: "Work & Energy", text: "A ball of mass 2 kg is dropped from a height of 20 m (g = 10 m/s²). Find:", answer: ["(a) Potential energy at the top: PE = mgh = 2 × 10 × 20 = 400 J", "(b) Kinetic energy just before hitting the ground: By conservation of energy, KE = 400 J", "(c) Velocity just before hitting the ground: ½mv² = 400 → v² = 400 → v = √400 = 20 m/s", "(d) Velocity at the midpoint (h = 10 m): PE = 2×10×10 = 200 J, KE = 400−200 = 200 J", "½(2)v² = 200 → v = √200 ≈ 14.1 m/s"] },
] },

/* ════════════════ PUNJAB · CLASS 10 · PHYSICS · 2023 ════════════════ */
"punjab-10-physics-2023-Objective": { paperType: "Objective", questions: [
  { id: "q1", number: 1, marks: 1, topic: "Kinematics", text: "The SI unit of acceleration is:", options: ["m/s", "m/s²", "km/h²", "N/kg"], correctIndex: 1, explanation: "Acceleration = change in velocity / time, SI unit = m/s²." },
  { id: "q2", number: 2, marks: 1, topic: "Kinematics", text: "A body moving at 20 m/s decelerates at 4 m/s². Time to stop is:", options: ["2 s", "5 s", "10 s", "80 s"], correctIndex: 1, explanation: "v = u + at → 0 = 20 + (−4)t → t = 20/4 = 5 s." },
  { id: "q3", number: 3, marks: 1, topic: "Forces & Motion", text: "Newton's third law states that:", options: ["F = ma", "Every action has an equal and opposite reaction", "A body at rest stays at rest", "Energy is conserved"], correctIndex: 1, explanation: "Newton's third law: for every action, there is an equal and opposite reaction." },
  { id: "q4", number: 4, marks: 1, topic: "Work & Energy", text: "Work done by a force of 10 N moving a body 5 m in the direction of the force is:", options: ["2 J", "15 J", "50 J", "0.5 J"], correctIndex: 2, explanation: "W = Fd = 10 × 5 = 50 J." },
  { id: "q5", number: 5, marks: 1, topic: "Forces & Motion", text: "A bullet of mass 20 g is fired at 300 m/s. Its momentum is:", options: ["6 Ns", "60 Ns", "600 Ns", "0.6 Ns"], correctIndex: 0, explanation: "p = mv = 0.02 × 300 = 6 Ns (mass must be in kg)." },
  { id: "q6", number: 6, marks: 1, topic: "Work & Energy", text: "A machine does 600 J of work in 2 seconds. Its power is:", options: ["100 W", "200 W", "300 W", "1200 W"], correctIndex: 2, explanation: "P = W/t = 600/2 = 300 W." },
  { id: "q7", number: 7, marks: 1, topic: "Waves & Sound", text: "The wavelength of a wave with frequency 500 Hz and speed 340 m/s is:", options: ["0.68 m", "1.47 m", "170 m", "840 m"], correctIndex: 0, explanation: "λ = v/f = 340/500 = 0.68 m." },
  { id: "q8", number: 8, marks: 1, topic: "Waves & Sound", text: "Sound travels fastest in:", options: ["Solids", "Liquids", "Gases", "Vacuum"], correctIndex: 0, explanation: "Sound travels fastest in solids because particles are closer together." },
  { id: "q9", number: 9, marks: 1, topic: "Heat & Thermodynamics", text: "The specific heat capacity of water is:", options: ["2100 J/kg·K", "4200 J/kg·K", "390 J/kg·K", "450 J/kg·K"], correctIndex: 1, explanation: "Water has a specific heat capacity of 4200 J/(kg·K), one of the highest of common substances." },
  { id: "q10", number: 10, marks: 1, topic: "Heat & Thermodynamics", text: "The process of heat transfer that does not require a medium is:", options: ["Conduction", "Convection", "Radiation", "All require a medium"], correctIndex: 2, explanation: "Radiation transfers heat via electromagnetic waves and does not need a material medium." },
  { id: "q11", number: 11, marks: 1, topic: "Current Electricity", text: "Two resistors of 4 Ω and 12 Ω are connected in parallel. The equivalent resistance is:", options: ["16 Ω", "3 Ω", "8 Ω", "6 Ω"], correctIndex: 1, explanation: "1/R = 1/4 + 1/12 = 3/12 + 1/12 = 4/12 = 1/3 → R = 3 Ω." },
  { id: "q12", number: 12, marks: 1, topic: "Current Electricity", text: "The current through a 6 Ω resistor connected to a 9 V battery is:", options: ["0.67 A", "1.5 A", "3 A", "54 A"], correctIndex: 1, explanation: "I = V/R = 9/6 = 1.5 A." },
  { id: "q13", number: 13, marks: 1, topic: "Waves & Sound", text: "The image formed by a plane mirror is:", options: ["Real and inverted", "Virtual and erect", "Real and magnified", "Virtual and inverted"], correctIndex: 1, explanation: "A plane mirror forms a virtual, erect, laterally inverted image of the same size." },
  { id: "q14", number: 14, marks: 1, topic: "Heat & Thermodynamics", text: "The boiling point of water at standard pressure is:", options: ["90 °C", "100 °C", "110 °C", "212 °C"], correctIndex: 1, explanation: "At standard atmospheric pressure (1 atm), water boils at 100 °C (373 K)." },
  { id: "q15", number: 15, marks: 1, topic: "Current Electricity", text: "Electrical energy consumed by a 100 W bulb in 10 hours is:", options: ["1 kWh", "10 kWh", "100 kWh", "0.1 kWh"], correctIndex: 0, explanation: "E = Pt = 100 W × 10 h = 1000 Wh = 1 kWh (1 unit of electricity)." },
] },

"punjab-10-physics-2023-Subjective": { paperType: "Subjective", questions: [
  { id: "sq1", number: 1, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Kinematics", text: "Define speed and velocity. How are they different?", answer: ["Speed is the distance covered per unit time — a scalar quantity (magnitude only).", "Velocity is the displacement per unit time — a vector quantity (magnitude + direction).", "Speed = distance/time, Velocity = displacement/time.", "A body moving in a circle has non-zero speed but can have zero average velocity."] },
  { id: "sq2", number: 2, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Forces & Motion", text: "A car of mass 1000 kg accelerates from 10 m/s to 30 m/s in 5 seconds. Find the force.", answer: ["a = (v − u)/t = (30 − 10)/5 = 20/5 = 4 m/s²", "F = ma = 1000 × 4 = 4000 N", "The engine exerts a force of 4000 N on the car."] },
  { id: "sq3", number: 3, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Work & Energy", text: "Define power and state its SI unit. A crane lifts a 500 kg load by 12 m in 10 seconds. Find the power.", answer: ["Power is the rate of doing work: P = W/t. SI unit: Watt (W).", "Work done = mgh = 500 × 10 × 12 = 60000 J", "P = W/t = 60000/10 = 6000 W = 6 kW", "The crane's power output is 6 kW."] },
  { id: "sq4", number: 4, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Waves & Sound", text: "Define amplitude, frequency, and wavelength of a wave.", answer: ["Amplitude: maximum displacement from equilibrium — determines loudness (sound) or brightness (light).", "Frequency: number of complete waves passing a point per second. Unit: Hertz (Hz).", "Wavelength: distance between two consecutive identical points (e.g., crest to crest). Unit: metres (m).", "Related by: v = fλ, where v is wave speed."] },
  { id: "sq5", number: 5, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Heat & Thermodynamics", text: "Explain the difference between conduction, convection, and radiation.", answer: ["Conduction: heat transfer through direct contact between particles (solids). Particles vibrate and pass energy to neighbours.", "Convection: heat transfer by bulk movement of fluid (liquids/gases). Hot fluid rises, cold fluid sinks, forming convection currents.", "Radiation: heat transfer by electromagnetic waves (infrared). Requires no medium — can travel through vacuum."] },
  { id: "sq6", number: 6, section: "C", sectionLabel: "Section C — long questions", marks: 10, topic: "Kinematics", text: "Derive the three equations of motion using a velocity-time graph.", answer: ["Consider a body with initial velocity u, uniform acceleration a, reaching velocity v in time t.", "First equation: slope of v-t graph = a = (v−u)/t → v = u + at", "Second equation: s = area under v-t graph = ½(u+v)t = ½(u + u + at)t = ut + ½at²", "Third equation: from s = ½(u+v)t and t = (v−u)/a:", "2as = (v+u)(v−u) = v²−u² → v² = u² + 2as"] },
  { id: "sq7", number: 7, section: "C", sectionLabel: "Section C — long questions", marks: 10, topic: "Current Electricity", text: "State Joule's law of heating. An electric heater of resistance 20 Ω draws 5 A. Find the power and heat produced in 2 minutes.", answer: ["Joule's law: H = I²Rt (heat produced is proportional to I², R, and t).", "Power P = I²R = 25 × 20 = 500 W", "Time = 2 min = 120 s", "Heat H = I²Rt = 25 × 20 × 120 = 60000 J = 60 kJ", "Also H = Pt = 500 × 120 = 60000 J ✓"] },
  { id: "sq8", number: 8, section: "C", sectionLabel: "Section C — long questions", marks: 10, topic: "Work & Energy", text: "A ball of mass 2 kg is dropped from 20 m. Find PE at top, KE and velocity at ground (g = 10 m/s²).", answer: ["(a) PE at top = mgh = 2 × 10 × 20 = 400 J", "(b) KE at ground = PE at top (conservation) = 400 J", "(c) ½mv² = 400 → v² = 400 → v = 20 m/s", "(d) At midpoint (10 m): PE = 200 J, KE = 200 J, v = √200 ≈ 14.1 m/s"] },
] },

/* ════════════════ PUNJAB · CLASS 10 · CHEMISTRY · 2024 ════════════════ */
"punjab-10-chemistry-2024-Objective": { paperType: "Objective", questions: [
  { id: "q1", number: 1, marks: 1, topic: "Atomic Structure", text: "The number of protons in an atom is called its:", options: ["Mass number", "Atomic number", "Neutron number", "Nucleon number"], correctIndex: 1, explanation: "The atomic number (Z) equals the number of protons in the nucleus." },
  { id: "q2", number: 2, marks: 1, topic: "Atomic Structure", text: "The maximum number of electrons in the second shell (L shell) is:", options: ["2", "6", "8", "18"], correctIndex: 2, explanation: "Maximum electrons in shell n = 2n². For n=2: 2(4) = 8." },
  { id: "q3", number: 3, marks: 1, topic: "Periodic Table Trends", text: "Elements in the same group of the periodic table have:", options: ["Same atomic mass", "Same number of neutrons", "Same number of valence electrons", "Same number of protons"], correctIndex: 2, explanation: "Elements in the same group have the same number of valence electrons, giving similar chemical properties." },
  { id: "q4", number: 4, marks: 1, topic: "Chemical Bonding", text: "NaCl is an example of:", options: ["Covalent bonding", "Ionic bonding", "Metallic bonding", "Hydrogen bonding"], correctIndex: 1, explanation: "NaCl is ionic — Na transfers one electron to Cl, forming Na⁺ and Cl⁻ ions." },
  { id: "q5", number: 5, marks: 1, topic: "Chemical Bonding", text: "The bond formed by sharing of electrons is called:", options: ["Ionic bond", "Covalent bond", "Metallic bond", "Coordinate bond"], correctIndex: 1, explanation: "A covalent bond is formed when two atoms share one or more pairs of electrons." },
  { id: "q6", number: 6, marks: 1, topic: "States of Matter", text: "Boyle's law states that at constant temperature:", options: ["P ∝ T", "P ∝ 1/V", "V ∝ T", "P ∝ V"], correctIndex: 1, explanation: "Boyle's law: at constant temperature, pressure is inversely proportional to volume (P ∝ 1/V)." },
  { id: "q7", number: 7, marks: 1, topic: "States of Matter", text: "The process of conversion of gas to liquid is called:", options: ["Evaporation", "Sublimation", "Condensation", "Freezing"], correctIndex: 2, explanation: "Condensation is the phase change from gas to liquid." },
  { id: "q8", number: 8, marks: 1, topic: "Stoichiometry", text: "The molar mass of water (H₂O) is:", options: ["16 g/mol", "18 g/mol", "20 g/mol", "32 g/mol"], correctIndex: 1, explanation: "H₂O = 2(1) + 16 = 18 g/mol." },
  { id: "q9", number: 9, marks: 1, topic: "Stoichiometry", text: "One mole of any substance contains:", options: ["6.02 × 10²³ particles", "3.01 × 10²³ particles", "1.20 × 10²⁴ particles", "6.02 × 10²² particles"], correctIndex: 0, explanation: "Avogadro's number: 1 mole = 6.022 × 10²³ particles." },
  { id: "q10", number: 10, marks: 1, topic: "Acids & Bases", text: "The pH of a neutral solution is:", options: ["0", "1", "7", "14"], correctIndex: 2, explanation: "A neutral solution (like pure water) has pH = 7." },
  { id: "q11", number: 11, marks: 1, topic: "Acids & Bases", text: "Which of the following is a strong acid?", options: ["CH₃COOH", "H₂CO₃", "HCl", "H₂SO₃"], correctIndex: 2, explanation: "HCl (hydrochloric acid) completely dissociates in water, making it a strong acid." },
  { id: "q12", number: 12, marks: 1, topic: "Acids & Bases", text: "Bases turn red litmus paper:", options: ["Red", "Blue", "Green", "Yellow"], correctIndex: 1, explanation: "Bases turn red litmus paper blue. Acids turn blue litmus paper red." },
  { id: "q13", number: 13, marks: 1, topic: "Chemical Bonding", text: "The number of covalent bonds in a methane (CH₄) molecule is:", options: ["2", "3", "4", "5"], correctIndex: 2, explanation: "Carbon shares 4 electrons with 4 hydrogen atoms, forming 4 single covalent bonds." },
  { id: "q14", number: 14, marks: 1, topic: "Periodic Table Trends", text: "Electronegativity generally increases:", options: ["Down a group", "Across a period (left to right)", "Both directions", "Neither direction"], correctIndex: 1, explanation: "Electronegativity increases across a period (left to right) due to increasing nuclear charge." },
  { id: "q15", number: 15, marks: 1, topic: "Stoichiometry", text: "The number of moles in 36 g of water is:", options: ["1", "2", "3", "4"], correctIndex: 1, explanation: "Moles = mass/molar mass = 36/18 = 2 moles." },
] },

"punjab-10-chemistry-2024-Subjective": { paperType: "Subjective", questions: [
  { id: "sq1", number: 1, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Atomic Structure", text: "Draw the electronic configuration of sodium (Na, Z=11) and explain its valency.", answer: ["Sodium: 1s² 2s² 2p⁶ 3s¹ (shells: K=2, L=8, M=1)", "Sodium has 1 electron in its outermost shell (valence electron = 1).", "It loses this one electron to achieve a stable noble gas configuration (like Ne).", "Therefore, sodium has a valency of 1 (forms Na⁺ ion)."] },
  { id: "sq2", number: 2, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Chemical Bonding", text: "Differentiate between ionic and covalent bonds with one example each.", answer: ["Ionic bond: formed by transfer of electrons from one atom to another. Example: NaCl (Na gives electron to Cl).", "Covalent bond: formed by sharing of electron pairs between atoms. Example: H₂O (O shares electrons with two H atoms).", "Ionic compounds are usually soluble in water, have high melting points, and conduct electricity in solution.", "Covalent compounds have lower melting points and generally do not conduct electricity."] },
  { id: "sq3", number: 3, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Stoichiometry", text: "Calculate the number of molecules in 44 g of CO₂. (C = 12, O = 16)", answer: ["Molar mass of CO₂ = 12 + 2(16) = 44 g/mol", "Number of moles = 44/44 = 1 mole", "Number of molecules = moles × Avogadro's number", "= 1 × 6.022 × 10²³ = 6.022 × 10²³ molecules"] },
  { id: "sq4", number: 4, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Acids & Bases", text: "What is the pH scale? Classify the following as acidic, basic, or neutral: lemon juice (pH 2), pure water (pH 7), baking soda solution (pH 9).", answer: ["The pH scale ranges from 0 to 14 and measures the hydrogen ion concentration of a solution.", "pH < 7: acidic, pH = 7: neutral, pH > 7: basic.", "Lemon juice (pH 2): strongly acidic", "Pure water (pH 7): neutral", "Baking soda solution (pH 9): basic"] },
  { id: "sq5", number: 5, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "States of Matter", text: "State Charles' law and explain it using the kinetic molecular theory.", answer: ["Charles' law: at constant pressure, the volume of a gas is directly proportional to its absolute temperature (V ∝ T).", "Mathematically: V₁/T₁ = V₂/T₂", "Kinetic explanation: when temperature increases, gas molecules gain kinetic energy and move faster.", "They collide with the container walls with greater force, pushing the walls outward and increasing the volume."] },
  { id: "sq6", number: 6, section: "C", sectionLabel: "Section C — long questions", marks: 10, topic: "Periodic Table Trends", text: "Describe the periodic law and the arrangement of elements in the modern periodic table. Explain how atomic size changes across a period and down a group.", answer: ["Modern Periodic Law: the properties of elements are periodic functions of their atomic numbers (Moseley).", "The modern table has 7 periods (horizontal rows) and 18 groups (vertical columns).", "Elements in the same group have similar valence electron configurations and chemical properties.", "Atomic size across a period: DECREASES from left to right. Reason: nuclear charge increases, pulling electrons closer.", "Atomic size down a group: INCREASES. Reason: new shells are added, increasing the distance of outer electrons from the nucleus."] },
  { id: "sq7", number: 7, section: "C", sectionLabel: "Section C — long questions", marks: 10, topic: "Acids & Bases", text: "Define acids and bases according to the Arrhenius and Brønsted-Lowry theories. Write the neutralization reaction between HCl and NaOH.", answer: ["Arrhenius: acids produce H⁺ in water; bases produce OH⁻ in water.", "Brønsted-Lowry: acids are proton (H⁺) donors; bases are proton (H⁺) acceptors.", "Example: HCl → H⁺ + Cl⁻ (Arrhenius acid)", "NH₃ + H⁺ → NH₄⁺ (NH₃ is a Brønsted base — accepts proton)", "Neutralization: HCl + NaOH → NaCl + H₂O", "Ionic form: H⁺ + OH⁻ → H₂O (salt and water always form)"] },
  { id: "sq8", number: 8, section: "C", sectionLabel: "Section C — long questions", marks: 10, topic: "Stoichiometry", text: "What is stoichiometry? Balance the equation and calculate the mass of CO₂ produced when 12 g of carbon burns completely in oxygen.", answer: ["Stoichiometry: the calculation of quantities in chemical reactions using balanced equations.", "Equation: C + O₂ → CO₂ (already balanced)", "Moles of C = 12/12 = 1 mole", "From equation: 1 mol C produces 1 mol CO₂", "Mass of CO₂ = moles × molar mass = 1 × 44 = 44 g", "Therefore, 12 g of carbon produces 44 g of CO₂."] },
] },

/* ════════════════ FBISE · CLASS 12 · MATH · 2024 ════════════════ */
"fbise-12-math-2024-Objective": { paperType: "Objective", questions: [
  { id: "q1", number: 1, marks: 1, topic: "Functions & Limits", text: "If f(x) = 3x + 2, then f(f(x)) equals:", options: ["9x + 8", "9x + 4", "6x + 4", "9x + 6"], correctIndex: 0, explanation: "f(f(x)) = 3(3x+2)+2 = 9x+6+2 = 9x+8." },
  { id: "q2", number: 2, marks: 1, topic: "Functions & Limits", text: "lim(x→0) sin(x)/x equals:", options: ["0", "1", "∞", "Does not exist"], correctIndex: 1, explanation: "This is a standard limit: lim(x→0) sin(x)/x = 1." },
  { id: "q3", number: 3, marks: 1, topic: "Differentiation", text: "The derivative of x³ + 2x² − 5x + 7 is:", options: ["3x² + 4x − 5", "x² + 4x − 5", "3x² + 2x − 5", "3x³ + 4x² − 5x"], correctIndex: 0, explanation: "d/dx(x³+2x²−5x+7) = 3x² + 4x − 5." },
  { id: "q4", number: 4, marks: 1, topic: "Differentiation", text: "If y = sin(2x), then dy/dx equals:", options: ["cos(2x)", "2cos(2x)", "−2cos(2x)", "2sin(2x)"], correctIndex: 1, explanation: "Chain rule: d/dx[sin(2x)] = cos(2x) × 2 = 2cos(2x)." },
  { id: "q5", number: 5, marks: 1, topic: "Integration", text: "∫ 2x dx equals:", options: ["x² + C", "2x² + C", "x + C", "2 + C"], correctIndex: 0, explanation: "∫2x dx = 2(x²/2) + C = x² + C." },
  { id: "q6", number: 6, marks: 1, topic: "Integration", text: "∫ cos(x) dx equals:", options: ["−sin(x) + C", "sin(x) + C", "cos(x) + C", "−cos(x) + C"], correctIndex: 1, explanation: "The integral of cos(x) is sin(x) + C." },
  { id: "q7", number: 7, marks: 1, topic: "Conic Sections", text: "The equation x²/a² + y²/b² = 1 represents:", options: ["A circle", "An ellipse", "A parabola", "A hyperbola"], correctIndex: 1, explanation: "This is the standard equation of an ellipse centred at the origin." },
  { id: "q8", number: 8, marks: 1, topic: "Conic Sections", text: "The focus of the parabola y² = 4ax is at:", options: ["(0, a)", "(a, 0)", "(−a, 0)", "(0, −a)"], correctIndex: 1, explanation: "For y² = 4ax, the focus is at (a, 0)." },
  { id: "q9", number: 9, marks: 1, topic: "Vectors", text: "If a = 3i + 4j, the magnitude |a| is:", options: ["5", "7", "12", "1"], correctIndex: 0, explanation: "|a| = √(3²+4²) = √(9+16) = √25 = 5." },
  { id: "q10", number: 10, marks: 1, topic: "Vectors", text: "The dot product of perpendicular vectors is:", options: ["0", "1", "−1", "Maximum"], correctIndex: 0, explanation: "a·b = |a||b|cos(90°) = 0. Perpendicular vectors have zero dot product." },
  { id: "q11", number: 11, marks: 1, topic: "Matrices & Determinants", text: "If det(A) = 0, then matrix A is:", options: ["Invertible", "Singular", "Orthogonal", "Symmetric"], correctIndex: 1, explanation: "A matrix with det = 0 is singular (non-invertible)." },
  { id: "q12", number: 12, marks: 1, topic: "Matrices & Determinants", text: "The inverse of a 2×2 matrix [a b; c d] is:", options: ["1/(ad−bc) [d −b; −c a]", "[d −b; −c a]", "1/(ad+bc) [d −b; −c a]", "[a b; c d]"], correctIndex: 0, explanation: "A⁻¹ = (1/det) × adj(A), where adj = [d −b; −c a] for a 2×2 matrix." },
  { id: "q13", number: 13, marks: 1, topic: "Sequences & Series", text: "The sum of an infinite geometric series with first term a and ratio r (|r|<1) is:", options: ["a/(1+r)", "a/(1−r)", "a(1−r)", "ar/(1−r)"], correctIndex: 1, explanation: "S∞ = a/(1−r) for |r| < 1." },
  { id: "q14", number: 14, marks: 1, topic: "Sequences & Series", text: "The nth term of an arithmetic sequence with first term a and common difference d is:", options: ["a + nd", "a + (n−1)d", "a × n × d", "a − (n−1)d"], correctIndex: 1, explanation: "aₙ = a + (n−1)d." },
  { id: "q15", number: 15, marks: 1, topic: "Probability", text: "If P(A) = 0.3 and P(B) = 0.5, and A, B are independent, P(A∩B) equals:", options: ["0.8", "0.15", "0.2", "0.35"], correctIndex: 1, explanation: "For independent events: P(A∩B) = P(A) × P(B) = 0.3 × 0.5 = 0.15." },
] },

"fbise-12-math-2024-Subjective": { paperType: "Subjective", questions: [
  { id: "sq1", number: 1, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Functions & Limits", text: "Evaluate: lim(x→3) (x² − 9)/(x − 3)", answer: ["Factor the numerator: x² − 9 = (x−3)(x+3)", "lim(x→3) [(x−3)(x+3)]/(x−3)", "Cancel (x−3): lim(x→3) (x+3)", "= 3 + 3 = 6"] },
  { id: "sq2", number: 2, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Differentiation", text: "Find dy/dx if y = x² · sin(x) using the product rule.", answer: ["Product rule: d/dx(uv) = u'v + uv'", "Let u = x² → u' = 2x, and v = sin(x) → v' = cos(x)", "dy/dx = 2x·sin(x) + x²·cos(x)", "= x(2sin(x) + x·cos(x))"] },
  { id: "sq3", number: 3, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Integration", text: "Evaluate ∫₀² (3x² + 2x) dx.", answer: ["∫(3x² + 2x) dx = x³ + x² + C", "Applying limits: [x³ + x²]₀²", "= (8 + 4) − (0 + 0)", "= 12"] },
  { id: "sq4", number: 4, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Conic Sections", text: "Find the equation of an ellipse with semi-major axis a = 5 and semi-minor axis b = 3. Find its eccentricity.", answer: ["Equation: x²/25 + y²/9 = 1", "Eccentricity e = √(1 − b²/a²) = √(1 − 9/25) = √(16/25)", "e = 4/5 = 0.8"] },
  { id: "sq5", number: 5, section: "B", sectionLabel: "Section B — short questions", marks: 4, topic: "Vectors", text: "Find the angle between vectors a = 2i + 3j − k and b = i − j + 2k.", answer: ["a·b = (2)(1) + (3)(−1) + (−1)(2) = 2 − 3 − 2 = −3", "|a| = √(4+9+1) = √14, |b| = √(1+1+4) = √6", "cos θ = (a·b)/(|a||b|) = −3/(√14 × √6) = −3/√84", "θ = cos⁻¹(−3/√84) ≈ cos⁻¹(−0.327) ≈ 109.1°"] },
  { id: "sq6", number: 6, section: "C", sectionLabel: "Section C — long questions", marks: 10, topic: "Differentiation", text: "Find the equation of the tangent to the curve y = x³ − 3x + 2 at the point where x = 1. Also find the equation of the normal.", answer: ["At x = 1: y = 1 − 3 + 2 = 0. Point: (1, 0).", "dy/dx = 3x² − 3. At x = 1: dy/dx = 3 − 3 = 0.", "Slope of tangent m = 0 (horizontal tangent).", "Tangent: y − 0 = 0(x − 1) → y = 0", "Slope of normal = −1/m = undefined (vertical line).", "Normal: x = 1"] },
  { id: "sq7", number: 7, section: "C", sectionLabel: "Section C — long questions", marks: 10, topic: "Integration", text: "Find the area enclosed by the curve y = x² and the line y = 4.", answer: ["Intersection: x² = 4 → x = −2 and x = 2", "Area = ∫₋₂² (4 − x²) dx", "= [4x − x³/3]₋₂²", "= (8 − 8/3) − (−8 + 8/3)", "= (16/3) − (−16/3) = 32/3", "Area = 32/3 square units ≈ 10.67 sq units"] },
  { id: "sq8", number: 8, section: "C", sectionLabel: "Section C — long questions", marks: 10, topic: "Sequences & Series", text: "The sum of the first 10 terms of an arithmetic sequence is 200, and the 5th term is 18. Find the first term and common difference.", answer: ["S₁₀ = n/2 [2a + (n−1)d] → 200 = 5[2a + 9d] → 2a + 9d = 40 ... (i)", "a₅ = a + 4d = 18 ... (ii)", "From (ii): a = 18 − 4d. Substitute in (i):", "2(18 − 4d) + 9d = 40", "36 − 8d + 9d = 40 → d = 4", "a = 18 − 4(4) = 18 − 16 = 2", "First term a = 2, common difference d = 4."] },
] },
};