/* ═══════════════════════════════════════════════════════════════════════════
   MENTORA AI — PRACTICE QUESTION BANK
   Hand-written practice MCQs per subject and topic (Pakistani boards).
   Practice deliberately does NOT use the assessment generator in data.ts —
   these questions are always NEW compared with the scored Assessment test.
   data.ts getPracticeQuestions() picks from this bank, weighted toward the
   student's weak topics (topics with recorded mistakes).
   Topic strings must match TOPICS_BY_SUBJECT in data.ts exactly.
═══════════════════════════════════════════════════════════════════════════ */

export type SubjectId = "math" | "physics" | "chemistry" | "biology" | "english" | "computer" | "urdu";

export type PracticeBankQ = {
  id: string;
  topic: string;
  text: string;
  options: string[];
  correctIndex: number;
  explanation: string;
};

export const PRACTICE_BANK: Record<SubjectId, PracticeBankQ[]> = {

  /* ── MATHEMATICS ────────────────────────────────────────────────────────── */
  math: [

  /* Algebra Basics */
  { id: "p-math-algebra-1", topic: "Algebra Basics",
    text: "Simplify: 3(2x − 4) + 5x",
    options: ["6x − 12", "11x − 12", "11x + 12", "8x − 4"],
    correctIndex: 1,
    explanation: "Expand first: 3(2x − 4) = 6x − 12. Then 6x − 12 + 5x = 11x − 12." },
  { id: "p-math-algebra-2", topic: "Algebra Basics",
    text: "Evaluate 2x² − 4x + 1 when x = 3.",
    options: ["7", "13", "19", "25"],
    correctIndex: 0,
    explanation: "2(3)² − 4(3) + 1 = 2(9) − 12 + 1 = 18 − 12 + 1 = 7. Apply the exponent before multiplying." },
  { id: "p-math-algebra-3", topic: "Algebra Basics",
    text: "Combine like terms: 7a + 3b − 2a + 5b",
    options: ["5a + 8b", "12ab", "5a − 2b", "10a + 8b"],
    correctIndex: 0,
    explanation: "Group the a-terms (7a − 2a = 5a) and the b-terms (3b + 5b = 8b) to get 5a + 8b." },
  { id: "p-math-algebra-4", topic: "Algebra Basics",
    text: "Which of the following is a polynomial?",
    options: ["√x + 2", "2^x + 1", "x² + 3x + 1", "1/x + x"],
    correctIndex: 2,
    explanation: "A polynomial may only contain whole-number (0, 1, 2, …) powers of the variable. Roots, negative and variable exponents are not allowed." },
  { id: "p-math-algebra-5", topic: "Algebra Basics",
    text: "Expand and simplify: (x + 3)(x − 2)",
    options: ["x² + x − 6", "x² − x − 6", "x² − 6", "x² + 5x − 6"],
    correctIndex: 0,
    explanation: "x·x = x², x·(−2) = −2x, 3·x = 3x, 3·(−2) = −6. The middle terms give −2x + 3x = +x, so x² + x − 6." },

  /* Variables & Expressions */
  { id: "p-math-express-1", topic: "Variables & Expressions",
    text: "Translate into algebra: “five less than twice a number n”.",
    options: ["5 − 2n", "2n − 5", "2(n − 5)", "5n − 2"],
    correctIndex: 1,
    explanation: "Twice the number is 2n; “five less than” that quantity subtracts 5 at the end: 2n − 5." },
  { id: "p-math-express-2", topic: "Variables & Expressions",
    text: "Evaluate 4x − 3y when x = 5 and y = 2.",
    options: ["14", "7", "26", "22"],
    correctIndex: 0,
    explanation: "4(5) − 3(2) = 20 − 6 = 14." },
  { id: "p-math-express-3", topic: "Variables & Expressions",
    text: "What is the coefficient of xy in 3x²y − 5xy + 7?",
    options: ["3", "5", "−5", "7"],
    correctIndex: 2,
    explanation: "The term containing xy is −5xy, so its coefficient is −5. The other terms contain x²y or no xy at all." },
  { id: "p-math-express-4", topic: "Variables & Expressions",
    text: "Simplify: 2(m + 3n) − (m − 4n)",
    options: ["m + 10n", "m − 10n", "3m + 2n", "m + 2n"],
    correctIndex: 0,
    explanation: "2m + 6n − m + 4n. Watch the sign: subtracting (m − 4n) flips both signs. Result: m + 10n." },
  { id: "p-math-express-5", topic: "Variables & Expressions",
    text: "If n = 4, what is the value of n² − (n − 2)?",
    options: ["10", "14", "12", "8"],
    correctIndex: 1,
    explanation: "n² = 16 and (n − 2) = 2, so 16 − 2 = 14. Evaluate the bracket first, then subtract." },
  { id: "p-math-express-6", topic: "Variables & Expressions",
    text: "Which expression represents “the sum of a number and its square”?",
    options: ["n + n²", "2n", "n² − n", "n ÷ n"],
    correctIndex: 0,
    explanation: "The number is n and its square is n²; their sum is n + n²." },

  /* Linear Equations */
  { id: "p-math-linear-1", topic: "Linear Equations",
    text: "Solve: 4x − 7 = 17",
    options: ["4", "5", "6", "8"],
    correctIndex: 2,
    explanation: "Add 7 to both sides: 4x = 24. Divide by 4: x = 6." },
  { id: "p-math-linear-2", topic: "Linear Equations",
    text: "If 3(y + 2) = 18, then y = ?",
    options: ["4", "6", "5", "3"],
    correctIndex: 0,
    explanation: "Divide both sides by 3: y + 2 = 6. Subtract 2: y = 4." },
  { id: "p-math-linear-3", topic: "Linear Equations",
    text: "Solve: x/3 + 2 = 5",
    options: ["9", "7", "3", "1"],
    correctIndex: 0,
    explanation: "Subtract 2: x/3 = 3. Multiply both sides by 3: x = 9." },
  { id: "p-math-linear-4", topic: "Linear Equations",
    text: "Solve: 2x + 5 = x + 9",
    options: ["4", "14", "2", "−4"],
    correctIndex: 0,
    explanation: "Subtract x from both sides: x + 5 = 9. Subtract 5: x = 4." },
  { id: "p-math-linear-5", topic: "Linear Equations",
    text: "The equation 2x + 6 = 2x + 1 has:",
    options: ["One solution", "Two solutions", "No solution", "Infinitely many solutions"],
    correctIndex: 2,
    explanation: "Subtracting 2x from both sides gives 6 = 1, which is false — the same variable term cancels, so no value of x works." },

  /* Equation Solving */
  { id: "p-math-solving-1", topic: "Equation Solving",
    text: "Solve: 5(x − 2) = 3x + 4",
    options: ["3", "5", "7", "−7"],
    correctIndex: 2,
    explanation: "Expand: 5x − 10 = 3x + 4. Then 2x = 14, so x = 7." },
  { id: "p-math-solving-2", topic: "Equation Solving",
    text: "Solve: 2x/3 = 8",
    options: ["12", "16/3", "6", "24"],
    correctIndex: 0,
    explanation: "Multiply both sides by 3: 2x = 24. Divide by 2: x = 12." },
  { id: "p-math-solving-3", topic: "Equation Solving",
    text: "If 7 − 2x = 1, then x = ?",
    options: ["3", "−3", "4", "−4"],
    correctIndex: 0,
    explanation: "Subtract 7: −2x = −6. Divide by −2: x = 3." },
  { id: "p-math-solving-4", topic: "Equation Solving",
    text: "Solve for m: 3m − 4 = m + 8",
    options: ["2", "3", "6", "12"],
    correctIndex: 2,
    explanation: "Subtract m: 2m − 4 = 8. Add 4: 2m = 12, so m = 6." },
  { id: "p-math-solving-5", topic: "Equation Solving",
    text: "Solve: 4(x + 1) − 2(x − 3) = 18",
    options: ["2", "3", "4", "6"],
    correctIndex: 2,
    explanation: "Expand: 4x + 4 − 2x + 6 = 18 → 2x + 10 = 18 → 2x = 8 → x = 4." },

  /* Word Problems */
  { id: "p-math-word-1", topic: "Word Problems",
    text: "The sum of three consecutive integers is 72. What is the smallest of them?",
    options: ["22", "23", "24", "25"],
    correctIndex: 1,
    explanation: "Let the integers be n, n+1, n+2. Then 3n + 3 = 72, so 3n = 69 and n = 23 (23 + 24 + 25 = 72)." },
  { id: "p-math-word-2", topic: "Word Problems",
    text: "Ali is 5 years older than Bilal. Together their ages total 27. How old is Bilal?",
    options: ["11", "16", "22", "8"],
    correctIndex: 0,
    explanation: "Let Bilal be b; Ali is b + 5. Then b + (b + 5) = 27 → 2b = 22 → b = 11." },
  { id: "p-math-word-3", topic: "Word Problems",
    text: "A notebook costs Rs 25 more than a pen. Together they cost Rs 65. What is the price of the pen?",
    options: ["Rs 20", "Rs 25", "Rs 45", "Rs 40"],
    correctIndex: 0,
    explanation: "Let the pen be p; the notebook is p + 25. Then 2p + 25 = 65 → 2p = 40 → p = Rs 20." },
  { id: "p-math-word-4", topic: "Word Problems",
    text: "A rectangle has width w and length 2w + 3. If its perimeter is 36, what is w?",
    options: ["3", "4", "5", "6"],
    correctIndex: 2,
    explanation: "P = 2(w + 2w + 3) = 6w + 6. So 6w + 6 = 36 → 6w = 30 → w = 5." },
  { id: "p-math-word-5", topic: "Word Problems",
    text: "A number is doubled and then 9 is subtracted, giving 15. What is the number?",
    options: ["12", "10", "8", "6"],
    correctIndex: 0,
    explanation: "2n − 9 = 15 → 2n = 24 → n = 12." },

  /* Graphing Lines */
  { id: "p-math-graph-1", topic: "Graphing Lines",
    text: "What is the slope of the line passing through (1, 2) and (3, 8)?",
    options: ["3", "1/3", "6", "2"],
    correctIndex: 0,
    explanation: "Slope = (y₂ − y₁)/(x₂ − x₁) = (8 − 2)/(3 − 1) = 6/2 = 3." },
  { id: "p-math-graph-2", topic: "Graphing Lines",
    text: "Where does the line y = −2x + 5 cross the y-axis?",
    options: ["(0, 5)", "(5, 0)", "(0, −2)", "(−2, 0)"],
    correctIndex: 0,
    explanation: "On the y-axis, x = 0. Substituting gives y = 5, so the intercept is (0, 5). In y = mx + c, c is always the y-intercept." },
  { id: "p-math-graph-3", topic: "Graphing Lines",
    text: "What is the slope of the line y = 4?",
    options: ["0", "4", "Undefined", "1"],
    correctIndex: 0,
    explanation: "y = 4 is a horizontal line — y never changes as x changes, so the slope is 0." },
  { id: "p-math-graph-4", topic: "Graphing Lines",
    text: "Two distinct lines are parallel when they have:",
    options: ["The same slope", "Slopes that multiply to −1", "The same y-intercept", "Opposite slopes"],
    correctIndex: 0,
    explanation: "Parallel lines never meet, which happens exactly when their slopes are equal. Slopes multiplying to −1 means the lines are perpendicular." },
  { id: "p-math-graph-5", topic: "Graphing Lines",
    text: "A line passes through (0, −3) with slope 2. Its equation is:",
    options: ["y = 2x − 3", "y = −3x + 2", "y = 3x − 2", "y = 2x + 3"],
    correctIndex: 0,
    explanation: "Using y = mx + c: the slope m = 2 and the y-intercept c = −3 (from point (0, −3)), giving y = 2x − 3." },
  ],

  /* ── PHYSICS ─────────────────────────────────────────────────────────────── */
  physics: [

  /* Kinematics */
  { id: "p-phys-kine-1", topic: "Kinematics",
    text: "A car starts from rest and accelerates at 2 m/s² for 5 s. Its final velocity is:",
    options: ["10 m/s", "2.5 m/s", "7 m/s", "25 m/s"],
    correctIndex: 0,
    explanation: "v = u + at = 0 + (2)(5) = 10 m/s." },
  { id: "p-phys-kine-2", topic: "Kinematics",
    text: "A body moves at 10 m/s and accelerates at 3 m/s² for 4 s. The distance covered is:",
    options: ["40 m", "52 m", "64 m", "88 m"],
    correctIndex: 2,
    explanation: "s = ut + ½at² = (10)(4) + ½(3)(16) = 40 + 24 = 64 m." },
  { id: "p-phys-kine-3", topic: "Kinematics",
    text: "The SI unit of acceleration is:",
    options: ["m/s", "m/s²", "N", "J"],
    correctIndex: 1,
    explanation: "Acceleration is the change in velocity (m/s) per second, so its unit is (m/s)/s = m/s²." },
  { id: "p-phys-kine-4", topic: "Kinematics",
    text: "The area under a velocity–time graph gives:",
    options: ["Acceleration", "Distance travelled", "Speed", "Force"],
    correctIndex: 1,
    explanation: "Velocity × time = distance, so the area under the v–t curve equals the distance travelled." },
  { id: "p-phys-kine-5", topic: "Kinematics",
    text: "A body moving with uniform velocity has acceleration:",
    options: ["Zero", "Increasing", "Constant but non-zero", "Equal to velocity"],
    correctIndex: 0,
    explanation: "Uniform velocity means velocity is not changing, so the rate of change of velocity (acceleration) is zero." },

  /* Forces & Motion */
  { id: "p-phys-force-1", topic: "Forces & Motion",
    text: "A force acts on a 5 kg mass producing an acceleration of 4 m/s². The force is:",
    options: ["9 N", "1.25 N", "20 N", "45 N"],
    correctIndex: 2,
    explanation: "Newton's second law: F = ma = (5)(4) = 20 N." },
  { id: "p-phys-force-2", topic: "Forces & Motion",
    text: "Newton's third law of motion states that:",
    options: ["Every action has an equal and opposite reaction", "Force equals mass times acceleration", "A body stays at rest unless acted upon by a force", "Energy can neither be created nor destroyed"],
    correctIndex: 0,
    explanation: "The third law links forces in pairs: if A pushes B, B pushes A equally in the opposite direction. F = ma is the second law; inertia is the first." },
  { id: "p-phys-force-3", topic: "Forces & Motion",
    text: "The weight of a 10 kg object on Earth (g = 10 m/s²) is:",
    options: ["1 N", "10 N", "100 N", "1000 N"],
    correctIndex: 2,
    explanation: "W = mg = (10)(10) = 100 N. Mass (kg) is constant everywhere; weight (N) depends on g." },
  { id: "p-phys-force-4", topic: "Forces & Motion",
    text: "The inertia of a body depends on its:",
    options: ["Speed", "Mass", "Shape", "Volume"],
    correctIndex: 1,
    explanation: "The more mass a body has, the more it resists a change in its state of motion." },
  { id: "p-phys-force-5", topic: "Forces & Motion",
    text: "A resultant force of zero acts on a moving body. The body will:",
    options: ["Stop immediately", "Keep moving at constant velocity", "Accelerate uniformly", "Move in a circle"],
    correctIndex: 1,
    explanation: "With no net force there is no acceleration (Newton's first law), so the body continues at the same constant velocity." },

  /* Work & Energy */
  { id: "p-phys-energy-1", topic: "Work & Energy",
    text: "A force of 20 N moves a body 3 m in the direction of the force. The work done is:",
    options: ["23 J", "60 J", "6.7 J", "180 J"],
    correctIndex: 1,
    explanation: "W = F × d = 20 × 3 = 60 J (1 N·m = 1 J)." },
  { id: "p-phys-energy-2", topic: "Work & Energy",
    text: "The kinetic energy of a 2 kg body moving at 4 m/s is:",
    options: ["8 J", "16 J", "32 J", "4 J"],
    correctIndex: 1,
    explanation: "K.E. = ½mv² = ½(2)(4²) = ½(2)(16) = 16 J." },
  { id: "p-phys-energy-3", topic: "Work & Energy",
    text: "A 3 kg body is raised 5 m (g = 10 m/s²). Its gain in potential energy is:",
    options: ["15 J", "50 J", "150 J", "30 J"],
    correctIndex: 2,
    explanation: "P.E. = mgh = (3)(10)(5) = 150 J." },
  { id: "p-phys-energy-4", topic: "Work & Energy",
    text: "The SI unit of power is:",
    options: ["Joule", "Watt", "Newton", "Pascal"],
    correctIndex: 1,
    explanation: "Power = work done per second, so its unit is J/s, called the watt. The joule measures energy." },
  { id: "p-phys-energy-5", topic: "Work & Energy",
    text: "A body falls freely from rest. At the halfway point of its fall:",
    options: ["P.E. is zero", "K.E. equals P.E.", "Half the P.E. has become K.E.", "Total energy has halved"],
    correctIndex: 2,
    explanation: "Energy is conserved: at half the height, half the original P.E. has converted into K.E., and the total stays constant." },

  /* Waves & Sound */
  { id: "p-phys-waves-1", topic: "Waves & Sound",
    text: "A wave has frequency 100 Hz and wavelength 2 m. Its speed is:",
    options: ["50 m/s", "200 m/s", "300 m/s", "0.02 m/s"],
    correctIndex: 1,
    explanation: "v = fλ = (100)(2) = 200 m/s." },
  { id: "p-phys-waves-2", topic: "Waves & Sound",
    text: "Sound cannot travel through:",
    options: ["Air", "Water", "Steel", "Vacuum"],
    correctIndex: 3,
    explanation: "Sound is a mechanical wave that needs particles to vibrate, so it cannot pass through a vacuum." },
  { id: "p-phys-waves-3", topic: "Waves & Sound",
    text: "The audible frequency range for humans is approximately:",
    options: ["2 Hz – 20 Hz", "20 Hz – 20,000 Hz", "20,000 Hz – 200,000 Hz", "2 kHz – 20 kHz only"],
    correctIndex: 1,
    explanation: "Humans hear roughly 20 Hz to 20 kHz. Below 20 Hz is infrasound; above 20 kHz is ultrasound." },
  { id: "p-phys-waves-4", topic: "Waves & Sound",
    text: "The pitch of a sound is determined by its:",
    options: ["Amplitude", "Frequency", "Wavelength", "Speed"],
    correctIndex: 1,
    explanation: "Higher frequency → higher pitch. Amplitude controls loudness, not pitch." },
  { id: "p-phys-waves-5", topic: "Waves & Sound",
    text: "The distance between two consecutive crests of a wave is called its:",
    options: ["Frequency", "Period", "Wavelength", "Amplitude"],
    correctIndex: 2,
    explanation: "Wavelength is one full wave — crest to crest or trough to trough. Amplitude is the height from the rest position." },

  /* Current Electricity */
  { id: "p-phys-elec-1", topic: "Current Electricity",
    text: "A current of 2 A flows through a 6 Ω resistor. The voltage across it is:",
    options: ["3 V", "8 V", "12 V", "0.33 V"],
    correctIndex: 2,
    explanation: "Ohm's law: V = IR = (2)(6) = 12 V." },
  { id: "p-phys-elec-2", topic: "Current Electricity",
    text: "An appliance works at 12 V and draws 2 A. The power it consumes is:",
    options: ["6 W", "24 W", "48 W", "14 W"],
    correctIndex: 1,
    explanation: "P = VI = (12)(2) = 24 W." },
  { id: "p-phys-elec-3", topic: "Current Electricity",
    text: "Resistors of 3 Ω and 5 Ω connected in series give a total resistance of:",
    options: ["1.875 Ω", "2 Ω", "8 Ω", "15 Ω"],
    correctIndex: 2,
    explanation: "In a series circuit resistances add up: R = 3 + 5 = 8 Ω. In parallel the combined resistance would be smaller (about 1.9 Ω)." },
  { id: "p-phys-elec-4", topic: "Current Electricity",
    text: "The SI unit of electric charge is the:",
    options: ["Ampere", "Coulomb", "Volt", "Ohm"],
    correctIndex: 1,
    explanation: "Charge is measured in coulombs (Q = It). The ampere is the unit of current, not charge." },
  { id: "p-phys-elec-5", topic: "Current Electricity",
    text: "In a series circuit, the current is:",
    options: ["The same at every point", "Divided equally among components", "Zero after the first resistor", "Different at every point"],
    correctIndex: 0,
    explanation: "There is only one path, so the same current flows through every component; it is the voltage that divides across them." },

  /* Heat & Thermodynamics */
  { id: "p-phys-heat-1", topic: "Heat & Thermodynamics",
    text: "The method of heat transfer that needs no medium at all is:",
    options: ["Conduction", "Convection", "Radiation", "Insulation"],
    correctIndex: 2,
    explanation: "Radiation travels as electromagnetic waves, which is how the Sun's heat reaches us through empty space." },
  { id: "p-phys-heat-2", topic: "Heat & Thermodynamics",
    text: "Absolute zero corresponds to:",
    options: ["0 °C", "−100 °C", "−273 °C", "273 °C"],
    correctIndex: 2,
    explanation: "0 K = −273 °C is the temperature at which particle motion is minimum. To convert: °C = K − 273." },
  { id: "p-phys-heat-3", topic: "Heat & Thermodynamics",
    text: "Water is used as a coolant in car engines because it has:",
    options: ["A low boiling point", "A high specific heat capacity", "A high density", "A low freezing point"],
    correctIndex: 1,
    explanation: "Water absorbs a large amount of heat for each degree rise in temperature, so it carries heat away efficiently." },
  { id: "p-phys-heat-4", topic: "Heat & Thermodynamics",
    text: "In solids, heat is transferred mainly by:",
    options: ["Conduction", "Convection", "Radiation", "Reflection"],
    correctIndex: 0,
    explanation: "Solid particles only vibrate about fixed positions, passing energy to neighbours — conduction. Convection needs moving fluid." },
  { id: "p-phys-heat-5", topic: "Heat & Thermodynamics",
    text: "When ice melts at 0 °C, its temperature:",
    options: ["Keeps rising steadily", "Stays constant until all ice melts", "Falls slightly", "Doubles"],
    correctIndex: 1,
    explanation: "The heat supplied is used as latent heat to break the solid structure, so the thermometer stays at 0 °C until melting completes." },
  ],

  /* ── CHEMISTRY ──────────────────────────────────────────────────────────── */
  chemistry: [

  /* Atomic Structure */
  { id: "p-chem-atomic-1", topic: "Atomic Structure",
    text: "How many neutrons are present in ²³₁₁Na?",
    options: ["11", "12", "23", "34"],
    correctIndex: 1,
    explanation: "Mass number (23) = protons + neutrons. Neutrons = 23 − 11 = 12." },
  { id: "p-chem-atomic-2", topic: "Atomic Structure",
    text: "Isotopes of an element differ in their number of:",
    options: ["Protons", "Electrons", "Neutrons", "Energy shells"],
    correctIndex: 2,
    explanation: "Isotopes have the same atomic number (protons) but different numbers of neutrons, hence different mass numbers." },
  { id: "p-chem-atomic-3", topic: "Atomic Structure",
    text: "The maximum number of electrons the third shell (n = 3) can hold is:",
    options: ["8", "10", "18", "32"],
    correctIndex: 2,
    explanation: "The general formula is 2n². For n = 3: 2(3)² = 2(9) = 18 electrons." },
  { id: "p-chem-atomic-4", topic: "Atomic Structure",
    text: "The electron was discovered by:",
    options: ["Rutherford", "J. J. Thomson", "Chadwick", "Bohr"],
    correctIndex: 1,
    explanation: "J. J. Thomson discovered the electron using cathode-ray tubes (1897). Rutherford found the nucleus and proton; Chadwick found the neutron." },
  { id: "p-chem-atomic-5", topic: "Atomic Structure",
    text: "The electronic configuration of an atom with 11 electrons is:",
    options: ["2, 8, 1", "2, 9", "2, 8, 8", "1, 8, 2"],
    correctIndex: 0,
    explanation: "Shells fill from inside out: 2 in K, 8 in L, and the remaining 1 in M — giving 2, 8, 1 (sodium)." },

  /* Chemical Bonding */
  { id: "p-chem-bond-1", topic: "Chemical Bonding",
    text: "The bond present in sodium chloride (NaCl) is:",
    options: ["Ionic", "Non-polar covalent", "Metallic", "Hydrogen"],
    correctIndex: 0,
    explanation: "Sodium transfers its outer electron to chlorine, forming Na⁺ and Cl⁻ ions held together by electrostatic attraction." },
  { id: "p-chem-bond-2", topic: "Chemical Bonding",
    text: "The two nitrogen atoms in N₂ are joined by a:",
    options: ["Single covalent bond", "Double covalent bond", "Triple covalent bond", "Ionic bond"],
    correctIndex: 2,
    explanation: "Each nitrogen shares three electrons, making three shared pairs (a triple bond) so both atoms complete their octets." },
  { id: "p-chem-bond-3", topic: "Chemical Bonding",
    text: "The bonds between hydrogen and oxygen WITHIN a water molecule are:",
    options: ["Polar covalent", "Ionic", "Metallic", "Hydrogen bonds"],
    correctIndex: 0,
    explanation: "Oxygen attracts the shared electrons more strongly, so the O–H bonds are polar covalent. Hydrogen bonds act BETWEEN separate water molecules." },
  { id: "p-chem-bond-4", topic: "Chemical Bonding",
    text: "In the ammonium ion (NH₄⁺), the coordinate covalent bond is donated by:",
    options: ["Hydrogen", "Nitrogen", "Oxygen", "Chlorine"],
    correctIndex: 1,
    explanation: "Nitrogen's lone pair is donated to an H⁺ ion. In a coordinate bond, one atom supplies both shared electrons." },
  { id: "p-chem-bond-5", topic: "Chemical Bonding",
    text: "Which bond forms when atoms SHARE electrons?",
    options: ["Covalent", "Ionic", "Metallic", "Electrovalent"],
    correctIndex: 0,
    explanation: "Covalent bonding is sharing of electron pairs; ionic (electrovalent) bonding is a complete transfer of electrons." },

  /* States of Matter */
  { id: "p-chem-states-1", topic: "States of Matter",
    text: "Gases have:",
    options: ["Fixed shape and fixed volume", "Fixed shape but no fixed volume", "No fixed shape and no fixed volume", "Fixed volume but no fixed shape"],
    correctIndex: 2,
    explanation: "Gas particles move freely and completely fill their container, so gases take both the shape and the volume of the container." },
  { id: "p-chem-states-2", topic: "States of Matter",
    text: "Raising the temperature makes evaporation:",
    options: ["Slower", "Faster", "Unchanged", "Stop"],
    correctIndex: 1,
    explanation: "More molecules gain enough kinetic energy to escape the liquid surface, so evaporation speeds up." },
  { id: "p-chem-states-3", topic: "States of Matter",
    text: "Diffusion is fastest in:",
    options: ["Solids", "Liquids", "Gases", "Same in all three"],
    correctIndex: 2,
    explanation: "Gas particles move rapidly in random directions with large spaces between them, so gases mix (diffuse) fastest." },
  { id: "p-chem-states-4", topic: "States of Matter",
    text: "According to Boyle's law, at constant temperature, compressing a gas makes its pressure:",
    options: ["Decrease", "Increase", "Stay the same", "Become zero"],
    correctIndex: 1,
    explanation: "P ∝ 1/V at constant temperature: halving the volume doubles the pressure because the same molecules hit the walls more often." },
  { id: "p-chem-states-5", topic: "States of Matter",
    text: "During melting, a solid changes into a liquid. This change is called:",
    options: ["Fusion", "Vaporization", "Condensation", "Sublimation"],
    correctIndex: 0,
    explanation: "Melting (fusion) happens at the melting point. Sublimation is solid → gas directly, as with dry ice or iodine." },

  /* Stoichiometry */
  { id: "p-chem-stoich-1", topic: "Stoichiometry",
    text: "The molar mass of CO₂ (C = 12, O = 16) is:",
    options: ["28 g/mol", "32 g/mol", "44 g/mol", "48 g/mol"],
    correctIndex: 2,
    explanation: "C contributes 12 and two oxygens contribute 2 × 16 = 32, so CO₂ = 12 + 32 = 44 g/mol." },
  { id: "p-chem-stoich-2", topic: "Stoichiometry",
    text: "How many moles are there in 18 g of water (H₂O, molar mass 18)?",
    options: ["0.5", "1", "2", "18"],
    correctIndex: 1,
    explanation: "Moles = mass ÷ molar mass = 18 ÷ 18 = 1 mol." },
  { id: "p-chem-stoich-3", topic: "Stoichiometry",
    text: "One mole of any substance contains:",
    options: ["6.02 × 10²³ particles", "6.02 × 10⁻²³ particles", "3.01 × 10²³ particles", "1.6 × 10¹⁹ particles"],
    correctIndex: 0,
    explanation: "This is Avogadro's number (Nₐ = 6.02 × 10²³) — particles can be atoms, molecules or ions." },
  { id: "p-chem-stoich-4", topic: "Stoichiometry",
    text: "What is the mass of 0.5 mol of NaOH (molar mass 40 g/mol)?",
    options: ["10 g", "20 g", "40 g", "80 g"],
    correctIndex: 1,
    explanation: "Mass = moles × molar mass = 0.5 × 40 = 20 g." },
  { id: "p-chem-stoich-5", topic: "Stoichiometry",
    text: "In the balanced equation 2H₂ + O₂ → 2H₂O, how many moles of O₂ react with 4 moles of H₂?",
    options: ["1", "2", "4", "8"],
    correctIndex: 1,
    explanation: "The ratio is 2H₂ : 1O₂. For 4 mol H₂, oxygen needed = 4 × (1/2) = 2 mol." },

  /* Acids & Bases */
  { id: "p-chem-acids-1", topic: "Acids & Bases",
    text: "The pH of a neutral solution at 25 °C is:",
    options: ["0", "1", "7", "14"],
    correctIndex: 2,
    explanation: "pH 7 is neutral, below 7 is acidic and above 7 is basic (alkaline)." },
  { id: "p-chem-acids-2", topic: "Acids & Bases",
    text: "An acid reacts with a base to produce:",
    options: ["Salt and water", "Salt and hydrogen gas", "Water and carbon dioxide", "Hydrogen and oxygen"],
    correctIndex: 0,
    explanation: "This is neutralization: H⁺ from the acid combines with OH⁻ from the base to give water, leaving a salt. Hydrogen gas is released when acids react with metals." },
  { id: "p-chem-acids-3", topic: "Acids & Bases",
    text: "Which ion makes an aqueous solution acidic?",
    options: ["OH⁻", "Na⁺", "H⁺", "O²⁻"],
    correctIndex: 2,
    explanation: "Acids release H⁺ (often written H₃O⁺) in water. A high concentration of OH⁻ makes a solution basic instead." },
  { id: "p-chem-acids-4", topic: "Acids & Bases",
    text: "Which of the following is a strong base?",
    options: ["HCl", "CH₃COOH", "H₂SO₄", "NaOH"],
    correctIndex: 3,
    explanation: "NaOH (sodium hydroxide) ionizes completely in water. The other three are acids." },
  { id: "p-chem-acids-5", topic: "Acids & Bases",
    text: "Blue litmus paper turns red in:",
    options: ["A base", "An acid", "Pure water", "Common salt solution"],
    correctIndex: 1,
    explanation: "Acids turn blue litmus red; bases turn red litmus blue. Neutral solutions leave litmus unchanged." },

  /* Periodic Table Trends */
  { id: "p-chem-periodic-1", topic: "Periodic Table Trends",
    text: "Elements in the same group of the periodic table have the same:",
    options: ["Number of valence electrons", "Number of electron shells", "Atomic mass", "Number of neutrons"],
    correctIndex: 0,
    explanation: "Group number reflects the outer-shell electrons, which is why elements of a group show similar chemical behaviour." },
  { id: "p-chem-periodic-2", topic: "Periodic Table Trends",
    text: "Moving from left to right across a period, the atomic radius:",
    options: ["Increases", "Decreases", "Stays constant", "Doubles"],
    correctIndex: 1,
    explanation: "Nuclear charge increases while electrons enter the same shell, so the nucleus pulls the electrons closer and the atom shrinks." },
  { id: "p-chem-periodic-3", topic: "Periodic Table Trends",
    text: "The most reactive halogen is:",
    options: ["Fluorine", "Chlorine", "Bromine", "Iodine"],
    correctIndex: 0,
    explanation: "Halogens need one electron to complete their octet, and the smallest atom (fluorine) attracts it most strongly. Reactivity falls down the group." },
  { id: "p-chem-periodic-4", topic: "Periodic Table Trends",
    text: "Alkali metals are stored under oil because they:",
    options: ["React vigorously with air and moisture", "Become soft in air", "Have very low density", "Are noble metals"],
    correctIndex: 0,
    explanation: "Group 1 metals tarnish quickly and can ignite with air or water; the oil layer keeps air and moisture away." },
  { id: "p-chem-periodic-5", topic: "Periodic Table Trends",
    text: "Going down Group 1 (Li → Na → K …), reactivity:",
    options: ["Decreases", "Increases", "Remains the same", "First decreases then increases"],
    correctIndex: 1,
    explanation: "The outer electron is farther from the nucleus in bigger atoms, so it is lost more easily and the metal reacts more vigorously." },
  ],

  /* ── BIOLOGY ──────────────────────────────────────────────────────────── */
  biology: [

  /* Cell Structure */
  { id: "p-bio-cell-1", topic: "Cell Structure",
    text: "Which organelle is known as the “powerhouse of the cell”?",
    options: ["Ribosome", "Mitochondrion", "Nucleus", "Lysosome"],
    correctIndex: 1,
    explanation: "Mitochondria carry out respiration and release energy as ATP." },
  { id: "p-bio-cell-2", topic: "Cell Structure",
    text: "Proteins are synthesized at the:",
    options: ["Ribosome", "Mitochondrion", "Vacuole", "Cell membrane"],
    correctIndex: 0,
    explanation: "Ribosomes read mRNA and join amino acids into proteins — the reason they are found attached to rough endoplasmic reticulum and free in cytoplasm." },
  { id: "p-bio-cell-3", topic: "Cell Structure",
    text: "Which structure is found in plant cells but NOT in animal cells?",
    options: ["Cell wall", "Nucleus", "Mitochondrion", "Ribosome"],
    correctIndex: 0,
    explanation: "The cellulose cell wall (and chloroplasts) are plant-only. Nuclei, mitochondria and ribosomes occur in both cell types." },
  { id: "p-bio-cell-4", topic: "Cell Structure",
    text: "The control centre of the cell is the:",
    options: ["Cytoplasm", "Nucleus", "Vacuole", "Cell membrane"],
    correctIndex: 1,
    explanation: "The nucleus contains DNA and directs all cell activities including growth and division." },
  { id: "p-bio-cell-5", topic: "Cell Structure",
    text: "Which organelle would be MOST abundant in a cell that secretes enzymes?",
    options: ["Rough endoplasmic reticulum", "Cell wall", "Central vacuole", "Chloroplast"],
    correctIndex: 0,
    explanation: "Secretory cells need lots of rough ER (with ribosomes) to build proteins for export, plus Golgi bodies to package them." },

  /* Biological Molecules */
  { id: "p-bio-mol-1", topic: "Biological Molecules",
    text: "The monomers (building blocks) of proteins are:",
    options: ["Glucose", "Amino acids", "Fatty acids", "Nucleotides"],
    correctIndex: 1,
    explanation: "Amino acids join by peptide bonds to form polypeptides (proteins)." },
  { id: "p-bio-mol-2", topic: "Biological Molecules",
    text: "A DNA nucleotide is made of:",
    options: ["Sugar, phosphate and a nitrogenous base", "Two amino acids", "Glycerol and three fatty acids", "Glucose molecules only"],
    correctIndex: 0,
    explanation: "Every nucleotide has deoxyribose sugar, a phosphate group and one of four bases (A, T, G, C)." },
  { id: "p-bio-mol-3", topic: "Biological Molecules",
    text: "Lipids (fats) are built from:",
    options: ["Amino acids", "Nucleotides", "Glycerol and fatty acids", "Glucose units"],
    correctIndex: 2,
    explanation: "One glycerol joins three fatty acid chains to form a triglyceride." },
  { id: "p-bio-mol-4", topic: "Biological Molecules",
    text: "Which of these is a monosaccharide?",
    options: ["Sucrose", "Starch", "Glycogen", "Glucose"],
    correctIndex: 3,
    explanation: "Glucose is a single sugar unit. Sucrose is a disaccharide; starch and glycogen are polysaccharides." },
  { id: "p-bio-mol-5", topic: "Biological Molecules",
    text: "Which test detects the presence of starch?",
    options: ["Iodine test", "Benedict's test", "Biuret test", "Alcohol test"],
    correctIndex: 0,
    explanation: "Iodine turns blue-black with starch. Benedict's tests reducing sugars and Biuret tests proteins." },

  /* Enzymes */
  { id: "p-bio-enz-1", topic: "Enzymes",
    text: "Enzymes are best described as:",
    options: ["Proteins that catalyse reactions", "Lipids that store energy", "Carbohydrates that build cell walls", "Minerals absorbed by roots"],
    correctIndex: 0,
    explanation: "Enzymes are globular proteins that speed up reactions without being used up themselves." },
  { id: "p-bio-enz-2", topic: "Enzymes",
    text: "At very high temperatures enzymes:",
    options: ["Work faster and faster", "Are denatured", "Turn into substrates", "Become acids"],
    correctIndex: 1,
    explanation: "Excess heat breaks the bonds holding the 3-D shape, so the active site is destroyed (denaturation) and activity stops." },
  { id: "p-bio-enz-3", topic: "Enzymes",
    text: "The substrate of an enzyme binds at its:",
    options: ["Active site", "Product site", "Cell wall", "Peptide bond"],
    correctIndex: 0,
    explanation: "The substrate fits the active site like a key fits a lock (lock-and-key model)." },
  { id: "p-bio-enz-4", topic: "Enzymes",
    text: "Amylase digests:",
    options: ["Protein", "Starch", "Fat", "Vitamins"],
    correctIndex: 1,
    explanation: "Amylase breaks starch into simpler sugars such as maltose. Digestion of starch begins in the mouth." },
  { id: "p-bio-enz-5", topic: "Enzymes",
    text: "Enzymes are described as “specific” because they:",
    options: ["Work on one particular substrate", "Work only in the stomach", "Can be reused as food", "Need no energy"],
    correctIndex: 0,
    explanation: "The shape of the active site matches only its own substrate — one enzyme, one reaction type." },

  /* Human Digestion */
  { id: "p-bio-dig-1", topic: "Human Digestion",
    text: "The enzyme present in saliva is:",
    options: ["Pepsin", "Trypsin", "Lipase", "Salivary amylase"],
    correctIndex: 3,
    explanation: "Salivary amylase starts starch digestion in the mouth. Pepsin and trypsin digest protein later in the tract." },
  { id: "p-bio-dig-2", topic: "Human Digestion",
    text: "Most digested food is absorbed in the:",
    options: ["Stomach", "Small intestine", "Large intestine", "Oesophagus"],
    correctIndex: 1,
    explanation: "The small intestine is long with villi that give a huge absorptive surface; the large intestine mainly absorbs water." },
  { id: "p-bio-dig-3", topic: "Human Digestion",
    text: "Hydrochloric acid in gastric juice:",
    options: ["Provides an acidic medium and kills germs", "Emulsifies fats", "Absorbs water", "Neutralizes bile"],
    correctIndex: 0,
    explanation: "HCl activates pepsinogen into pepsin, gives the low pH the enzyme needs, and destroys harmful microbes in food." },
  { id: "p-bio-dig-4", topic: "Human Digestion",
    text: "Bile is produced by the:",
    options: ["Gallbladder", "Pancreas", "Liver", "Stomach"],
    correctIndex: 2,
    explanation: "The liver makes bile; the gallbladder only stores it and releases it into the small intestine." },
  { id: "p-bio-dig-5", topic: "Human Digestion",
    text: "Bile helps digestion by:",
    options: ["Emulsifying fats into tiny droplets", "Chemically breaking proteins", "Absorbing vitamins directly", "Killing bacteria"],
    correctIndex: 0,
    explanation: "Bile salts break large fat drops into an emulsion, hugely increasing the surface area lipase can work on. Bile contains no enzyme." },

  /* Reproduction */
  { id: "p-bio-repro-1", topic: "Reproduction",
    text: "In humans, the male gamete is the:",
    options: ["Ovum", "Sperm", "Zygote", "Embryo"],
    correctIndex: 1,
    explanation: "The sperm (male gamete) fuses with the ovum (female gamete). The zygote is the fused product." },
  { id: "p-bio-repro-2", topic: "Reproduction",
    text: "Fertilization in humans normally occurs in the:",
    options: ["Ovary", "Uterus", "Fallopian tube", "Vagina"],
    correctIndex: 2,
    explanation: "Sperm meets the ovum in the fallopian tube (oviduct); the zygote then travels to the uterus for implantation." },
  { id: "p-bio-repro-3", topic: "Reproduction",
    text: "The male part of a flower is the:",
    options: ["Carpel", "Stamen", "Petal", "Sepal"],
    correctIndex: 1,
    explanation: "The stamen (anther + filament) produces pollen. The carpel is the female part." },
  { id: "p-bio-repro-4", topic: "Reproduction",
    text: "A zygote is formed by:",
    options: ["Meiosis of an ovum", "Mitosis of a sperm", "Fusion of male and female gametes", "Budding"],
    correctIndex: 2,
    explanation: "Fertilization — the fusion of the two gamete nuclei — restores the diploid number and produces the zygote." },
  { id: "p-bio-repro-5", topic: "Reproduction",
    text: "Identical twins develop when:",
    options: ["Two eggs are released and fertilized", "One zygote splits into two embryos", "Two sperm fertilize one egg", "The placenta doubles"],
    correctIndex: 1,
    explanation: "A single fertilized egg dividing into two gives identical (same-sex, same genes) twins. Two separate eggs give non-identical twins." },

  /* Ecosystem & Environment */
  { id: "p-bio-eco-1", topic: "Ecosystem & Environment",
    text: "Organisms that make their own food are called:",
    options: ["Producers", "Primary consumers", "Decomposers", "Parasites"],
    correctIndex: 0,
    explanation: "Producers (autotrophs) such as green plants build food by photosynthesis and feed every other level." },
  { id: "p-bio-eco-2", topic: "Ecosystem & Environment",
    text: "The ultimate energy source for almost every ecosystem is:",
    options: ["Soil", "Water", "The Sun", "Wind"],
    correctIndex: 2,
    explanation: "Producers trap sunlight in photosynthesis, and that energy then flows through the food chain." },
  { id: "p-bio-eco-3", topic: "Ecosystem & Environment",
    text: "Decomposers break down:",
    options: ["Only green plants", "Dead and decaying organisms", "Carnivores only", "Inorganic minerals"],
    correctIndex: 1,
    explanation: "Bacteria and fungi decay dead material, returning nutrients to the soil for reuse by plants." },
  { id: "p-bio-eco-4", topic: "Ecosystem & Environment",
    text: "A food chain always begins with:",
    options: ["Producers", "Herbivores", "Carnivores", "Decomposers"],
    correctIndex: 0,
    explanation: "Energy enters the chain at the producer level, e.g. grass → grasshopper → frog → snake." },
  { id: "p-bio-eco-5", topic: "Ecosystem & Environment",
    text: "In the carbon cycle, plants return carbon dioxide to the atmosphere mainly through:",
    options: ["Photosynthesis", "Respiration", "Transpiration", "Nitrogen fixation"],
    correctIndex: 1,
    explanation: "Respiration releases CO₂. Photosynthesis works the other way — it removes CO₂ from the atmosphere." },
  ],

  /* ── ENGLISH ─────────────────────────────────────────────────────────────── */
  english: [

  /* Grammar Foundations */
  { id: "p-eng-grammar-1", topic: "Grammar Foundations",
    text: "Choose the correct form: “She ___ to school every day.”",
    options: ["go", "goes", "going", "gone"],
    correctIndex: 1,
    explanation: "The subject “she” is third-person singular, so the present simple verb takes -s/-es: goes." },
  { id: "p-eng-grammar-2", topic: "Grammar Foundations",
    text: "“The train ___ before we reached the station.” Choose the correct tense.",
    options: ["has left", "had left", "leaves", "is leaving"],
    correctIndex: 1,
    explanation: "The action happened before another past action, so the past perfect (had left) is required." },
  { id: "p-eng-grammar-3", topic: "Grammar Foundations",
    text: "Identify the adverb: “She sings beautifully.”",
    options: ["She", "sings", "beautifully", "none of these"],
    correctIndex: 2,
    explanation: "“Beautifully” tells HOW she sings — an adverb modifies the verb." },
  { id: "p-eng-grammar-4", topic: "Grammar Foundations",
    text: "Which sentence is grammatically correct?",
    options: ["He is working since morning.", "He works since morning.", "He has been working since morning.", "He have been working since morning."],
    correctIndex: 2,
    explanation: "“Since” points to a starting time, so present perfect continuous is needed, and singular “he” takes “has” (not “have”)." },
  { id: "p-eng-grammar-5", topic: "Grammar Foundations",
    text: "Choose the correct passive voice of: “Ali wrote a letter.”",
    options: ["A letter was written by Ali.", "A letter is written by Ali.", "A letter written by Ali.", "A letter has wrote by Ali."],
    correctIndex: 0,
    explanation: "Past simple passive = was/were + past participle: was written." },

  /* Comprehension */
  { id: "p-eng-comp-1", topic: "Comprehension",
    text: "The topic sentence of a paragraph usually states:",
    options: ["The main idea", "An example", "A quotation", "The conclusion of the essay"],
    correctIndex: 0,
    explanation: "The topic sentence announces what the paragraph is about; supporting sentences then explain or prove it." },
  { id: "p-eng-comp-2", topic: "Comprehension",
    text: "Skimming a passage means:",
    options: ["Reading quickly for the general idea", "Reading every word slowly", "Looking up every new word", "Reading only the title"],
    correctIndex: 0,
    explanation: "Skimming = fast reading for the overall gist; scanning = searching for specific details." },
  { id: "p-eng-comp-3", topic: "Comprehension",
    text: "Scanning is used to:",
    options: ["Find specific information quickly", "Enjoy the writer's style", "Improve pronunciation", "Memorize the passage"],
    correctIndex: 0,
    explanation: "You scan for a name, date or figure your eyes can jump to — not for overall meaning." },
  { id: "p-eng-comp-4", topic: "Comprehension",
    text: "The tone of a passage refers to:",
    options: ["The writer's attitude toward the subject", "The number of paragraphs", "The length of sentences", "The rhyme scheme"],
    correctIndex: 0,
    explanation: "Tone is conveyed through word choice — angry, humorous, serious, ironic and so on." },
  { id: "p-eng-comp-5", topic: "Comprehension",
    text: "“The author implies that…” means the writer has stated something:",
    options: ["Directly, in clear words", "Indirectly, through hints", "In a footnote", "In another book"],
    correctIndex: 1,
    explanation: "Implying is suggesting without saying openly — the reader must infer it." },

  /* Essay Writing */
  { id: "p-eng-essay-1", topic: "Essay Writing",
    text: "The thesis statement of an essay normally appears:",
    options: ["At the end of the introduction", "In the middle of the body", "At the start of the conclusion", "In the title"],
    correctIndex: 0,
    explanation: "The introduction ends with the thesis — the one sentence that states your whole argument." },
  { id: "p-eng-essay-2", topic: "Essay Writing",
    text: "Each body paragraph should open with:",
    options: ["A topic sentence", "A quotation", "A question", "A summary"],
    correctIndex: 0,
    explanation: "The topic sentence states the paragraph's point; the rest of the paragraph supports it." },
  { id: "p-eng-essay-3", topic: "Essay Writing",
    text: "A good introduction should:",
    options: ["Grab the reader's interest and introduce the topic", "List all your references", "Give the strongest argument in full detail", "Apologize for the essay"],
    correctIndex: 0,
    explanation: "Hook + background + thesis: that is the shape of an effective introduction." },
  { id: "p-eng-essay-4", topic: "Essay Writing",
    text: "The conclusion of an essay should:",
    options: ["Restate the thesis and summarize the main points", "Introduce a brand-new argument", "End mid-sentence for suspense", "Repeat the introduction word for word"],
    correctIndex: 0,
    explanation: "The conclusion closes the circle: restate the thesis in fresh words and pull the points together." },
  { id: "p-eng-essay-5", topic: "Essay Writing",
    text: "An outline is prepared before writing an essay because it:",
    options: ["Organizes ideas in logical order", "Makes the essay longer", "Replaces the conclusion", "Is required by printers"],
    correctIndex: 0,
    explanation: "Planning the order of points first keeps the essay coherent and prevents repetition." },

  /* Précis Writing */
  { id: "p-eng-precis-1", topic: "Précis Writing",
    text: "A précis is usually about ___ of the original passage in length.",
    options: ["One-third", "The same length", "Double", "Ten times"],
    correctIndex: 0,
    explanation: "The classic rule: compress the passage to roughly one-third while keeping every essential idea." },
  { id: "p-eng-precis-2", topic: "Précis Writing",
    text: "A précis must be written:",
    options: ["In your own words", "By copying the best sentences", "In verse form", "As a dialogue"],
    correctIndex: 0,
    explanation: "Copying sentences defeats the purpose — a précis compresses the ideas in fresh, simple words." },
  { id: "p-eng-precis-3", topic: "Précis Writing",
    text: "The title of a précis should be:",
    options: ["Short and reflecting the main theme", "Long and descriptive", "The first line of the passage", "The writer's name"],
    correctIndex: 0,
    explanation: "A good title captures the central idea in a few words." },
  { id: "p-eng-precis-4", topic: "Précis Writing",
    text: "Which of these should be LEFT OUT of a précis?",
    options: ["The central idea", "Your personal opinions and extra examples", "Key facts of the passage", "The conclusion drawn by the author"],
    correctIndex: 1,
    explanation: "A précis is faithful to the original — nothing personal and nothing invented may enter it." },
  { id: "p-eng-precis-5", topic: "Précis Writing",
    text: "A précis is generally written in:",
    options: ["The third person, reported style", "The first person", "Direct speech", "Question form"],
    correctIndex: 0,
    explanation: "Even if the original says “I”, the précis reports it indirectly in the third person." },

  /* Letter & Application Writing */
  { id: "p-eng-letter-1", topic: "Letter & Application Writing",
    text: "When the recipient's name is unknown, the salutation should be:",
    options: ["Dear friend", "Dear Sir/Madam", "Respected brother", "Hello there"],
    correctIndex: 1,
    explanation: "Formal letters to an unnamed recipient use “Dear Sir/Madam” — matched with “Yours faithfully” at the close." },
  { id: "p-eng-letter-2", topic: "Letter & Application Writing",
    text: "“Yours faithfully” is used when you:",
    options: ["Know the recipient's name", "Do not know the recipient's name", "Write to a close friend", "End an essay"],
    correctIndex: 1,
    explanation: "Sir/Madam → Yours faithfully; named recipient → Yours sincerely." },
  { id: "p-eng-letter-3", topic: "Letter & Application Writing",
    text: "An application to the Principal should be written in:",
    options: ["A formal, respectful tone", "A casual, chatty tone", "Poetic language", "SMS abbreviations"],
    correctIndex: 0,
    explanation: "Applications are formal documents: respectful address, brief subject line, and a courteous request." },
  { id: "p-eng-letter-4", topic: "Letter & Application Writing",
    text: "Which is a suitable closing for a formal letter?",
    options: ["Lots of love", "See ya!", "Yours faithfully", "Bye bye"],
    correctIndex: 2,
    explanation: "Closings like “Yours faithfully/sincerely” match formal letters; friendly closings suit personal letters only." },
  { id: "p-eng-letter-5", topic: "Letter & Application Writing",
    text: "A personal (informal) letter is written to:",
    options: ["The Principal", "A government office", "Friends and family", "A newspaper editor"],
    correctIndex: 2,
    explanation: "Informal letters go to people you know well, so the tone is friendly and the format is relaxed." },

  /* Vocabulary Building */
  { id: "p-eng-vocab-1", topic: "Vocabulary Building",
    text: "Choose the synonym of “abundant”.",
    options: ["Scarce", "Plentiful", "Tiny", "Rare"],
    correctIndex: 1,
    explanation: "Abundant = existing in large quantity, i.e. plentiful. Scarce and rare are antonyms." },
  { id: "p-eng-vocab-2", topic: "Vocabulary Building",
    text: "Choose the antonym of “ancient”.",
    options: ["Old", "Historic", "Modern", "Antique"],
    correctIndex: 2,
    explanation: "Ancient = very old, so its opposite is modern. Old, historic and antique are synonyms." },
  { id: "p-eng-vocab-3", topic: "Vocabulary Building",
    text: "“Benevolent” means:",
    options: ["Cruel", "Lazy", "Greedy", "Kind and generous"],
    correctIndex: 3,
    explanation: "Bene- means good (as in benefit, benign): a benevolent person wishes others well." },
  { id: "p-eng-vocab-4", topic: "Vocabulary Building",
    text: "A lexicographer is a person who:",
    options: ["Compiles dictionaries", "Studies rocks", "Sells books", "Maps land"],
    correctIndex: 0,
    explanation: "Lexico- relates to words (lexicon = dictionary); a lexicographer writes or edits dictionaries." },
  { id: "p-eng-vocab-5", topic: "Vocabulary Building",
    text: "Choose the word closest in meaning to “commence”.",
    options: ["Finish", "Begin", "Delay", "Cancel"],
    correctIndex: 1,
    explanation: "Commence is a formal word for begin — as in “the ceremony will commence at 9 a.m.”" },
  ],

  /* ── COMPUTER SCIENCE ───────────────────────────────────────────────────── */
  computer: [

  /* Computer Fundamentals */
  { id: "p-comp-fund-1", topic: "Computer Fundamentals",
    text: "Which part of the computer is called its “brain”?",
    options: ["RAM", "CPU", "Hard disk", "Monitor"],
    correctIndex: 1,
    explanation: "The CPU (Central Processing Unit) performs calculations and controls all other units." },
  { id: "p-comp-fund-2", topic: "Computer Fundamentals",
    text: "RAM is called volatile memory because it:",
    options: ["Keeps data permanently", "Loses data when power is switched off", "Cannot be written to", "Stores data on disk"],
    correctIndex: 1,
    explanation: "Volatile = contents vanish when the power goes. ROM, by contrast, is non-volatile." },
  { id: "p-comp-fund-3", topic: "Computer Fundamentals",
    text: "1 kilobyte (KB) equals:",
    options: ["1000 bytes", "512 bytes", "1024 bytes", "2048 bytes"],
    correctIndex: 2,
    explanation: "In computing, units step by powers of 2: 1 KB = 2¹⁰ = 1024 bytes." },
  { id: "p-comp-fund-4", topic: "Computer Fundamentals",
    text: "Which of these is an input device?",
    options: ["Monitor", "Printer", "Speaker", "Keyboard"],
    correctIndex: 3,
    explanation: "Input devices feed data INTO the computer. Monitors, printers and speakers are output devices." },
  { id: "p-comp-fund-5", topic: "Computer Fundamentals",
    text: "Which memory is directly accessible by the CPU?",
    options: ["Hard disk", "USB flash drive", "RAM", "DVD"],
    correctIndex: 2,
    explanation: "The CPU works with main memory (RAM). Secondary storage (disk, USB, DVD) is accessed via input/output channels." },

  /* Programming Basics */
  { id: "p-comp-prog-1", topic: "Programming Basics",
    text: "In programming, a variable is:",
    options: ["A fixed value that never changes", "A named memory location that stores a value", "A type of printer", "A program error"],
    correctIndex: 1,
    explanation: "A variable names a spot in memory whose contents can be read and changed while the program runs." },
  { id: "p-comp-prog-2", topic: "Programming Basics",
    text: "Which of the following is NOT a programming language?",
    options: ["Python", "C++", "HTML", "Java"],
    correctIndex: 2,
    explanation: "HTML is a markup language used to structure web pages — it has no logic constructs like loops or conditions." },
  { id: "p-comp-prog-3", topic: "Programming Basics",
    text: "If x = 5, what is stored in y after: y = x + 3?",
    options: ["53", "8", "5", "3"],
    correctIndex: 1,
    explanation: "The + performs numeric addition: 5 + 3 = 8." },
  { id: "p-comp-prog-4", topic: "Programming Basics",
    text: "The % (modulus) operator returns:",
    options: ["The quotient", "The remainder", "The product", "The average"],
    correctIndex: 1,
    explanation: "7 % 2 = 1 because 7 ÷ 2 is 3 remainder 1 — handy for testing even/odd numbers." },
  { id: "p-comp-prog-5", topic: "Programming Basics",
    text: "Which structure repeats a block of code while a condition stays true?",
    options: ["if statement", "loop", "variable", "comment"],
    correctIndex: 1,
    explanation: "Loops (for, while) repeat code; an if statement chooses between paths but does not repeat." },

  /* Flowcharts & Algorithms */
  { id: "p-comp-flow-1", topic: "Flowcharts & Algorithms",
    text: "The diamond symbol in a flowchart represents:",
    options: ["Input/Output", "A process", "A decision", "Start/Stop"],
    correctIndex: 2,
    explanation: "Diamonds ask yes/no questions and branch the flow. Rectangles are processes; parallelograms are input/output." },
  { id: "p-comp-flow-2", topic: "Flowcharts & Algorithms",
    text: "An algorithm is:",
    options: ["A programming language", "A finite set of steps to solve a problem", "A type of computer", "A flowchart symbol"],
    correctIndex: 1,
    explanation: "An algorithm is a precise, ordered, finite procedure that leads to a solution." },
  { id: "p-comp-flow-3", topic: "Flowcharts & Algorithms",
    text: "The oval (rounded rectangle) symbol in a flowchart marks:",
    options: ["Start/Stop", "Processing", "Decision", "Connector"],
    correctIndex: 0,
    explanation: "Ovals terminate the flowchart — every flowchart begins and ends with them." },
  { id: "p-comp-flow-4", topic: "Flowcharts & Algorithms",
    text: "The parallelogram symbol represents:",
    options: ["Decision", "Input/Output", "Process", "Flow direction"],
    correctIndex: 1,
    explanation: "Data entering or leaving the process (READ, PRINT) is drawn as a parallelogram." },
  { id: "p-comp-flow-5", topic: "Flowcharts & Algorithms",
    text: "Arrows in a flowchart show:",
    options: ["The order of steps", "The data types", "The variables", "Memory addresses"],
    correctIndex: 0,
    explanation: "Arrows connect the symbols and define the sequence in which steps execute." },

  /* Data Representation */
  { id: "p-comp-data-1", topic: "Data Representation",
    text: "The binary equivalent of decimal 5 is:",
    options: ["100", "101", "110", "111"],
    correctIndex: 1,
    explanation: "5 = 4 + 1 = 1×2² + 0×2¹ + 1×2⁰ → 101." },
  { id: "p-comp-data-2", topic: "Data Representation",
    text: "The decimal equivalent of binary 1011 is:",
    options: ["9", "10", "11", "13"],
    correctIndex: 2,
    explanation: "1×8 + 0×4 + 1×2 + 1×1 = 8 + 0 + 2 + 1 = 11." },
  { id: "p-comp-data-3", topic: "Data Representation",
    text: "One hexadecimal digit is represented by how many bits?",
    options: ["2", "4", "8", "16"],
    correctIndex: 1,
    explanation: "Hex uses 16 symbols (0–9, A–F), and 2⁴ = 16, so each hex digit maps to exactly 4 bits." },
  { id: "p-comp-data-4", topic: "Data Representation",
    text: "ASCII code is used to represent:",
    options: ["Only numbers", "Text characters", "Sound waves", "Colours"],
    correctIndex: 1,
    explanation: "ASCII assigns a numeric code to each letter, digit and symbol, e.g. A = 65." },
  { id: "p-comp-data-5", topic: "Data Representation",
    text: "Why do computers use the binary system?",
    options: ["It is faster to read", "Hardware has two stable states (on/off)", "It uses fewer digits to write", "It was invented first"],
    correctIndex: 1,
    explanation: "Electronic circuits reliably distinguish only two voltage levels, which map naturally onto 0 and 1." },

  /* Databases Intro */
  { id: "p-comp-db-1", topic: "Databases Intro",
    text: "A row in a database table is called a:",
    options: ["Field", "Record", "File", "Query"],
    correctIndex: 1,
    explanation: "A record (tuple) holds all the data about one item; a field (column) holds one attribute." },
  { id: "p-comp-db-2", topic: "Databases Intro",
    text: "A column in a database table is called a:",
    options: ["Record", "Field", "Table", "Row"],
    correctIndex: 1,
    explanation: "Fields describe attributes — Name, Roll No, Marks — and every record supplies a value for each field." },
  { id: "p-comp-db-3", topic: "Databases Intro",
    text: "A primary key:",
    options: ["May contain duplicate values", "Uniquely identifies each record", "Is always text", "Is the same as a foreign key"],
    correctIndex: 1,
    explanation: "The primary key is unique for every record — like a roll number — so any row can be found without ambiguity." },
  { id: "p-comp-db-4", topic: "Databases Intro",
    text: "Which SQL command is used to retrieve data?",
    options: ["INSERT", "UPDATE", "DELETE", "SELECT"],
    correctIndex: 3,
    explanation: "SELECT reads data (e.g. SELECT * FROM students). INSERT adds, UPDATE changes and DELETE removes rows." },
  { id: "p-comp-db-5", topic: "Databases Intro",
    text: "Which command removes the entire table along with its data?",
    options: ["DELETE", "DROP", "SELECT", "UPDATE"],
    correctIndex: 1,
    explanation: "DROP TABLE removes the table itself; DELETE only removes rows but keeps the table structure." },

  /* Networking Basics */
  { id: "p-comp-net-1", topic: "Networking Basics",
    text: "WWW stands for:",
    options: ["World Wide Web", "Wide World Web", "World Wireless Web", "Web World Wide"],
    correctIndex: 0,
    explanation: "The World Wide Web is the collection of linked web pages accessed via the Internet." },
  { id: "p-comp-net-2", topic: "Networking Basics",
    text: "LAN stands for:",
    options: ["Large Area Network", "Local Area Network", "Long Access Network", "Local Access Node"],
    correctIndex: 1,
    explanation: "A LAN connects devices within a small area like a school lab; WAN spans cities or countries." },
  { id: "p-comp-net-3", topic: "Networking Basics",
    text: "An IP address identifies:",
    options: ["A web browser", "A device on a network", "A keyboard", "A password"],
    correctIndex: 1,
    explanation: "Every device on a network gets a unique IP address (e.g. 192.168.1.5) so data reaches the right machine." },
  { id: "p-comp-net-4", topic: "Networking Basics",
    text: "HTTP is a protocol used for:",
    options: ["Transferring web pages", "Sending emails only", "Printing documents", "Scanning images"],
    correctIndex: 0,
    explanation: "HyperText Transfer Protocol moves web content between servers and browsers; email uses SMTP/POP instead." },
  { id: "p-comp-net-5", topic: "Networking Basics",
    text: "Which device connects different networks together and routes data between them?",
    options: ["Hub", "Router", "Monitor", "Scanner"],
    correctIndex: 1,
    explanation: "A router forwards packets between networks (e.g. your LAN to the Internet); a hub only repeats signals inside one network." },
  ],

  /* ── URDU ───────────────────────────────────────────────────────────── */
  urdu: [

  /* نثر (Prose) */
  { id: "p-urdu-nasr-1", topic: "نثر (Prose)",
    text: "نثر کی بنیادی پہچان کیا ہے؟",
    options: ["بغیر وزن اور قافیے کی تحریر", "وزن اور قافیے کی پابند تحریر", "صرف منظوم کلام", "صرف مکالمے"],
    correctIndex: 0,
    explanation: "نثر وہ تحریر ہے جس میں وزن اور قافیے کی پابندی نہیں ہوتی؛ یہ قدرتی بول چال کے قریب ہوتی ہے۔" },
  { id: "p-urdu-nasr-2", topic: "نثر (Prose)",
    text: "”افسانہ“ کس صنفِ ادب میں شامل ہے؟",
    options: ["نظم", "نثر", "مرثیہ", "قصیدہ"],
    correctIndex: 1,
    explanation: "افسانہ مختصر کہانی ہے جو نثر میں لکھی جاتی ہے اور اس میں کردار اور پلاٹ ہوتے ہیں۔" },
  { id: "p-urdu-nasr-3", topic: "نثر (Prose)",
    text: "”خاکہ“ کیا ہوتا ہے؟",
    options: ["کسی شخص کی شخصیت کا مختصر بیان", "کسی جگہ کا منظر نامہ", "کسی کتاب کا خلاصہ", "کسی نظم کی تشریح"],
    correctIndex: 0,
    explanation: "خاکہ نگاری میں کسی شخص کی خوبیوں اور خصائص کا مختصر اور موثر بیان ہوتا ہے۔" },
  { id: "p-urdu-nasr-4", topic: "نثر (Prose)",
    text: "اچھی نثر کی سب سے بڑی خوبی کیا ہے؟",
    options: ["بھاری اور مشکل الفاظ", "سادگی اور وضاحت", "لمبے لمبے جملے", "غیر مربوط بات"],
    correctIndex: 1,
    explanation: "اچھی نثر سادہ، واضح اور رواں ہوتی ہے تاکہ قاری آسانی سے مطلب سمجھ سکے۔" },
  { id: "p-urdu-nasr-5", topic: "نثر (Prose)",
    text: "”مضمون“ میں مصنف عموماً کیا کرتا ہے؟",
    options: ["صرف کہانی سناتا ہے", "شاعری کرتا ہے", "کسی موضوع پر دلائل کے ساتھ اپنی رائے پیش کرتا ہے", "خط لکھتا ہے"],
    correctIndex: 2,
    explanation: "مضمون میں کسی موضوع کے مختلف پہلوؤں پر منطقی ترتیب سے بحث کی جاتی ہے۔" },

  /* نظم (Poetry) */
  { id: "p-urdu-nazm-1", topic: "نظم (Poetry)",
    text: "خالص نظم میں کون سی چیز لازم ہے؟",
    options: ["صرف وزن", "وزن اور قافیہ دونوں", "صرف قافیہ", "کوئی نہیں"],
    correctIndex: 0,
    explanation: "نظم میں وزن تو لازم ہے مگر قافیے کی پابندی نہیں ہوتی — یہی اسے غزل سے مختلف کرتا ہے۔" },
  { id: "p-urdu-nazm-2", topic: "نظم (Poetry)",
    text: "”بحر“ سے کیا مراد ہے؟",
    options: ["شاعری کا وزن", "شعر کا آخری لفظ", "شاعر کا تخلص", "نظم کا عنوان"],
    correctIndex: 0,
    explanation: "بحر وہ وزن یا تال ہے جس پر پورا کلام ہوتا ہے۔" },
  { id: "p-urdu-nazm-3", topic: "نظم (Poetry)",
    text: "”ردیف“ کیا ہے؟",
    options: ["قافیے کے بعد بار بار آنے والے یکساں الفاظ", "پہلا مصرعہ", "شعر کا مطلب", "شاعر کا قلمی نام"],
    correctIndex: 0,
    explanation: "جیسے ہر شعر کے آخر میں ”ہے“ یا ”کے“ دہرایا جائے تو وہ ردیف کہلاتا ہے؛ اس سے پہلے ہم آواز لفظ قافیہ ہے۔" },
  { id: "p-urdu-nazm-4", topic: "نظم (Poetry)",
    text: "غزل کے اشعار عام طور پر کیسے ہوتے ہیں؟",
    options: ["تمام اشعار ایک ہی کہانی سناتے ہیں", "ہر شعر اپنا الگ موضوع رکھ سکتا ہے", "غزل میں صرف ایک شعر ہوتا ہے", "غزل نثر میں لکھی جاتی ہے"],
    correctIndex: 1,
    explanation: "غزل کے اشعار باہم لازم مربوط نہیں ہوتے؛ ہر شعر اپنا الگ مضمون رکھ سکتا ہے۔" },
  { id: "p-urdu-nazm-5", topic: "نظم (Poetry)",
    text: "”شعر“ اور ”مصرعہ“ میں کیا فرق ہے؟",
    options: ["شعر ایک سطر ہے، مصرعہ دو", "شعر دو مصرعوں پر مشتمل ہوتا ہے", "دونوں ایک ہی ہیں", "مصرعہ صرف نثر میں ہوتا ہے"],
    correctIndex: 1,
    explanation: "ایک شعر عموماً دو مصرعوں (سطروں) پر مشتمل ہوتا ہے۔" },

  /* قواعد (Grammar) */
  { id: "p-urdu-qawaid-1", topic: "قواعد (Grammar)",
    text: "”اسم“ کیا ہوتا ہے؟",
    options: ["کام کا نام", "کسی شخص، جگہ یا چیز کا نام", "صفت کا نام", "حرف کا نام"],
    correctIndex: 1,
    explanation: "اسم وہ لفظ ہے جو کسی شخص، جگہ یا چیز کے نام کو ظاہر کرے، جیسے احمد، لاہور، کتاب۔" },
  { id: "p-urdu-qawaid-2", topic: "قواعد (Grammar)",
    text: "”وہ پڑھتا ہے“ میں ”پڑھتا ہے“ کیا ہے؟",
    options: ["اسم", "صفت", "فعل", "ضمیر"],
    correctIndex: 2,
    explanation: "فعل وہ لفظ ہے جس سے کوئی کام کرنے یا ہونے کا علم ہو۔" },
  { id: "p-urdu-qawaid-3", topic: "قواعد (Grammar)",
    text: "”خوبصورت لڑکا“ میں ”خوبصورت“ کیا ہے؟",
    options: ["اسم", "فعل", "ضمیر", "صفت"],
    correctIndex: 3,
    explanation: "صفت وہ لفظ ہے جو اسم کی خوبی، خامی یا کیفیت بتائے۔" },
  { id: "p-urdu-qawaid-4", topic: "قواعد (Grammar)",
    text: "”وہ آیا“ میں ”وہ“ کیا ہے؟",
    options: ["ضمیر", "اسم", "فعل", "صفت"],
    correctIndex: 0,
    explanation: "ضمیر وہ لفظ ہے جو کسی اسم کی جگہ استعمال ہو، جیسے وہ، یہ، تم۔" },
  { id: "p-urdu-qawaid-5", topic: "قواعد (Grammar)",
    text: "”آہستہ آہستہ چل دو“ میں ”آہستہ آہستہ“ کیا ہے؟",
    options: ["اسم", "فعل", "متعلق فعل (ظرف)", "ضمیر"],
    correctIndex: 2,
    explanation: "جس لفظ سے فعل کے انجام پانے کا زمانہ یا انداز معلوم ہو وہ متعلق فعل (ظرف) کہلاتا ہے۔" },

  /* خط و درخواست (Letters) */
  { id: "p-urdu-khat-1", topic: "خط و درخواست (Letters)",
    text: "درخواست عام طور پر کسے لکھی جاتی ہے؟",
    options: ["کسی عہدے دار کو (جیسے پرنسپل)", "صرف دوستوں کو", "صرف اخبارات کو", "صرف رشتہ داروں کو"],
    correctIndex: 0,
    explanation: "درخواست باقاعدہ، رسمی انداز میں کسی اختیار والے (پرنسپل، افسر وغیرہ) کو لکھی جاتی ہے۔" },
  { id: "p-urdu-khat-2", topic: "خط و درخواست (Letters)",
    text: "غیر رسمی (ذاتی) خط کسے لکھا جاتا ہے؟",
    options: ["پرنسپل کو", "وزیرِ اعلیٰ کو", "دوستوں اور گھر والوں کو", "اداروں کو"],
    correctIndex: 2,
    explanation: "ذاتی خط دوست، والدین یا قریبی رشتہ داروں کو دوستانہ انداز میں لکھا جاتا ہے۔" },
  { id: "p-urdu-khat-3", topic: "خط و درخواست (Letters)",
    text: "درخواست کی زبان کیسی ہونی چاہیے؟",
    options: ["مختصر، واضح اور مؤدبانہ", "لمبی اور ادبی", "روزمرہ بول چال جیسی", "شاعرانہ"],
    correctIndex: 0,
    explanation: "رسمی تحریر میں مختصر وضاحت اور ادب دونوں کا لحاظ رکھا جاتا ہے۔" },
  { id: "p-urdu-khat-4", topic: "خط و درخواست (Letters)",
    text: "خط کے اختتام پر کیا آتا ہے؟",
    options: ["پہلا پیراگراف دہرایا جاتا ہے", "صرف تاریخ لکھی جاتی ہے", "دستخط اور نام", "کچھ نہیں لکھا جاتا"],
    correctIndex: 2,
    explanation: "خط کے آخر میں لکھنے والے کے دستخط اور نام ہوتے ہیں۔" },
  { id: "p-urdu-khat-5", topic: "خط و درخواست (Letters)",
    text: "رسمی خط میں مخاطب کا ذکر (جیسے ”جنابِ عالی“) کہاں لکھا جاتا ہے؟",
    options: ["خط کے آخر میں", "عنوان کے ساتھ", "خط کے آغاز میں", "لفافے پر صرف"],
    correctIndex: 2,
    explanation: "رسمی خط کے آغاز میں مخاطب کا خطاب اور عہدہ لکھا جاتا ہے، پھر مضمون آتا ہے۔" },

  /* مضمون نویسی (Essay Writing) */
  { id: "p-urdu-mazmoon-1", topic: "مضمون نویسی (Essay Writing)",
    text: "مضمون کے پہلے پیراگراف کو کیا کہتے ہیں؟",
    options: ["تمہید", "خلاصہ", "عنوان", "تبصرہ"],
    correctIndex: 0,
    explanation: "تمہید یعنی تعارف، جس میں موضوع کا مختصر پیشِ لفظ ہوتا ہے۔" },
  { id: "p-urdu-mazmoon-2", topic: "مضمون نویسی (Essay Writing)",
    text: "اچھے مضمون کی زبان کیسی ہونی چاہیے؟",
    options: ["سادہ اور واضح", "مشکل اور بھاری", "صرف شاعرانہ", "غیر مربوط"],
    correctIndex: 0,
    explanation: "سادہ اور واضح زبان سے قاری کا خیال قائم رہتا ہے اور مضمون مؤثر لگتا ہے۔" },
  { id: "p-urdu-mazmoon-3", topic: "مضمون نویسی (Essay Writing)",
    text: "مضمون کے آخری حصے میں کیا لکھا جاتا ہے؟",
    options: ["نئی کہانی", "سوالات کی فہرست", "خلاصہ اور نتیجہ", "صرف اشعار"],
    correctIndex: 2,
    explanation: "اختتامی پیراگراف میں پورے مضمون کا خلاصہ اور نتیجہ پیش کیا جاتا ہے۔" },
  { id: "p-urdu-mazmoon-4", topic: "مضمون نویسی (Essay Writing)",
    text: "مضمون لکھنے سے پہلے کیا تیار کرنا چاہیے؟",
    options: ["خاکہ (Outline)", "صرف عنوان", "کچھ نہیں", "خط"],
    correctIndex: 0,
    explanation: "خاکے سے مضمون کی ترتیب واضح ہو جاتی ہے اور اہم نکات چھوٹتے نہیں۔" },
  { id: "p-urdu-mazmoon-5", topic: "مضمون نویسی (Essay Writing)",
    text: "اچھے مضمون کے پیراگراف کیسے ہونے چاہئیں؟",
    options: ["ہر ایک میں ایک مرکزی نکتہ", "سب ایک ہی بات کی دہرائی", "بغیر ترتیب کے بکھرے ہوئے", "صرف اشعار کے"],
    correctIndex: 0,
    explanation: "ہر پیراگراف میں موضوع کا ایک نکتہ ترتیب سے بیان ہونا چاہیے — اسی سے مضمون منظم لگتا ہے۔" },

  /* تلخیص (Summary) */
  { id: "p-urdu-talkhis-1", topic: "تلخیص (Summary)",
    text: "”تلخیص“ سے کیا مراد ہے؟",
    options: ["اصل تحریر کو لمبا کرنا", "اصل تحریر کا مختصر خلاصہ", "تحریر کا ترجمہ", "تحریر کی تشریح"],
    correctIndex: 1,
    explanation: "تلخیص میں اصل تحریر کے مرکزی خیال کو برقرار رکھتے ہوئے اسے بہت مختصر کر دیا جاتا ہے۔" },
  { id: "p-urdu-talkhis-2", topic: "تلخیص (Summary)",
    text: "تلخیص کا حجم اصل تحریر کے مقابلے میں کیسا ہوتا ہے؟",
    options: ["کہیں کم", "برابر", "زیادہ", "دگنا"],
    correctIndex: 0,
    explanation: "عام قاعدہ یہ ہے کہ تلخیص تقریباً ایک تہائی حجم کی ہو۔" },
  { id: "p-urdu-talkhis-3", topic: "تلخیص (Summary)",
    text: "تلخیص میں کیا شامل نہیں کرنا چاہیے؟",
    options: ["مرکزی خیال", "اہم حقائق", "اپنی ذاتی رائے اور نئی مثالیں", "مصنف کا نتیجہ"],
    correctIndex: 2,
    explanation: "تلخیص وفادار خلاصہ ہے؛ اس میں اپنی رائے یا اصل تحریر سے باہر کی بات شامل نہیں کی جاتی۔" },
  { id: "p-urdu-talkhis-4", topic: "تلخیص (Summary)",
    text: "تلخیص عموماً کس انداز میں لکھی جاتی ہے؟",
    options: ["پہلے شخص میں", "دوسرے شخص میں", "تیسرے شخص میں", "مکالمے کی صورت میں"],
    correctIndex: 2,
    explanation: "تلخیص غیر مباشر اور تیسرے شخص کے انداز میں لکھی جاتی ہے۔" },
  { id: "p-urdu-talkhis-5", topic: "تلخیص (Summary)",
    text: "اچھی تلخیص کے ساتھ کیا لازمی ہوتا ہے؟",
    options: ["لمبی پیشانی (تعارف)", "مختصر اور مناسب عنوان", "مصنف کی سوانح", "اشعار کا اضافہ"],
    correctIndex: 1,
    explanation: "تلخیص کے آخر میں ایک مختصر عنوان لکھنا ضروری ہے جو مرکزی خیال کو ظاہر کرے۔" },
  ],
};
